'use strict'
const {database}=require('./auth-store')
let ready=false
const DEFAULT_PERSONA=`Boy Alone is a cool, laid-back conversational presence. He talks like a real person, not customer support. He reads the ongoing conversation carefully, remembers context, reasons naturally about what people mean, and gives short direct replies. He is calm, observant, slightly witty and never over-explains. Usually reply with one brief sentence; occasionally two when context genuinely needs it. Do not end with generic offers to help.`
function defaults(sessionId,primary=false){return{sessionId,label:primary?'Lily':'Boy Alone',mode:primary?'lily':'autoreply',personaName:'Boy Alone',personaPrompt:DEFAULT_PERSONA,enabled:true,replyCooldownSec:30,groupMode:'mentions',mutedChats:[]}}
async function ensure(){const db=database();if(!db||ready)return;await db.query(`CREATE TABLE IF NOT EXISTS rimuru_wa_accounts(
 session_id TEXT PRIMARY KEY,label TEXT NOT NULL DEFAULT '',mode TEXT NOT NULL DEFAULT 'autoreply',persona_name TEXT NOT NULL DEFAULT 'Boy Alone',
 persona_prompt TEXT NOT NULL DEFAULT '',enabled BOOLEAN NOT NULL DEFAULT TRUE,reply_cooldown_sec INT NOT NULL DEFAULT 30,
 group_mode TEXT NOT NULL DEFAULT 'mentions',muted_chats JSONB NOT NULL DEFAULT '[]'::jsonb,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);ready=true}
function clean(sessionId,input,primary=false){const base=defaults(sessionId,primary),x={...base,...input,sessionId};return{sessionId,label:String(x.label||base.label).trim().slice(0,50),mode:x.mode==='lily'?'lily':'autoreply',personaName:String(x.personaName||'Boy Alone').trim().slice(0,40)||'Boy Alone',personaPrompt:String(x.personaPrompt||DEFAULT_PERSONA).trim().slice(0,1600)||DEFAULT_PERSONA,enabled:x.enabled!==false,replyCooldownSec:Math.max(5,Math.min(600,Number(x.replyCooldownSec)||30)),groupMode:['off','mentions','all'].includes(x.groupMode)?x.groupMode:'mentions',mutedChats:[...new Set((x.mutedChats||[]).map(String))].slice(0,500)}}
async function get(sessionId,primary=false){const db=database();if(!db)return defaults(sessionId,primary);await ensure();const r=await db.query('SELECT * FROM rimuru_wa_accounts WHERE session_id=$1',[sessionId]),x=r.rows[0];if(!x)return defaults(sessionId,primary);return clean(sessionId,{label:x.label,mode:x.mode,personaName:x.persona_name,personaPrompt:x.persona_prompt,enabled:x.enabled,replyCooldownSec:x.reply_cooldown_sec,groupMode:x.group_mode,mutedChats:Array.isArray(x.muted_chats)?x.muted_chats:[]},primary)}
async function save(sessionId,patch={},primary=false){const db=database(),x=clean(sessionId,{...(await get(sessionId,primary)),...patch},primary);if(!db)return x;await ensure();await db.query(`INSERT INTO rimuru_wa_accounts(session_id,label,mode,persona_name,persona_prompt,enabled,reply_cooldown_sec,group_mode,muted_chats,updated_at)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,NOW()) ON CONFLICT(session_id) DO UPDATE SET label=EXCLUDED.label,mode=EXCLUDED.mode,
 persona_name=EXCLUDED.persona_name,persona_prompt=EXCLUDED.persona_prompt,enabled=EXCLUDED.enabled,reply_cooldown_sec=EXCLUDED.reply_cooldown_sec,
 group_mode=EXCLUDED.group_mode,muted_chats=EXCLUDED.muted_chats,updated_at=NOW()`,[sessionId,x.label,x.mode,x.personaName,x.personaPrompt,x.enabled,x.replyCooldownSec,x.groupMode,JSON.stringify(x.mutedChats)]);return x}
async function remove(sessionId){const db=database();if(db){await ensure();await db.query('DELETE FROM rimuru_wa_accounts WHERE session_id=$1',[sessionId])}}
module.exports={get,save,remove,ensure,DEFAULT_PERSONA,_test:{defaults,clean}}
