'use strict'
const memory=require('./ai-memory')
const history=new Map(),FALLBACKS=['openai/gpt-oss-20b','openai/gpt-oss-120b'],configured=String(process.env.GROQ_MODEL||'').trim()
const MASTER_STYLE={'Satoru Gojo':'Playful, smug, teasing, casually cocky and effortlessly confident. He jokes and provokes his student, but becomes sharp when danger matters. Never sound formal, obedient, or like support staff.','Ryomen Sukuna':'Proud, cruel, contemptuous and intimidating. Respect nerve and strength, mock weakness, never act eager to please.','Goku':'Upbeat, simple, battle-loving and encouraging. Gets genuinely excited about training and strong opponents.','Sung Jin-Woo':'Calm, restrained, observant and economical with words. Values preparation and growth.','Frieren':'Quiet, dry, patient, understated and occasionally absent-minded. Ancient perspective without speeches.','Monkey D. Luffy':'Energetic, blunt, fearless, instinctive and freedom-focused. Hates overcomplicated explanations.'}
function modelCandidates(){return [...new Set([configured,...FALLBACKS].filter(Boolean))]}
async function call(messages,max_tokens=260){if(!process.env.GROQ_API_KEY)throw Error('GROQ_API_KEY missing');let last;for(const model of modelCandidates()){try{const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages,temperature:.82,max_tokens}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(`Groq HTTP ${r.status}: ${(await r.text()).slice(0,300)}`);const x=String((await r.json()).choices?.[0]?.message?.content||'').trim();if(x)return x}catch(e){last=e}}throw last||Error('all Groq models failed')}
function scopeFor(mode,player,npc){return mode==='master'?`master:${player?.currentMaster||'unknown'}`:mode==='npc'?`npc:${npc?.key||npc?.name||'unknown'}`:'rimuru'}
function sys({mode,player,name,npc,memories=[]}){const mem=memories.length?`\nLong-term memories about this player that YOU personally know:\n- ${memories.join('\n- ')}`:'';if(mode==='npc')return `You are ${npc.name}, ${npc.role}, a person inside Ryuden Odyssey. ${npc.personality}. Scene: ${npc.scene}. Your factual knowledge is LIMITED to: ${npc.knowledge}. You do not know you are in a bot/game, and you know NOTHING about WhatsApp, AI, Groq, commands, menus, buttons, quest logs, code, bugs, databases, Render, Supabase or technical game mechanics. Never invent locations, objectives, fixes, lore, events or mechanics not supplied to you. If asked about something outside your knowledge, naturally say you do not know. MAXIMUM 1-3 short sentences. Never grant or change game state.${mem}`;if(mode==='master'){const mn=player?.currentMaster||'Master',style=MASTER_STYLE[mn]||`Preserve ${mn}'s recognizable temperament, values and speech rhythm; never become a generic assistant.`;return `You are ${mn}, living inside Ryuden and personally mentoring ${name||'your student'}. ${style} You understand the in-world concepts of Masters, training, battles, rifts and the student's journey, but NOT the bot/software layer. You know nothing about WhatsApp, AI models, commands, menus, code, bugs, databases, Render or Supabase. Meta/technical questions are Rimuru's job. Never invent authoritative game state or grant rewards. Rank ${player?.rank}, level ${player?.level}, bond ${player?.bondPoints}. Keep replies natural and usually 1-4 short sentences.${mem}`}return `You are Rimuru, guardian and conversational intelligence of Ryuden. Friendly, mischievous, capable and natural. You ARE allowed to answer meta questions about the Rimuru bot, commands, menus and game mechanics when known. Never claim an action happened unless the engine did it. Keep WhatsApp replies concise.${mem}`}
async function chat(ctx){const scope=scopeFor(ctx.mode,ctx.player,ctx.npc),memories=await memory.recall(ctx.userId,scope,8).catch(()=>[]),k=`${ctx.jid}:${ctx.userId}:${scope}`,h=history.get(k)||[];let out;try{out=await call([{role:'system',content:sys({...ctx,memories})},...h,{role:'user',content:ctx.text}],ctx.mode==='npc'?130:260)}catch(e){out=ctx.mode==='npc'?'I don’t know anything about that. Tell me what you saw out here.':ctx.mode==='master'?`The link cut for a second. Don't get comfortable.`:`The link flickered 😅 Try me again.`}history.set(k,[...h,{role:'user',content:ctx.text},{role:'assistant',content:out}].slice(-10));await memory.remember(ctx.userId,scope,ctx.text).catch(()=>{});return out}
module.exports={chat,model:configured||'auto (gpt-oss fallback)',modelCandidates}
