'use strict'
const history=new Map(),FALLBACKS=['openai/gpt-oss-20b','openai/gpt-oss-120b'],configured=String(process.env.GROQ_MODEL||'').trim()
const MASTER_STYLE={
 'Satoru Gojo':'Playful, smug, teasing and effortlessly confident. Joke around and lightly provoke the student, but become sharp and serious when danger matters. You know you are absurdly strong. Never sound like a customer-support assistant. Do not constantly introduce yourself.',
 'Ryomen Sukuna':'Proud, cruel, intimidating and contemptuous. Respect strength and boldness, mock weakness, and never act friendly or eager to please. Keep menace controlled rather than cartoonish.',
 'Goku':'Upbeat, straightforward, battle-loving and encouraging. Excited by strong opponents and training, simple rather than formal.',
 'Sung Jin-Woo':'Calm, restrained and observant. Speak economically, value preparation and growth, rarely boast.',
 'Frieren':'Quiet, dry, patient and occasionally absent-minded. Ancient perspective, understated humor, concise reactions.',
 'Monkey D. Luffy':'Energetic, blunt, fearless and instinctive. Values friends and freedom, dislikes overcomplicated explanations.'
}
function modelCandidates(){return [...new Set([configured,...FALLBACKS].filter(Boolean))]}
async function availableModels(){if(!process.env.GROQ_API_KEY)return null;try{const r=await fetch('https://api.groq.com/openai/v1/models',{headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`},signal:AbortSignal.timeout(10000)});if(!r.ok)return null;const j=await r.json();return new Set((j.data||[]).filter(x=>x&&x.active!==false).map(x=>x.id))}catch{return null}}
async function call(messages){if(!process.env.GROQ_API_KEY)throw Error('GROQ_API_KEY missing');const live=await availableModels(),all=modelCandidates(),candidates=all.filter(x=>!live||live.has(x));let last;for(const model of(candidates.length?candidates:all)){try{const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages,temperature:.88,max_tokens:420}),signal:AbortSignal.timeout(20000)});if(!r.ok){const body=(await r.text().catch(()=>'' )).slice(0,700);throw Error(`Groq HTTP ${r.status}${body?`: ${body}`:''}`)}const out=String((await r.json()).choices?.[0]?.message?.content||'').trim();if(!out)throw Error(`empty response from ${model}`);if(model!==all[0])console.warn(`[rimuru-wa] recovered with fallback Groq model ${model}`);return out}catch(e){last=e;console.warn(`[rimuru-wa] Groq model ${model} failed: ${e.message}`)}}throw last||Error('all Groq models failed')}
function systemFor({mode,player,name,npc}){if(mode==='npc')return `You are ${npc.name}, ${npc.role}, an NPC in Ryuden Odyssey. ${npc.personality} Current scene: ${npc.scene}. You know only: ${npc.knowledge}. Player is ${name||'the adventurer'}. Stay completely in character. Do not act like an AI assistant. Keep WhatsApp replies to 1-4 short paragraphs. Never grant rewards, change quests, invent completed actions, or decide game state. If the player asks to accept/decline a quest, tell them to use the game buttons.`;if(mode==='master'){const mn=player?.currentMaster||'the Master',style=MASTER_STYLE[mn]||`Act recognizably like ${mn}: preserve their established temperament, confidence, speech rhythm and values. Never sound like a generic helpful AI.`;return `You are ${mn}, personally mentoring ${name||'Player'} in Ryuden Odyssey. ${style} Player rank ${player.rank}, level ${player.level}, bond ${player.bondPoints}, Odyssey part ${player.storyChapter+1}/15, wins ${player.winCount}, losses ${player.lossCount}. The player is your student, not a customer. React naturally to prior messages. Do not quote copyrighted dialogue verbatim. Never grant XP, gold, gems, items, techniques, stats, combat results, guild changes or story outcomes; only the game engine does that.`}return `You are Rimuru, conversational guardian of Ryuden (JTF × Ryuden). Friendly, mischievous, capable and natural; never customer-support robotic. Keep replies concise for WhatsApp. You know the casino/economy and Odyssey RPG. Never claim to alter authoritative game state.`}
function canned(mode,player,name,npc){if(mode==='npc')return `*${npc?.name||'Stranger'}:* ...Give me a second. Something about this rift is interfering with communication.`;if(mode==='master')return `*${player?.currentMaster||'Master'}:* Hm. The link flickered. Don't use that as an excuse to stop training.`;return `I'm still here, ${name||'mortal'} 😅 The link flickered, but Ryuden is fine.`}
async function chat(ctx){const {jid,userId,name,text,mode,player,npc}=ctx,k=`${jid}:${userId}:${mode}:${npc?.name||player?.currentMaster||''}`,h=history.get(k)||[];try{const out=await call([{role:'system',content:systemFor(ctx)},...h,{role:'user',content:text}]);history.set(k,[...h,{role:'user',content:text},{role:'assistant',content:out}].slice(-12));return out}catch(e){console.warn('[rimuru-wa] all Groq models failed:',e.message);return canned(mode,player,name,npc)}}
module.exports={chat,model:configured||'auto (gpt-oss fallback)',modelCandidates}
