'use strict'
const {isOwner}=require('./access'),{isModerator,canonicalUserId}=require('./economy-router')

function contextInfo(content={}){return content.extendedTextMessage?.contextInfo||content.imageMessage?.contextInfo||content.videoMessage?.contextInfo||content.stickerMessage?.contextInfo||{}}
function unwrap(message={}){let x=message;for(let i=0;i<5;i++){x=x?.ephemeralMessage?.message||x?.viewOnceMessage?.message||x?.viewOnceMessageV2?.message||x?.viewOnceMessageV2Extension?.message||x;const direct=x?.stickerMessage;if(direct)return direct;if(!x)break}return null}
function cursedWebp(input,variant=1){if(!Buffer.isBuffer(input)||input.length<16||input.toString('ascii',0,4)!=='RIFF'||input.toString('ascii',8,12)!=='WEBP')throw Error('The replied file is not a valid WebP sticker.');const out=Buffer.from(input);if(variant===2){out.writeUInt32LE(Math.min(0xffffffff,out.length+4096),4);return out}if(variant===3){const tag=Buffer.from('LILY_CURSED_STICKER_TEST');const pad=tag.length%2?Buffer.from([0]):Buffer.alloc(0),head=Buffer.alloc(8);head.write('JUNK',0,'ascii');head.writeUInt32LE(tag.length,4);const joined=Buffer.concat([out,head,tag,pad]);joined.writeUInt32LE(joined.length-8,4);return joined}return Buffer.concat([out,Buffer.from('LILY-CURSED-WEBP-TRAILER')])}

function createCursedSticker({baileys,logger}){return{async handle(sock,m,content){const text=String(content.conversation||content.extendedTextMessage?.text||'').trim(),match=text.match(/^\/cursedsticker(?:\s+([123]))?(?:\s|$)/i);if(!match)return false;const jid=m.key.remoteJid,userId=canonicalUserId(m.key);if(!(isOwner(userId)||await isModerator(userId))){await sock.sendMessage(jid,{text:'🧪 This experiment is limited to Lily moderators for now.'},{quoted:m});return true}const sticker=unwrap(contextInfo(content).quotedMessage);if(!sticker){await sock.sendMessage(jid,{text:'Reply directly to a WhatsApp sticker with */cursedsticker*.'},{quoted:m});return true}const chunks=[];for await(const chunk of await baileys.downloadContentFromMessage(sticker,'sticker'))chunks.push(chunk);const original=Buffer.concat(chunks);if(!original.length)throw Error('The replied sticker could not be downloaded.');if(original.length>1024*1024)throw Error('That sticker is too large for the compatibility experiment.');const variant=Number(match[1]||1),mutated=cursedWebp(original,variant);await sock.sendMessage(jid,{sticker:mutated},{quoted:m});logger.info({jid,userId,variant,originalBytes:original.length,mutatedBytes:mutated.length},'cursed sticker compatibility test sent');return true}}}
module.exports={createCursedSticker,_test:{contextInfo,unwrap,cursedWebp}}
