'use strict'
const crypto=require('crypto'),{database}=require('./auth-store'),{canonicalUserId,displayName,quotedUserId}=require('./economy-router')
function db(){const d=database();if(!d)throw Error('DATABASE_URL is required for duels');return d}let ready=false
async function ensureSchema(){if(ready)return;await db().query(`CREATE TABLE IF NOT EXISTS rimuru_wa_duels(duel_id TEXT PRIMARY KEY,chat_jid TEXT NOT NULL,challenger_id TEXT NOT NULL,opponent_id TEXT NOT NULL,duel_type TEXT NOT NULL DEFAULT 'battle',status TEXT NOT NULL DEFAULT 'pending',combat_state JSONB NOT NULL DEFAULT '{}'::jsonb,winner_id TEXT,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS rimuru_wa_duels_chat_status ON rimuru_wa_duels(chat_jid,status);`);ready=true}
const actor=m=>canonicalUserId(m.key),label=(p,f)=>p?.username||f||'Player'
function mentioned(content){const c=content.extendedTextMessage?.contextInfo||content.imageMessage?.contextInfo||{},jid=(c.mentionedJid||[])[0];return jid?String(jid).split(':')[0].split('@')[0]:quotedUserId(content)}
async function player(id){return(await db().query('SELECT * FROM rimuru_rpg_players WHERE user_id=$1',[id])).rows[0]||null}async function row(id){await ensureSchema();return(await db().query('SELECT * FROM rimuru_wa_duels WHERE duel_id=$1',[id])).rows[0]||null}
function createDuels({sendButtons}){const send=(s,j,m,t,x={})=>s.sendMessage(j,{text:t,...x},{quoted:m}),buttons=(s,j,m,b,f,d,o)=>sendButtons(s,j,b,f,d,o)
 async function challenge(s,m,content){const jid=m.key.remoteJid,a=actor(m),b=mentioned(content);if(!jid.endsWith('@g.us'))return send(s,jid,m,'🥊 Duels must be challenged inside the Duels group.'),true;if(!b)return send(s,jid,m,'Reply to or @mention a registered player with */duel @player*.'),true;if(a===b)return send(s,jid,m,'😭 You cannot duel yourself.'),true;const[pa,pb]=await Promise.all([player(a),player(b)]);if(!pa||!pb)return send(s,jid,m,'🌊 Both fighters must use */start* and create their Odyssey profiles first.'),true;await ensureSchema();await db().query("UPDATE rimuru_wa_duels SET status='expired',updated_at=NOW() WHERE status='pending' AND expires_at<NOW()");const id=crypto.randomUUID().replace(/-/g,'').slice(0,12);await db().query("INSERT INTO rimuru_wa_duels(duel_id,chat_jid,challenger_id,opponent_id,duel_type,expires_at) VALUES($1,$2,$3,$4,'battle',NOW()+INTERVAL '5 minutes')",[id,jid,a,b]);await buttons(s,jid,m,`🥊 *DUEL CHALLENGE*\n\n⚔️ *${label(pa,displayName(m))}* challenged *${label(pb,b)}*.\n\nMode: *Odyssey Battle*\nExpires in: *5 minutes*`,'LILY • RYUDEN DUELS',[['✅ Accept',`duel_accept_${id}`],['❌ Decline',`duel_decline_${id}`]],b);return true}
 async function decline(s,m,id){const d=await row(id),u=actor(m);if(!d||d.status!=='pending')return send(s,m.key.remoteJid,m,'⌛ This duel challenge is no longer active.'),true;if(u!==d.opponent_id)return send(s,m.key.remoteJid,m,'🔒 Only the challenged player can decline this duel.'),true;await db().query("UPDATE rimuru_wa_duels SET status='declined',updated_at=NOW() WHERE duel_id=$1",[id]);return send(s,d.chat_jid,m,'❌ *DUEL DECLINED*\n\nThe challenge has been refused.'),true}
 async function accept(s,m,id){const d=await row(id),u=actor(m);if(!d||d.status!=='pending'||new Date(d.expires_at)<new Date())return send(s,m.key.remoteJid,m,'⌛ This duel challenge has expired.'),true;if(u!==d.opponent_id)return send(s,m.key.remoteJid,m,'🔒 Only the challenged player can accept this duel.'),true;const[a,b]=await Promise.all([player(d.challenger_id),player(d.opponent_id)]),state={turn:d.challenger_id,round:1,guard:{},fighters:{[d.challenger_id]:{name:label(a,d.challenger_id),hp:+a.hp,maxHp:+a.hp,atk:+a.atk,def:+a.def},[d.opponent_id]:{name:label(b,d.opponent_id),hp:+b.hp,maxHp:+b.hp,atk:+b.atk,def:+b.def}}};await db().query("UPDATE rimuru_wa_duels SET status='active',combat_state=$2::jsonb,updated_at=NOW() WHERE duel_id=$1",[id,JSON.stringify(state)]);await panel(s,m,{...d,status:'active',combat_state:state},'The challenge was accepted. Fight!');return true}
 async function panel(s,m,d,result=''){const st=d.combat_state,ids=Object.keys(st.fighters),a=st.fighters[ids[0]],b=st.fighters[ids[1]],cur=st.fighters[st.turn];return buttons(s,d.chat_jid,m,`🥊 *ODYSSEY DUEL • ROUND ${st.round}*\n\n${result?`${result}\n\n`:''}⚔️ *${a.name}* — ❤️ ${Math.max(0,a.hp)}/${a.maxHp}\n⚔️ *${b.name}* — ❤️ ${Math.max(0,b.hp)}/${b.maxHp}\n\n🎯 Turn: *${cur.name}*`,'LILY • RYUDEN DUELS',[['⚔️ Attack',`duel_attack_${d.duel_id}`],['🛡️ Guard',`duel_guard_${d.duel_id}`],['🏳️ Forfeit',`duel_forfeit_${d.duel_id}`]],st.turn)}
 async function finish(s,m,d,winner,result){const st=d.combat_state,loser=Object.keys(st.fighters).find(x=>x!==winner);await db().query("UPDATE rimuru_wa_duels SET status='completed',winner_id=$2,combat_state=$3::jsonb,updated_at=NOW() WHERE duel_id=$1",[d.duel_id,winner,JSON.stringify(st)]);await db().query('UPDATE rimuru_rpg_players SET win_count=win_count+1,updated_at=NOW() WHERE user_id=$1',[winner]);await db().query('UPDATE rimuru_rpg_players SET loss_count=loss_count+1,updated_at=NOW() WHERE user_id=$1',[loser]);await send(s,d.chat_jid,m,`🏆 *DUEL COMPLETE*\n\n${result}\n\n👑 Winner: *${st.fighters[winner].name}*\n\nNo Gold or inventory changed.`);return true}
 async function action(s,m,kind,id){const d=await row(id),u=actor(m);if(!d||d.status!=='active')return send(s,m.key.remoteJid,m,'⌛ This duel is no longer active.'),true;const st=d.combat_state;if(st.turn!==u)return send(s,d.chat_jid,m,'⏳ Wait for your turn.'),true;const ids=Object.keys(st.fighters),enemyId=ids.find(x=>x!==u),me=st.fighters[u],enemy=st.fighters[enemyId];if(kind==='forfeit')return finish(s,m,d,enemyId,`${me.name} forfeited.`);let result;if(kind==='guard'){st.guard[u]=true;result=`🛡️ ${me.name} raised their guard.`}else{let damage=Math.max(8,Math.round(me.atk*1.15+Math.random()*8-enemy.def*.45));if(st.guard[enemyId]){damage=Math.max(3,Math.round(damage*.45));delete st.guard[enemyId]}enemy.hp-=damage;result=`⚔️ ${me.name} struck ${enemy.name} for *${damage}* damage.`;if(enemy.hp<=0)return finish(s,m,{...d,combat_state:st},u,result)}st.turn=enemyId;st.round++;await db().query('UPDATE rimuru_wa_duels SET combat_state=$2::jsonb,updated_at=NOW() WHERE duel_id=$1',[id,JSON.stringify(st)]);await panel(s,m,{...d,combat_state:st},result);return true}
 async function route(s,m,c,content){if(['/duel','/challenge'].includes(c.command))return challenge(s,m,content);if(c.command==='/duels'){await send(s,m.key.remoteJid,m,'🥊 *RYUDEN DUELS*\n\nChallenge someone with */duel @player*.\nCurrent mode: *Odyssey Battle*.\nCard Battle and Hybrid are reserved for the next expansion.');return true}return false}
 async function section(s,m,id){const x=id.match(/^duel_(accept|decline|attack|guard|forfeit)_([a-z0-9]+)$/);if(!x)return false;if(x[1]==='accept')return accept(s,m,x[2]);if(x[1]==='decline')return decline(s,m,x[2]);return action(s,m,x[1],x[2])}
 return{route,section,ensureSchema}}
module.exports={createDuels,ensureSchema}
