'use strict'

const crypto = require('crypto')
const { database } = require('./auth-store')
const { canonicalUserId, displayName } = require('./economy-router')
const cardPower = require('./card-power')
const rpgStore = require('./rpg-store')
const AI_ID = 'ai:lily'
let ready = false
function db () { const d = database(); if (!d) throw Error('DATABASE_URL is required for Duels'); return d }
function actor (m) { return canonicalUserId(m.key) }
function label (p, fallback) { return String(p?.display_name || p?.displayName || p?.username || p?.name || fallback || 'Fighter').slice(0, 40) }
function mentioned (content) { const x = content.extendedTextMessage?.contextInfo || content.imageMessage?.contextInfo || {}; return (x.mentionedJid || [])[0] || x.participantAlt || x.participant || null }
function bare (jid) { return String(jid || '').split(':')[0].split('@')[0] }
function uid () { return crypto.randomUUID().replace(/-/g, '').slice(0, 12) }
function random (min, max) { return min + Math.floor(Math.random() * (max - min + 1)) }
async function ensureSchema () { if (ready) return; await db().query(`CREATE TABLE IF NOT EXISTS rimuru_wa_duels(duel_id TEXT PRIMARY KEY,chat_jid TEXT NOT NULL,challenger_id TEXT NOT NULL,opponent_id TEXT NOT NULL,duel_type TEXT NOT NULL DEFAULT 'battle',status TEXT NOT NULL DEFAULT 'pending',combat_state JSONB NOT NULL DEFAULT '{}'::jsonb,winner_id TEXT,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS rimuru_wa_duels_chat_status ON rimuru_wa_duels(chat_jid,status);`); await cardPower.ensureSchema(); ready = true }
async function player (id, suggestedName = '') { const user = (await db().query('SELECT user_id,display_name FROM rimuru_wa_users WHERE user_id=$1', [id])).rows[0]; if (!user) return null; const p = await rpgStore.ensurePlayer(id, suggestedName || user.display_name || ''); return { ...p, display_name: suggestedName || user.display_name || p.username || '' } }
async function resolveOpponent (sock, jid, reference) { if (!reference) return null; const wanted = bare(reference), candidates = new Map([[wanted, '']]); try { const meta = await sock.groupMetadata(jid); for (const p of meta.participants || []) { const ids = [p.id, p.lid, p.phoneNumber].filter(Boolean); if (ids.some(x => bare(x) === wanted)) for (const x of ids) candidates.set(bare(x), p.notify || p.name || p.verifiedName || '') } } catch {} const ids = [...candidates.keys()]; const found = (await db().query('SELECT user_id,display_name FROM rimuru_wa_users WHERE user_id=ANY($1::text[]) ORDER BY CASE WHEN user_id=$2 THEN 0 ELSE 1 END LIMIT 1', [ids, wanted])).rows[0]; return found ? { id: found.user_id, name: found.display_name || candidates.get(found.user_id) || '' } : { id: wanted, name: candidates.get(wanted) || '' } }
async function row (id) { await ensureSchema(); return (await db().query('SELECT * FROM rimuru_wa_duels WHERE duel_id=$1', [id])).rows[0] || null }
async function saveState (id, state, status = 'active') { await db().query('UPDATE rimuru_wa_duels SET combat_state=$2::jsonb,status=$3,updated_at=NOW() WHERE duel_id=$1', [id, JSON.stringify(state), status]) }
function rpgUnit (p, id) { const hp = Math.max(100, Number(p.hp) || Number(p.max_hp) || 120); return { kind: 'rpg', key: `rpg:${id}`, name: label(p, id), hp, maxHp: hp, attack: Math.max(20, Number(p.atk) || 25), defense: Math.max(10, Number(p.def) || 12), speed: Math.max(25, Number(p.speed) || 45), technique: Math.max(25, Number(p.technique) || 45), signature: 'Odyssey Art' } }
function cardUnit (x) { return { kind: 'card', key: `card:${x.cardKey}`, name: `${x.name} T${x.tier}`, hp: x.hp, maxHp: x.hp, attack: x.attack, defense: x.defense, speed: x.speed, technique: x.technique, signature: x.signature, power: x.power } }
function aiEcho (unit, index) { const mult = 0.94 + index * 0.03; return { ...unit, key: `echo:${index}:${unit.key}`, name: `Lily's ${unit.name} Echo`, hp: Math.round(unit.maxHp * mult), maxHp: Math.round(unit.maxHp * mult), attack: Math.round(unit.attack * mult), defense: Math.round(unit.defense * mult), speed: Math.round(unit.speed * mult), technique: Math.round(unit.technique * mult) } }
async function teamFor (userId, type, logger) { const units = []; if (type === 'battle' || type === 'hybrid') { const p = await player(userId); if (!p) throw new Error('Create your Odyssey character with /rpg first.'); units.push(rpgUnit(p, userId)) } if (type === 'card' || type === 'hybrid') { const cards = await cardPower.deck(userId, type === 'hybrid' ? 2 : 3, { logger }); if (!cards.length) throw new Error('You need at least one owned card. Use /collection to check.'); units.push(...cards.map(cardUnit)) } return units }
function aliveIndex (team) { return team.units.findIndex(x => x.hp > 0) }
function currentUnit (team) { return team.units[team.active] }
function teamName (state, id) { return state.teams[id]?.name || (id === AI_ID ? 'Lily' : id) }
function modeName (type) { return type === 'card' ? 'Card Battle' : type === 'hybrid' ? 'Hybrid Battle' : 'Odyssey Battle' }
function actionButtons (id) { return [['⚔️ Attack', `duel_attack_${id}`], ['💥 Special', `duel_special_${id}`], ['🛡️ Guard', `duel_guard_${id}`], ['🏳️ Forfeit', `duel_forfeit_${id}`]] }

function createDuels ({ sendButtons, logger }) {
  const send = (s, j, m, t) => s.sendMessage(j, { text: t }, { quoted: m })
  const buttons = (s, j, m, b, f, d, o) => sendButtons(s, j, b, f, d, o)
  async function beginSelection (s, m, opponentRef, forcedType = '') {
    const jid = m.key.remoteJid, challenger = actor(m), p = await player(challenger, displayName(m)), resolved = opponentRef === AI_ID ? { id: AI_ID, name: 'Lily' } : await resolveOpponent(s, jid, opponentRef), opponentId = resolved?.id
    if (!jid.endsWith('@g.us')) { await send(s, jid, m, '🥊 Duels must begin inside the Duels group.'); return true }
    if (!p) { await send(s, jid, m, '🌊 Use */start* and create your Odyssey profile first.'); return true }
    if (opponentId !== AI_ID) { if (!opponentId) { await send(s, jid, m, 'Reply to or @mention a player with */duel @player*, or use */duel ai*.'); return true } if (opponentId === challenger) { await send(s, jid, m, '😭 You cannot duel yourself. Try */duel ai*.'); return true } if (!(await player(opponentId, resolved.name))) { await send(s, jid, m, '🌊 That fighter has not registered yet. Ask them to use */start*.'); return true } }
    await ensureSchema(); await db().query("UPDATE rimuru_wa_duels SET status='expired',updated_at=NOW() WHERE status IN ('selecting','pending') AND expires_at<NOW()")
    const id = uid(); await db().query("INSERT INTO rimuru_wa_duels(duel_id,chat_jid,challenger_id,opponent_id,duel_type,status,expires_at) VALUES($1,$2,$3,$4,'select','selecting',NOW()+INTERVAL '5 minutes')", [id, jid, challenger, opponentId])
    if (forcedType) return selectMode(s, m, forcedType, id)
    const opponent = opponentId === AI_ID ? 'Lily-controlled AI' : label(await player(opponentId, resolved.name), 'Opponent')
    await buttons(s, jid, m, `⚔️ *CHOOSE DUEL STYLE*\n\nChallenger: *${label(p, displayName(m))}*\nOpponent: *${opponent}*\n\n🥊 Battle — Odyssey characters\n🃏 Card Battle — up to 3 owned cards\n🔥 Hybrid — character + up to 2 cards`, 'LILY • RYUDEN DUELS', [['🥊 Battle', `duel_mode_battle_${id}`], ['🃏 Card Battle', `duel_mode_card_${id}`], ['🔥 Hybrid', `duel_mode_hybrid_${id}`]], challenger); return true
  }
  async function selectMode (s, m, type, id) {
    const d = await row(id), u = actor(m); if (!d || d.status !== 'selecting' || new Date(d.expires_at) < new Date()) { await send(s, m.key.remoteJid, m, '⌛ That duel setup expired.'); return true } if (u !== d.challenger_id) { await send(s, d.chat_jid, m, '🔒 Only the challenger can choose the duel style.'); return true }
    try { await teamFor(d.challenger_id, type, logger) } catch (e) { await send(s, d.chat_jid, m, `❌ ${e.message}`); return true }
    await db().query('UPDATE rimuru_wa_duels SET duel_type=$2,status=$3,updated_at=NOW() WHERE duel_id=$1', [id, type, d.opponent_id === AI_ID ? 'starting' : 'pending'])
    if (d.opponent_id === AI_ID) return startFight(s, m, { ...d, duel_type: type, status: 'starting' })
    const [challenger, opponent] = await Promise.all([player(d.challenger_id), player(d.opponent_id)])
    await buttons(s, d.chat_jid, m, `⚔️ *DUEL CHALLENGE*\n\n*${label(challenger, 'Challenger')}* challenged *${label(opponent, 'Opponent')}*.\n\nMode: *${modeName(type)}*\nExpires in: *5 minutes*`, 'LILY • RYUDEN DUELS', [['✅ Accept', `duel_accept_${id}`], ['❌ Decline', `duel_decline_${id}`]], d.opponent_id); return true
  }
  async function decline (s, m, id) { const d = await row(id), u = actor(m); if (!d || d.status !== 'pending') { await send(s, m.key.remoteJid, m, '⌛ This challenge is no longer active.'); return true } if (u !== d.opponent_id) { await send(s, d.chat_jid, m, '🔒 Only the challenged player can decline.'); return true } await db().query("UPDATE rimuru_wa_duels SET status='declined',updated_at=NOW() WHERE duel_id=$1", [id]); await send(s, d.chat_jid, m, '❌ *DUEL DECLINED*\n\nThe challenge was refused.'); return true }
  async function accept (s, m, id) { const d = await row(id), u = actor(m); if (!d || d.status !== 'pending' || new Date(d.expires_at) < new Date()) { await send(s, m.key.remoteJid, m, '⌛ This challenge expired.'); return true } if (u !== d.opponent_id) { await send(s, d.chat_jid, m, '🔒 Only the challenged player can accept.'); return true } return startFight(s, m, d) }
  async function startFight (s, m, d) {
    try { const left = await teamFor(d.challenger_id, d.duel_type, logger), right = d.opponent_id === AI_ID ? left.map(aiEcho) : await teamFor(d.opponent_id, d.duel_type, logger); const first = (left[0]?.speed || 0) >= (right[0]?.speed || 0) ? d.challenger_id : d.opponent_id; const state = { version: 2, type: d.duel_type, isAi: d.opponent_id === AI_ID, turn: first === AI_ID ? d.challenger_id : first, round: 1, guard: {}, cooldown: {}, teams: { [d.challenger_id]: { name: label(await player(d.challenger_id), d.challenger_id), active: 0, units: left }, [d.opponent_id]: { name: d.opponent_id === AI_ID ? 'Lily' : label(await player(d.opponent_id), d.opponent_id), active: 0, units: right } } }; await saveState(d.duel_id, state); await panel(s, m, { ...d, status: 'active', combat_state: state }, `${modeName(d.duel_type)} started!`) } catch (e) { await db().query("UPDATE rimuru_wa_duels SET status='cancelled',updated_at=NOW() WHERE duel_id=$1", [d.duel_id]); await send(s, d.chat_jid, m, `❌ Duel cancelled: ${e.message}`) } return true
  }
  function statusLine (team) { return team.units.map((x, i) => `${i === team.active ? '▶️' : x.hp > 0 ? '▫️' : '💀'} ${x.name} — ❤️ ${Math.max(0, x.hp)}/${x.maxHp}`).join('\n') }
  async function panel (s, m, d, result = '') { const st = d.combat_state, turnUnit = currentUnit(st.teams[st.turn]), ids = Object.keys(st.teams); await buttons(s, d.chat_jid, m, `⚔️ *${modeName(st.type).toUpperCase()} • ROUND ${st.round}*\n\n${result ? `${result}\n\n` : ''}*${st.teams[ids[0]].name}*\n${statusLine(st.teams[ids[0]])}\n\n*${st.teams[ids[1]].name}*\n${statusLine(st.teams[ids[1]])}\n\n🎯 Turn: *${turnUnit.name}*`, 'LILY • DAMAGE AND WINNERS ARE ENGINE-CONTROLLED', actionButtons(d.duel_id), st.turn) }
  async function finish (s, m, d, winner, result) { const st = d.combat_state; await db().query("UPDATE rimuru_wa_duels SET status='completed',winner_id=$2,combat_state=$3::jsonb,updated_at=NOW() WHERE duel_id=$1", [d.duel_id, winner, JSON.stringify(st)]); if (!st.isAi) { const loser = Object.keys(st.teams).find(x => x !== winner); await db().query('UPDATE rimuru_rpg_players SET win_count=win_count+1,updated_at=NOW() WHERE user_id=$1', [winner]); await db().query('UPDATE rimuru_rpg_players SET loss_count=loss_count+1,updated_at=NOW() WHERE user_id=$1', [loser]) } await send(s, d.chat_jid, m, `🏆 *DUEL COMPLETE*\n\n${result}\n\n👑 Winner: *${teamName(st, winner)}*\n\nNo Gold, cards, or inventory changed.`); return true }
  function strike (state, attackerId, kind) { const defenderId = Object.keys(state.teams).find(x => x !== attackerId), a = currentUnit(state.teams[attackerId]), b = currentUnit(state.teams[defenderId]); if (kind === 'guard') { state.guard[attackerId] = true; return { text: `🛡️ ${a.name} raised their guard.`, defenderId } } const special = kind === 'special' && !state.cooldown[attackerId]; if (kind === 'special' && !special) return { text: `⏳ ${a.name}'s special is still cooling down.`, defenderId, invalid: true }; const scale = special ? 1.2 : 0.9, technique = special ? 0.3 : 0.12; let damage = Math.max(5, Math.round(a.attack * scale + a.technique * technique + random(0, 9) - b.defense * 0.38)); if (state.guard[defenderId]) { damage = Math.max(3, Math.round(damage * 0.5)); delete state.guard[defenderId] } if (special) state.cooldown[attackerId] = 2; b.hp -= damage; const move = special ? `💥 ${a.name} used *${a.signature}*` : `⚔️ ${a.name} attacked`; let text = `${move} for *${damage}* damage.`; if (b.hp <= 0) { b.hp = 0; text += `\n💀 ${b.name} was defeated.`; state.teams[defenderId].active = aliveIndex(state.teams[defenderId]) } return { text, defenderId } }
  function tickCooldown (state, id) { if (state.cooldown[id]) { state.cooldown[id]--; if (state.cooldown[id] <= 0) delete state.cooldown[id] } }
  async function action (s, m, kind, id) { const d = await row(id), u = actor(m); if (!d || d.status !== 'active' || !d.combat_state?.teams) { await send(s, m.key.remoteJid, m, '⌛ This duel is no longer active.'); return true } const st = d.combat_state; if (st.turn !== u) { await send(s, d.chat_jid, m, '⏳ Wait for your turn.'); return true } const enemyId = Object.keys(st.teams).find(x => x !== u); if (kind === 'forfeit') return finish(s, m, d, enemyId, `${teamName(st, u)} forfeited.`); const out = strike(st, u, kind); if (out.invalid) { await panel(s, m, { ...d, combat_state: st }, out.text); return true } tickCooldown(st, u); if (aliveIndex(st.teams[enemyId]) < 0) return finish(s, m, { ...d, combat_state: st }, u, out.text); st.turn = enemyId; st.round++; let result = out.text; if (enemyId === AI_ID) { const aiUnit = currentUnit(st.teams[AI_ID]), aiKind = aiUnit.hp < aiUnit.maxHp * 0.3 && Math.random() < 0.3 ? 'guard' : !st.cooldown[AI_ID] && Math.random() < 0.35 ? 'special' : 'attack'; const aiOut = strike(st, AI_ID, aiKind); tickCooldown(st, AI_ID); result += `\n\n${aiOut.text}`; if (aliveIndex(st.teams[u]) < 0) return finish(s, m, { ...d, combat_state: st }, AI_ID, result); st.turn = u; st.round++ } await saveState(id, st); await panel(s, m, { ...d, combat_state: st }, result); return true }
  async function route (s, m, commandParts, content) { const command = commandParts?.command; if (!['/duel', '/duels', '/challenge', '/cardbattle', '/hybridbattle'].includes(command)) return false; if (command === '/duels') { await send(s, m.key.remoteJid, m, '⚔️ *RYUDEN DUELS*\n\n*/duel @player* — PvP mode selector\n*/duel ai* — Lily PvE mode selector\n*/cardbattle ai* — direct Card PvE\n*/hybridbattle ai* — direct Hybrid PvE\n*/deck #id #id #id* — choose card team\n\n🥊 Odyssey • 🃏 Cards • 🔥 Hybrid'); return true } const raw = String(content.conversation || content.extendedTextMessage?.text || '').trim(), wantsAi = /\sai\s*$/i.test(raw), forced = command === '/cardbattle' ? 'card' : command === '/hybridbattle' ? 'hybrid' : ''; return beginSelection(s, m, wantsAi ? AI_ID : mentioned(content), forced) }
  async function section (s, m, id) { let x = id.match(/^duel_mode_(battle|card|hybrid)_([a-z0-9]+)$/); if (x) return selectMode(s, m, x[1], x[2]); x = id.match(/^duel_(accept|decline|attack|special|guard|forfeit)_([a-z0-9]+)$/); if (!x) return false; if (x[1] === 'accept') return accept(s, m, x[2]); if (x[1] === 'decline') return decline(s, m, x[2]); return action(s, m, x[1], x[2]) }
  return { route, section, ensureSchema }
}
module.exports = { createDuels, ensureSchema, _test: { rpgUnit, cardUnit, aiEcho, modeName, label, bare } }
