'use strict'
function canonicalUserId(key={}){const c=[key.participantAlt,key.remoteJidAlt,key.participant,key.remoteJid].filter(Boolean),jid=c.find(v=>String(v).endsWith('@s.whatsapp.net'))||c[0]||'';return String(jid).split(':')[0].split('@')[0]}
function quotedUserId(content={}){const x=content.extendedTextMessage?.contextInfo||content.imageMessage?.contextInfo||content.videoMessage?.contextInfo||content.documentMessage?.contextInfo||{},jid=x.participantAlt||x.participant;return jid?String(jid).split(':')[0].split('@')[0]:null}
function displayName(m){return String(m?.pushName||'').trim()}
const BUTTON_COMMANDS=new Map([['🎰 casino','/casino'],['💰 balance','/balance'],['🏆 leaderboard','/leaderboard'],['🎮 games','/games'],['🛠️ utilities','/utilities'],['❓ help','/help'],['⬅️ menu','/menu'],['🎰 slots','/slotshelp'],['🪙 coin flip','/cfhelp'],['🎲 dice','/dicehelp'],['🎡 roulette','/roulettehelp']])
function commandParts(content={}){let raw=String(content.conversation||content.extendedTextMessage?.text||'').trim();if(!raw)return null;const mapped=BUTTON_COMMANDS.get(raw.toLocaleLowerCase());if(mapped)raw=mapped;if(!raw.startsWith('/'))return null;const parts=raw.split(/\s+/);return{command:parts.shift().toLowerCase().split('@')[0],args:parts,raw}}
function ownerIds(){return new Set(String(process.env.OWNER_NUMBERS||process.env.OWNER_NUMBER||process.env.OWNER_ID||'').split(/[,;\s]+/).map(x=>x.replace(/\D/g,'')).filter(Boolean))}
function createEconomyRouter({economy,logger}){const reply=(s,j,m,t)=>s.sendMessage(j,{text:t},{quoted:m})
 return async function routeEconomy(sock,m,content){const p=commandParts(content);if(!p)return false;const supported=new Set(['/balance','/bal','/bank','/dep','/deposit','/wd','/withdraw','/donate','/transfer','/addcoin','/setbal','/setbalance']);if(!supported.has(p.command))return false;const jid=m.key.remoteJid,id=canonicalUserId(m.key),name=displayName(m);if(!id)return false
  if(['/addcoin','/setbal','/setbalance'].includes(p.command)){if(!ownerIds().has(id)){await reply(sock,jid,m,'⛔ Owner-only command.');return true}const to=quotedUserId(content)||id,amount=Number(String(p.args[0]||'').replace(/,/g,''));if(!Number.isFinite(amount)||amount<0){await reply(sock,jid,m,`Usage: reply to a user with *${p.command} [amount]*.`);return true}const u=p.command==='/addcoin'?await economy.adjustWallet(to,amount):await economy.setWallet(to,amount);await reply(sock,jid,m,`${p.command==='/addcoin'?'💰 *COINS ADDED*':'🛠️ *BALANCE SET*'}\n\nTarget: *${to}*\n👛 Wallet: *${economy.fmt(u.wallet)}*`);return true}
  if(['/balance','/bal'].includes(p.command)){const u=await economy.getBalance(id,name);await reply(sock,jid,m,`💰 *${u.displayName||'YOUR'} BALANCE*\n\n👛 Wallet (rob-able): *${economy.fmt(u.wallet)}*\n🏦 Bank (safe): *${economy.fmt(u.bank)}*\n💎 Net worth: *${economy.fmt(u.wallet+u.bank)}*`);return true}
  if(p.command==='/bank'){const u=await economy.getBalance(id,name);await reply(sock,jid,m,`🏦 *BANK*\n\n💼 Saved: *${economy.fmt(u.bank)}*\n👛 Wallet: *${economy.fmt(u.wallet)}*\n\nUse */dep [amount|all]* or */wd [amount|all]*.`);return true}
  if(['/dep','/deposit'].includes(p.command)){const r=await economy.deposit(id,p.args[0]||'all',name);await reply(sock,jid,m,r.ok?`🏦 *Deposited ${economy.fmt(r.amount)}*\n\n👛 ${economy.fmt(r.user.wallet)} • 🏦 ${economy.fmt(r.user.bank)}`:r.message);return true}
  if(['/wd','/withdraw'].includes(p.command)){const r=await economy.withdraw(id,p.args[0]||'all',name);await reply(sock,jid,m,r.ok?`💸 *Withdrew ${economy.fmt(r.amount)}*\n\n👛 ${economy.fmt(r.user.wallet)} • 🏦 ${economy.fmt(r.user.bank)}`:r.message);return true}
  const to=quotedUserId(content);if(!to){await reply(sock,jid,m,`🎯 Reply to someone's message with *${p.command} [amount]*.`);return true}const a={fromId:id,toId:to,rawAmount:p.args[0],fromName:name,toName:''},r=p.command==='/donate'?await economy.donate(a):await economy.transfer(a);await reply(sock,jid,m,r.ok?`${p.command==='/donate'?'💝':'🏦'} *${p.command==='/donate'?'Donated':'Transferred'} ${economy.fmt(r.amount)}* ✅`:r.message);logger.info({command:p.command,fromId:id,toId:to,amount:r.amount},'economy transfer');return true
 }}
module.exports={createEconomyRouter,canonicalUserId,quotedUserId,commandParts,displayName,BUTTON_COMMANDS}
