 'use strict'
const {isOwner,norm}=require('./access')
const {database}=require('./auth-store')
function canonicalUserId(key={}){const c=[key.participantAlt,key.remoteJidAlt,key.participant,key.remoteJid].filter(Boolean),jid=c.find(v=>String(v).endsWith('@s.whatsapp.net'))||c[0]||'';return String(jid).split(':')[0].split('@')[0]}
function quotedUserId(content={}){const x=content.extendedTextMessage?.contextInfo||content.imageMessage?.contextInfo||content.videoMessage?.contextInfo||content.documentMessage?.contextInfo||{},jid=x.participantAlt||x.participant;return jid?String(jid).split(':')[0].split('@')[0]:null}
function displayName(m){return String(m?.pushName||'').trim()}
const BUTTON_COMMANDS=new Map([['🎰 casino','/casino'],['💰 balance','/balance'],['🏆 leaderboard','/leaderboard'],['🎮 games','/games'],['🛠️ utilities','/utilities'],['❓ help','/help'],['⬅️ menu','/menu']])
function commandParts(content={}){let raw=String(content.conversation||content.extendedTextMessage?.text||'').trim();if(!raw)return null;const mapped=BUTTON_COMMANDS.get(raw.toLowerCase());if(mapped)raw=mapped;if(!raw.startsWith('/'))return null;const parts=raw.split(/\s+/);return{command:parts.shift().toLowerCase().split('@')[0],args:parts,raw}}
function db(){const d=database();if(!d)throw Error('DATABASE_URL is required');return d}
let ready=false
async function ensureMods(){if(ready)return;await db().query(`CREATE TABLE IF NOT EXISTS rimuru_bot_moderators(user_id TEXT PRIMARY KEY,added_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);ready=true}
async function isModerator(id){if(isOwner(id))return true;await ensureMods();return !!(await db().query('SELECT 1 FROM rimuru_bot_moderators WHERE user_id=$1',[norm(id)])).rowCount}
async function mods(){await ensureMods();return (await db().query('SELECT user_id FROM rimuru_bot_moderators ORDER BY created_at')).rows}
function createEconomyRouter({economy,logger}){const reply=(s,j,m,t)=>s.sendMessage(j,{text:t},{quoted:m});return async function(sock,m,content){const p=commandParts(content);if(!p)return false;const supported=new Set(['/balance','/bal','/bank','/dep','/deposit','/wd','/withdraw','/donate','/transfer','/addcoin','/setbal','/setbalance','/mod','/mods']);if(!supported.has(p.command))return false;const jid=m.key.remoteJid,id=canonicalUserId(m.key),name=displayName(m);if(!id)return false
 if(['/mod','/mods'].includes(p.command)){if(!isOwner(id)){await reply(sock,jid,m,'⛔ *ORIGINAL OWNER ONLY*');return true}const sub=p.command==='/mods'?'list':String(p.args[0]||'list').toLowerCase();if(sub==='list'){const r=await mods();await reply(sock,jid,m,`🛡️ *BOT MODERATORS*\n\n${r.length?r.map((x,i)=>`${i+1}. +${x.user_id}`).join('\n'):'No moderators yet.'}\n\n/mod add [number]\n/mod remove [number]`);return true}const target=norm(p.args[1]||quotedUserId(content)||'');if(!/^\d{8,15}$/.test(target)){await reply(sock,jid,m,'Use */mod add 234XXXXXXXXXX* or reply to a user with */mod add*.');return true}if(isOwner(target)){await reply(sock,jid,m,'👑 The Original Owner cannot be changed through /mod.');return true}if(sub==='add'){await ensureMods();await db().query('INSERT INTO rimuru_bot_moderators(user_id,added_by) VALUES($1,$2) ON CONFLICT(user_id) DO NOTHING',[target,id]);await reply(sock,jid,m,`🛡️ *MOD ADDED*\n\n+${target}`);return true}if(['remove','delete','del'].includes(sub)){await ensureMods();const r=await db().query('DELETE FROM rimuru_bot_moderators WHERE user_id=$1',[target]);await reply(sock,jid,m,r.rowCount?`🛡️ *MOD REMOVED*\n\n+${target}`:`ℹ️ +${target} was not a moderator.`);return true}await reply(sock,jid,m,'Use */mod add*, */mod remove*, or */mod list*.');return true}
 if(['/addcoin','/setbal','/setbalance'].includes(p.command)){if(!isOwner(id)){await reply(sock,jid,m,'⛔ Owner-only command.');return true}const to=quotedUserId(content)||id,amount=Number(String(p.args[0]||'').replace(/,/g,''));if(!Number.isFinite(amount)||amount<0){await reply(sock,jid,m,`Usage: reply to a user with *${p.command} [amount]*.`);return true}const u=p.command==='/addcoin'?await economy.adjustWallet(to,amount):await economy.setWallet(to,amount);await reply(sock,jid,m,`${p.command==='/addcoin'?'💰 *COINS ADDED*':'🛠️ *BALANCE SET*'}\n\nTarget: *${to}*\n👛 Wallet: *${economy.fmt(u.wallet)}*`);return true}
 if(['/balance','/bal'].includes(p.command)){const u=await economy.getBalance(id,name);await reply(sock,jid,m,`💰 *${u.displayName||'YOUR'} BALANCE*\n\n👛 Wallet: *${economy.fmt(u.wallet)}*\n🏦 Bank: *${economy.fmt(u.bank)}*\n💎 Net worth: *${economy.fmt(u.wallet+u.bank)}*`);return true}if(p.command==='/bank'){const u=await economy.getBalance(id,name);await reply(sock,jid,m,`🏦 *BANK*\n\n💼 ${economy.fmt(u.bank)}\n👛 ${economy.fmt(u.wallet)}`);return true}if(['/dep','/deposit'].includes(p.command)){const r=await economy.deposit(id,p.args[0]||'all',name);await reply(sock,jid,m,r.ok?`🏦 Deposited *${economy.fmt(r.amount)}*`:r.message);return true}if(['/wd','/withdraw'].includes(p.command)){const r=await economy.withdraw(id,p.args[0]||'all',name);await reply(sock,jid,m,r.ok?`💸 Withdrew *${economy.fmt(r.amount)}*`:r.message);return true}const to=quotedUserId(content);if(!to){await reply(sock,jid,m,`🎯 Reply to someone with *${p.command} [amount]*.`);return true}const a={fromId:id,toId:to,rawAmount:p.args[0],fromName:name,toName:''},r=p.command==='/donate'?await economy.donate(a):await economy.transfer(a);await reply(sock,jid,m,r.ok?`✅ ${economy.fmt(r.amount)} sent.`:r.message);return true}}
module.exports={createEconomyRouter,canonicalUserId,quotedUserId,commandParts,displayName,BUTTON_COMMANDS,isModerator}
