'use strict'
const {MASTERS:MASTER_LIST}=require('./rpg-store')
const PREFIX=['menu_','casino_','start_','rpg_','mines_']
const IDS=new Set(['ryuden_enter','mines_a1','mines_b2','mines_cashout'])
function clean(t){return String(t||'').replace(/[\u200b-\u200f\u2060\ufeff\ufe0f]/g,'').trim().replace(/\s+/g,' ').toLowerCase()}
const MAP=new Map([['🎰 casino','menu_casino'],['💰 balance','menu_balance'],['🏆 leaderboard','menu_leaderboard'],['🎮 games','menu_games'],['🛠️ utilities','menu_utilities'],['❓ help','menu_help'],['⬅️ menu','menu_main'],['🎰 slots','casino_slots_help'],['🪙 coin flip','casino_cf_help'],['🎲 dice','casino_dice_help'],['🎡 roulette','casino_roulette_help'],['⚔️ enter odyssey','start_rpg'],['🎰 enter casino','start_casino'],['📜 main menu','menu_main'],['🗺️ explore','rpg_explore'],['🗺️ explore again','rpg_explore'],['🗺️ continue','rpg_explore'],['➡️ continue','rpg_explore'],['🧙 master','rpg_master'],['🎒 inventory','rpg_inventory'],['🏰 guild','rpg_guild'],['📖 odyssey','rpg_story'],['🎁 daily','rpg_daily'],['⚔️ rpg home','rpg_home'],['💬 talk to master','rpg_talk_master'],['🗺️ begin odyssey','rpg_explore'],['🗺️ try again','rpg_explore'],['🔎 explore more masters','rpg_masters_page_1'],['⭐ featured','rpg_master']].map(x=>[clean(x[0]),x[1]]))
const MASTERS=new Map(MASTER_LIST.map(x=>[clean(x.name),x.key]))
function visibleText(c={}){return String(c.conversation||c.extendedTextMessage?.text||c.buttonsResponseMessage?.selectedDisplayText||c.templateButtonReplyMessage?.selectedDisplayText||c.listResponseMessage?.title||'').trim()}
function native(c={}){const x=c.interactiveResponseMessage?.nativeFlowResponseMessage?.paramsJson;if(!x)return{id:'',text:''};try{const v=JSON.parse(x);return{id:String(v.id||v.button_id||v.selected_id||''),text:String(v.display_text||v.title||v.text||'')}}catch{return{id:'',text:''}}}
function valid(x){return typeof x==='string'&&(IDS.has(x)||PREFIX.some(p=>x.startsWith(p)))}
function resolveButtonId(c={}){const n=native(c);for(const x of[n.id,c.buttonsResponseMessage?.selectedButtonId,c.templateButtonReplyMessage?.selectedId,c.listResponseMessage?.singleSelectReply?.selectedRowId])if(valid(x))return x;for(const t of[visibleText(c),n.text,c.interactiveResponseMessage?.body?.text]){const z=clean(t);if(MAP.has(z))return MAP.get(z);if(MASTERS.has(z))return `rpg_master_${MASTERS.get(z)}`}return null}
function isKnownButtonInteraction(c={}){return !!resolveButtonId(c)}
const CMDS=new Set(['/start','/menu','/help','/p','/profile','/balance','/bal','/bank','/leaderboard','/lb','/casino','/games','/utilities','/dep','/deposit','/wd','/withdraw','/donate','/transfer','/addcoin','/setbal','/setbalance','/slots','/cf','/coinflip','/dice','/roulette','/ping','/test','/dbping','/image','/api','/mines','/rpg','/masters','/master','/daily','/explore','/inventory','/rlb','/rpgleaderboard','/guild','/ai','/talk','/endtalk'])
function isReplyTrigger(c={}){return isKnownButtonInteraction(c)||CMDS.has(visibleText(c).toLowerCase().split(/\s+/)[0].split('@')[0])}
function shouldHandleUpsert(c={},o={}){const b=isKnownButtonInteraction(c);if(o.fromMe&&!b)return false;if(o.type==='append'&&!b)return false;return o.type==='notify'||o.type==='append'}
class ReplyRateLimiter{constructor(){this.users=new Map();this.maxReplies=3;this.windowMs=5000;this.minMuteMs=5000;this.maxMuteMs=10000}key(m){const k=m?.key||{};return String(k.participantAlt||k.participant||k.remoteJidAlt||k.remoteJid||'unknown').split(':')[0].split('@')[0]}check(m){const now=Date.now(),k=this.key(m);let s=this.users.get(k)||{times:[],mutedUntil:0};if(s.mutedUntil>now)return{allowed:false,warn:false,remainingMs:s.mutedUntil-now};if(s.mutedUntil)s={times:[],mutedUntil:0};s.times=s.times.filter(t=>now-t<=this.windowMs);if(s.times.length>=this.maxReplies){const d=this.minMuteMs+Math.floor(Math.random()*(this.maxMuteMs-this.minMuteMs+1));s.mutedUntil=now+d;this.users.set(k,s);return{allowed:false,warn:true,durationMs:d}}s.times.push(now);this.users.set(k,s);return{allowed:true}}}
module.exports={resolveButtonId,isKnownButtonInteraction,isReplyTrigger,shouldHandleUpsert,visibleText,ReplyRateLimiter}
