'use strict'
const {database}=require('./auth-store'),{displayName}=require('./economy-router'),story=require('./odyssey-story')
const ENEMIES=[{key:'wraith',name:'Wandering Wraith',hp:100,atk:13,def:5,xp:42,gold:24,gems:0},{key:'golem',name:'Corrupted Golem',hp:125,atk:16,def:9,xp:60,gold:36,gems:0},{key:'stalker',name:'Void Stalker',hp:110,atk:19,def:7,xp:72,gold:46,gems:1},{key:'hound',name:'Rift Hound',hp:90,atk:14,def:5,xp:36,gold:22,gems:0}]
const BOSSES={5:{key:'hollow',name:'The Hollow Sovereign',hp:280,atk:23,def:12,xp:288,gold:204,gems:10,boss:true},10:{key:'chrono',name:'Chronophage, Eater of Time',hp:330,atk:25,def:15,xp:348,gold:252,gems:12,boss:true},15:{key:'echo_crown',name:'The Crown Beyond Time',hp:390,atk:28,def:17,xp:504,gold:360,gems:18,boss:true}}
function db(){const d=database();if(!d)throw Error('DATABASE_URL is required');return d}
function id(m){const k=m.key||{},c=[k.participantAlt,k.remoteJidAlt,k.participant,k.remoteJid].filter(Boolean),j=c.find(v=>String(v).endsWith('@s.whatsapp.net'))||c[0]||'';return String(j).split(':')[0].split('@')[0]}
async function player(uid){return(await db().query('SELECT * FROM rimuru_rpg_players WHERE user_id=$1',[uid])).rows[0]}
async function setBattle(uid,b){await db().query('UPDATE rimuru_rpg_players SET active_battle=$2::jsonb,updated_at=NOW() WHERE user_id=$1',[uid,b?JSON.stringify(b):null])}
async function setStory(uid,st,chapter){await db().query('UPDATE rimuru_rpg_players SET story_state=$2::jsonb,story_chapter=COALESCE($3,story_chapter),updated_at=NOW() WHERE user_id=$1',[uid,JSON.stringify(st||{}),chapter??null])}
function masterLine(p,event,enemy){
 const m=p?.current_master||'Your Master',bond=Number(p?.bond_points||0)
 const lines=event==='win'?[`🧙 *${m}:* Good. Don't get careless now.`,`🧙 *${m}:* That's the result I expected. Keep moving.`,`🧙 *${m}:* ${enemy} is down. Remember what worked.`]:[`🧙 *${m}:* Losing once isn't the end. Learn from it.`,`🧙 *${m}:* Get up. We're fixing that mistake next time.`,`🧙 *${m}:* You survived. That's enough to improve from.`]
 return lines[(bond+String(enemy||'').length)%lines.length]
}
function createRpgUpgrade({base,sendButtons}){const send=(s,j,m,t)=>s.sendMessage(j,{text:t},{quoted:m}),btn=(s,j,m,b,f,d)=>sendButtons(s,j,b,f,d,id(m)),who=m=>({id:id(m),name:displayName(m),jid:m.key.remoteJid})
 async function missions(s,m){const u=who(m),p=await player(u.id),st=p?.story_state||{},q=st.quest;return btn(s,u.jid,m,`📜 *MISSION LOG*\n\n📖 Main: *Odyssey I — ${story.chapter((p?.story_chapter||0)+1).title}*\n📍 ${story.chapter((p?.story_chapter||0)+1).location}\n\n${q&&['offered','accepted','active'].includes(q.status)?`🧭 Active side mission: *${q.key==='lost_scout'?'The Missing Scout':q.key}*\nStatus: *${q.status}*`:'🧭 No active side mission.'}`,'RYUDEN • MISSIONS',[['📖 Story','rpg_story'],['⚔️ RPG Home','rpg_home']])}
 async function storyPanel(s,m){const u=who(m),p=await player(u.id),n=Math.min(15,(p?.story_chapter||0)+1),ch=story.chapter(n);return btn(s,u.jid,m,`📖 *ODYSSEY I — THE THIRTEENTH ECHO*\n\n*Part ${n}/15 — ${ch.title}*\n📍 ${ch.location}\n\n${ch.summary}`,'RYUDEN • STORY',[['▶️ Continue Story','rpg_story_continue'],['📜 Missions','rpg_missions'],['⚔️ RPG Home','rpg_home']])}
 async function storyContinue(s,m){const u=who(m),p=await player(u.id),n=Math.min(15,(p?.story_chapter||0)+1),ch=story.chapter(n);if(BOSSES[n])return startBattle(s,m,BOSSES[n],n);if(n>=15)return storyPanel(s,m);await setStory(u.id,{...(p?.story_state||{}),npc:null,location:story.chapter(n+1).location,summary:`Part ${n} completed: ${ch.title}.`,flags:{...(p?.story_state?.flags||{}),[`chapter_${n}_complete`]:true}},n);return storyPanel(s,m)}
 async function startBattle(s,m,e=null,storyBoss=0){const u=who(m),p=await player(u.id);if(!p?.current_master)return base.section(s,m,'rpg_master');const enemy=e||ENEMIES[Math.floor(Math.random()*ENEMIES.length)],b={enemy,enemyHp:enemy.hp,playerHp:p.hp,energy:100,guard:0,turn:1,storyBoss,masterAssistUsed:false};await setBattle(u.id,b);return battlePanel(s,m,b,'The fight begins.')}
 async function battlePanel(s,m,b,result=''){const u=who(m),p=await player(u.id);return btn(s,u.jid,m,`⚔️ *BATTLE • TURN ${b.turn}*\n\n${result?`${result}\n\n`:''}👹 *${b.enemy.name}* — ❤️ ${Math.max(0,b.enemyHp)}/${b.enemy.hp}\n👤 *${p.username||u.name||'Player'}* — ❤️ ${Math.max(0,b.playerHp)}/${p.hp} • ⚡ ${b.energy}/100`,'RYUDEN • COMBAT',[['⚔️ Attack','rpg_battle_attack'],['🛡️ Guard','rpg_battle_guard'],['✨ Skill','rpg_battle_skill'],['🎒 Item','rpg_battle_item'],['🌌 Ultimate','rpg_battle_ultimate'],['🏃 Retreat','rpg_battle_retreat']])}
 function hitDamage(p,b,mult=1,bonus=0){const floor=Math.max(16,Math.round(b.enemy.hp*(b.enemy.boss?.09:.18))),raw=Math.round((18+p.atk*1.05+Math.random()*8-b.enemy.def*.45+bonus)*mult);return Math.max(floor,raw)}
 async function finish(s,m,p,b,won){const u=who(m);await setBattle(u.id,null);if(won){let chapter=p.story_chapter||0;if(b.storyBoss){chapter=Math.max(chapter,b.storyBoss);await setStory(u.id,{...(p.story_state||{}),npc:null,summary:`You defeated ${b.enemy.name}.`,flags:{...(p.story_state?.flags||{}),[`chapter_${b.storyBoss}_boss_defeated`]:true}},chapter)}await db().query('UPDATE rimuru_rpg_players SET xp=xp+$2,gold=gold+$3,gems=gems+$4,win_count=win_count+1,updated_at=NOW() WHERE user_id=$1',[u.id,b.enemy.xp,b.enemy.gold,b.enemy.gems||0]);return btn(s,u.jid,m,`🏆 *VICTORY*\n\n${b.enemy.name} falls.\n✨ +${b.enemy.xp} XP • 🪙 +${b.enemy.gold}${b.enemy.gems?` • 💎 +${b.enemy.gems}`:''}\n\n${masterLine(p,'win',b.enemy.name)}`,'RYUDEN • BATTLE',b.storyBoss?[['📖 Continue Story','rpg_story'],['⚔️ RPG Home','rpg_home']]:[['🗺️ Continue','rpg_explore'],['⚔️ RPG Home','rpg_home']])}const loss=Math.max(1,Math.floor(Number(p.gold||0)*.1));await db().query('UPDATE rimuru_rpg_players SET gold=GREATEST(0,gold-$2),loss_count=loss_count+1,updated_at=NOW() WHERE user_id=$1',[u.id,loss]);return btn(s,u.jid,m,`💀 *DEFEAT*\n\n${b.enemy.name} overwhelms you.\n🪙 Lost *${loss} Gold*.\n\n${masterLine(p,'loss',b.enemy.name)}`,'RYUDEN • BATTLE',[['⚔️ RPG Home','rpg_home']])}
 async function action(s,m,a,key){const u=who(m),p=await player(u.id),b=p?.active_battle;if(!b)return startBattle(s,m);if(a==='retreat'){await setBattle(u.id,null);return btn(s,u.jid,m,'🏃 *RETREATED*','RYUDEN • COMBAT',[['⚔️ RPG Home','rpg_home']])}const techs=p.techniques||[],inv=p.inventory||[];if(a==='skill')return btn(s,u.jid,m,'✨ *CHOOSE TECHNIQUE*','RYUDEN • COMBAT',[...techs.slice(0,8).map(x=>[x.name,`rpg_battle_cast_${x.key}`]),['↩️ Battle','rpg_combat']]);if(a==='item')return btn(s,u.jid,m,'🎒 *CHOOSE ITEM*','RYUDEN • COMBAT',[...inv.filter(x=>x.heal||x.guard).slice(0,8).map(x=>[x.name,`rpg_battle_use_${x.key}`]),['↩️ Battle','rpg_combat']]);let dealt=0,label='';if(a==='attack'){dealt=hitDamage(p,b);label=`⚔️ You hit for *${dealt}*.`}else if(a==='guard'){b.guard=.65;label='🛡️ You brace for the counterattack.'}else if(a==='cast'){const t=techs.find(x=>x.key===key);if(!t)return battlePanel(s,m,b);if(b.energy<(t.cost||0))return send(s,u.jid,m,'⚡ Not enough energy.');b.energy-=t.cost||0;dealt=hitDamage(p,b,1.25,(t.damage||20)*.35);label=`✨ *${t.name}* dealt *${dealt}*.`}else if(a==='ultimate'){const t=techs.find(x=>x.ultimate);if(!t)return send(s,u.jid,m,'🌌 Your Master has not taught you an Ultimate yet.');if(b.energy<(t.cost||60))return send(s,u.jid,m,'⚡ Not enough energy.');b.energy-=t.cost||60;dealt=hitDamage(p,b,2,(t.damage||80)*.4);label=`🌌 *${t.name}* crashed in for *${dealt}*.`}else if(a==='use'){const ix=inv.findIndex(x=>x.key===key);if(ix<0)return battlePanel(s,m,b);const it=inv[ix];inv.splice(ix,1);await db().query('UPDATE rimuru_rpg_players SET inventory=$2::jsonb WHERE user_id=$1',[u.id,JSON.stringify(inv)]);if(it.heal)b.playerHp=Math.min(p.hp,b.playerHp+it.heal);if(it.guard)b.guard=Math.max(b.guard||0,it.guard);label=`🎒 Used *${it.name}*.`}
 b.enemyHp-=dealt
 // Deterministic Master assist: one possible assist per battle, chance scales with Bond; engine owns damage.
 if(!b.masterAssistUsed&&b.enemyHp>0&&p.current_master&&Math.random()<Math.min(.30,.05+Number(p.bond_points||0)/500)){const assist=Math.max(8,Math.round(hitDamage(p,b,.45)));b.enemyHp-=assist;b.masterAssistUsed=true;label+=`\n🧙 *${p.current_master} assisted!* +${assist} damage.`}
 if(b.enemyHp<=0)return finish(s,m,p,b,true)
 let enemy=Math.max(6,Math.round(b.enemy.atk+Math.random()*6-p.def*.35));if(b.guard){enemy=Math.max(1,Math.round(enemy*(1-b.guard)));b.guard=0}b.playerHp-=enemy;if(b.playerHp<=0)return finish(s,m,p,b,false);b.turn++;b.energy=Math.min(100,b.energy+12);await setBattle(u.id,b);return battlePanel(s,m,b,`${label}\n👹 ${b.enemy.name} countered for *${enemy}*.`)}
 async function section(s,m,x){if(x==='rpg_missions')return missions(s,m);if(x==='rpg_story')return storyPanel(s,m);if(x==='rpg_story_continue')return storyContinue(s,m);if(x==='rpg_combat'){const p=await player(id(m));return p?.active_battle?battlePanel(s,m,p.active_battle):startBattle(s,m)}if(x.startsWith('rpg_battle_cast_'))return action(s,m,'cast',x.slice(16));if(x.startsWith('rpg_battle_use_'))return action(s,m,'use',x.slice(15));if(x.startsWith('rpg_battle_'))return action(s,m,x.slice(11));return false}
 async function route(s,m,c){if(['/missions','/mission'].includes(c.command))return missions(s,m),true;if(c.command==='/story')return storyPanel(s,m),true;if(['/combat','/fight'].includes(c.command))return section(s,m,'rpg_combat'),true;return false}
 return{route,section,missions,storyPanel}
}
module.exports={createRpgUpgrade}
