'use strict'
const store=require('./rpg-store')
const {canonicalUserId,displayName}=require('./economy-router')
const ENEMIES=[
 {name:'Wandering Wraith',hp:60,atk:10,def:4,xp:30,gold:15,gems:0},
 {name:'Corrupted Golem',hp:90,atk:14,def:10,xp:45,gold:25,gems:0},
 {name:'Void Stalker',hp:75,atk:18,def:6,xp:50,gold:30,gems:1},
 {name:'Rift Hound',hp:55,atk:12,def:5,xp:25,gold:12,gems:0}
]
const BOSSES=[{name:'The Hollow Sovereign',hp:260,atk:26,def:14,xp:220,gold:150,gems:8},{name:'Chronophage, Eater of Time',hp:300,atk:24,def:18,xp:260,gold:180,gems:10}]
const STORY=["You find a torn page of a forgotten Odyssey. It hints at a monarch who once refused the System's judgment.","The sky fractures for a moment, revealing a world that never chose a Master.","You hear whispers in a language your Master refuses to translate."]
const RARITIES=['Common','Common','Common','Uncommon','Uncommon','Rare','Epic','Legendary','Mythic','Ascended']
function item(){const kinds=['weapon','armor','accessory'],names=['Fractured Blade','System Dagger','Void-Touched Spear','Shadow-Woven Cloak','Rift Compass','System Core Fragment'];return{name:names[Math.floor(Math.random()*names.length)],rarity:RARITIES[Math.floor(Math.random()*RARITIES.length)],kind:kinds[Math.floor(Math.random()*kinds.length)]}}
function createRpg({economy,logger}){
 const send=(s,j,m,t)=>s.sendMessage(j,{text:t},{quoted:m})
 async function isAdmin(sock,jid,userId){if(!jid.endsWith('@g.us'))return false;const meta=await sock.groupMetadata(jid),p=meta.participants.find(x=>String(x.id||x.phoneNumber||'').split(':')[0].split('@')[0]===userId||String(x.lid||'').split(':')[0].split('@')[0]===userId);return !!p?.admin}
 async function adminIds(sock,jid){const meta=await sock.groupMetadata(jid);return meta.participants.filter(p=>p.admin).map(p=>String(p.id||p.phoneNumber||p.lid||'').split(':')[0].split('@')[0])}
 async function route(sock,m,c){
  const id=canonicalUserId(m.key),name=displayName(m),jid=m.key.remoteJid,args=c.args||[]
  if(c.command==='/rpg'){const p=await store.ensurePlayer(id,name),g=await store.guildForPlayer(id);await send(sock,jid,m,`⚔️ *RYUDEN ODYSSEY*\\n\\n> 👤 *${p.username||name||'Player'}*\\n🎖️ Rank: *${p.rank}* • Lv. *${p.level}*\\n✨ XP: *${p.xp}/${store.xpNeed(p.level)}*\\n💥 Power: *${p.powerScore}*\\n\\n❤️ HP ${p.hp} • ⚔️ ATK ${p.atk} • 🛡️ DEF ${p.def}\\n💨 SPD ${p.spd} • 🍀 LUCK ${p.luck} • 🎯 CRIT ${p.crit}%\\n\\n🧙 Master: *${p.currentMaster||'None'}*\\n🏰 Guild: *${g?.name||'None'}*\\n🪙 Gold: *${economy.fmt(p.gold)}* • 💎 Gems: *${p.gems}*\\n📖 Odyssey: *Part ${p.storyChapter+1}/15*\\n\\nUse */masters*, */explore*, */daily*, */guild*.`);return true}
  if(c.command==='/masters'){const list=store.MASTERS.map(x=>`• *${x.name}* — ${x.universe}\\n  /master ${x.key}`).join('\\n');await send(sock,jid,m,`🧙 *ODYSSEY MASTERS*\\n\\n${list}\\n\\n> Your Master shapes your Odyssey universe.`);return true}
  if(c.command==='/master'){const p=await store.ensurePlayer(id,name);if(p.currentMaster){await send(sock,jid,m,`🧙 Your current Master is *${p.currentMaster}*. Master switching unlocks after completing an Odyssey.`);return true}const r=await store.setMaster(id,args[0]);if(!r){await send(sock,jid,m,'❌ Unknown Master. Use */masters*.');return true}await send(sock,jid,m,`🧙 *MASTER SELECTED*\\n\\n> ${r.master.name} — ${r.master.universe}\\n\\nPassive: *${r.master.passive}*\\nSkill: *${r.master.skill}*\\nUltimate: *${r.master.ultimate}*\\n\\nYour Odyssey has begun.`);return true}
  if(c.command==='/daily'){const r=await store.daily(id);if(!r.ok){await send(sock,jid,m,`⏳ Daily already claimed. Try again in about *${Math.ceil(r.remaining/3600000)}h*.`);return true}await send(sock,jid,m,`🎁 *DAILY REWARD*\\n\\n🪙 +${r.gold} RPG Gold${r.gems?`\\n💎 +${r.gems} Gem`:''}`);return true}
  if(c.command==='/explore'){const p=await store.ensurePlayer(id,name);if(!p.currentMaster){await send(sock,jid,m,'🧙 Choose a Master first with */masters*.');return true}const roll=Math.random();if(roll<.22){const gold=20+Math.floor(Math.random()*61),it=Math.random()<.35?item():null,n=await store.addProgress(id,{xp:20,gold,item:it});await send(sock,jid,m,`🗺️ *TREASURE ENCOUNTER*\\n\\nYou uncover a sealed System cache.\\n\\n✨ +20 XP\\n🪙 +${gold} Gold${it?`\\n🎒 ${it.rarity} ${it.name}`:''}\\n\\nLv.${n.level} • Rank ${n.rank}`);return true}if(roll<.42){await send(sock,jid,m,`📖 *ODYSSEY ECHO*\\n\\n${STORY[Math.floor(Math.random()*STORY.length)]}`);return true}const boss=roll>.92,e=(boss?BOSSES:ENEMIES)[Math.floor(Math.random()*(boss?BOSSES:ENEMIES).length)],playerHit=Math.max(1,p.atk+Math.floor(Math.random()*12)-e.def),enemyHit=Math.max(1,e.atk+Math.floor(Math.random()*8)-p.def),turns=Math.ceil(e.hp/playerHit),damage=enemyHit*Math.max(0,turns-1),won=damage<p.hp;if(won){const drop=Math.random()<(boss?.7:.18)?item():null,n=await store.addProgress(id,{xp:e.xp,gold:e.gold,gems:e.gems,item:drop,win:1});await send(sock,jid,m,`${boss?'👑 *BOSS DEFEATED*':'⚔️ *VICTORY*'}\\n\\n> ${e.name}\\n\\n💥 You dealt ~${playerHit}/turn.\\n❤️ Damage taken: ${damage}\\n✨ +${e.xp} XP\\n🪙 +${e.gold} Gold${e.gems?`\\n💎 +${e.gems} Gems`:''}${drop?`\\n🎒 ${drop.rarity} ${drop.name}`:''}\\n\\n🎖️ ${n.rank} • Lv.${n.level}`)}else{const loss=Math.max(1,Math.floor(p.gold*.1));await store.addProgress(id,{gold:-loss,loss:1});await send(sock,jid,m,`💀 *DEFEAT*\\n\\n> ${e.name}\\n\\nThe System pulls you back to Ryuden before death claims you.\\n🪙 Lost *${loss}* RPG Gold.`)}return true}
  if(c.command==='/inventory'){const p=await store.ensurePlayer(id,name),x=p.inventory.length?p.inventory.map((v,i)=>`${i+1}. *${v.rarity}* ${v.name} — ${v.kind}`).join('\\n'):'Your inventory is empty.';await send(sock,jid,m,`🎒 *RPG INVENTORY*\\n\\n${x}`);return true}
  if(['/rlb','/rpgleaderboard'].includes(c.command)){const rows=await store.leaderboard(10);await send(sock,jid,m,`🏆 *ODYSSEY POWER RANKING*\\n\\n${rows.map((p,i)=>`${i+1}. *${p.username||'Player'}* — ${p.rank} Lv.${p.level}\\n   💥 ${p.powerScore}`).join('\\n\\n')||'No adventurers yet.'}`);return true}
  if(c.command==='/guild'){
   const sub=String(args[0]||'info').toLowerCase()
   if(sub==='create'){if(!jid.endsWith('@g.us')){await send(sock,jid,m,'🏰 Guilds can only be created from WhatsApp groups.');return true}if(!(await isAdmin(sock,jid,id))){await send(sock,jid,m,'🛡️ Only a *group admin* can propose a guild.');return true}const gname=args.slice(1).join(' ').trim();if(gname.length<3||gname.length>32){await send(sock,jid,m,'Use */guild create [name]* — 3 to 32 characters.');return true}await store.ensurePlayer(id,name);const ids=await adminIds(sock,jid),r=await store.createProposal(jid,gname,id,ids);if(!r.ok){await send(sock,jid,m,`❌ ${r.message}`);return true}if(r.created){await send(sock,jid,m,`🏰 *GUILD CREATED*\\n\\n*${r.guild.name}* now represents this group.\\nThere were no other admins to vote.`);return true}await send(sock,jid,m,`🗳️ *GUILD PROPOSAL*\\n\\n> 🏰 *${gname}*\\nProposed by: *${name||'Group Admin'}*\\n\\nGroup admins must approve it.\\nVotes: *1/${r.needed}* required\\n\\nAdmins: use */guild accept*.\\n⏳ Proposal expires in 24 hours.`);return true}
   if(sub==='accept'){if(!jid.endsWith('@g.us')||!(await isAdmin(sock,jid,id))){await send(sock,jid,m,'🛡️ Only group admins can vote.');return true}const r=await store.voteProposal(jid,id);if(!r.ok){await send(sock,jid,m,`❌ ${r.message}`);return true}await send(sock,jid,m,r.created?`🏰 *GUILD APPROVED!*\\n\\n*${r.guild.name}* has been founded.\\nFinal vote: *${r.votes}/${r.needed}*.`:`🗳️ Vote accepted for *${r.name}*.\\nVotes: *${r.votes}/${r.needed}*.`);return true}
   if(sub==='join'){if(!jid.endsWith('@g.us')){await send(sock,jid,m,'Use */guild join* inside the guild’s WhatsApp group.');return true}const g=await store.joinGroupGuild(jid,id);await send(sock,jid,m,g?`🏰 You joined *${g.name}*.`:'❌ This WhatsApp group does not have an approved guild.');return true}
   const g=jid.endsWith('@g.us')?await store.guildForGroup(jid):await store.guildForPlayer(id);await send(sock,jid,m,g?`🏰 *${g.name}*\\n\\nLevel: *${g.level}*\\nXP: *${economy.fmt(g.xp)}*\\nTreasury: *${economy.fmt(g.treasury)}*\\nMembers: *${g.member_count}*\\n\\n/group join — join this group's guild`:'🏰 No guild found.\\n\\nGroup admins can propose one with */guild create [name]*.');return true
  }
  return false
 }
 return {route}
}
module.exports={createRpg}
