'use strict'
const store=require('./rpg-store')
const {canonicalUserId,displayName}=require('./economy-router')
const ENEMIES=[{key:'wraith',name:'Wandering Wraith',hp:70,atk:12,def:4,xp:35,gold:20,gems:0},{key:'golem',name:'Corrupted Golem',hp:110,atk:15,def:9,xp:50,gold:30,gems:0},{key:'stalker',name:'Void Stalker',hp:90,atk:19,def:6,xp:60,gold:38,gems:1},{key:'hound',name:'Rift Hound',hp:65,atk:13,def:5,xp:30,gold:18,gems:0}]
const BOSSES=[{key:'hollow',name:'The Hollow Sovereign',hp:300,atk:27,def:14,xp:240,gold:170,gems:8},{key:'chrono',name:'Chronophage, Eater of Time',hp:360,atk:25,def:18,xp:290,gold:210,gems:10}]
const FEATURED=store.MASTERS.slice(0,10),ARCHIVE=store.MASTERS.slice(10),MASTER_KEYS=new Set(store.MASTERS.map(x=>x.key)),PAGE_SIZE=10
const SHOP=[
 {key:'potion',name:'Recovery Potion',type:'item',price:45,currency:'gold',desc:'Restore 45 HP during battle.',heal:45},
 {key:'barrier',name:'Barrier Capsule',type:'item',price:90,currency:'gold',desc:'Reduce the next enemy hit by 60%.',guard:.6},
 {key:'hi_potion',name:'Hi-Potion',type:'item',price:2,currency:'gems',desc:'Restore 110 HP during battle.',heal:110},
 {key:'rift_slash',name:'Rift Slash',type:'technique',price:180,currency:'gold',desc:'Original System technique. Reliable heavy strike.',damage:34,cost:18,cooldown:1},
 {key:'aegis_pulse',name:'Aegis Pulse',type:'technique',price:3,currency:'gems',desc:'Original System technique. Damage + temporary armor.',damage:20,armor:18,cost:22,cooldown:2},
 {key:'nova_break',name:'Nova Break',type:'technique',price:7,currency:'gems',desc:'Rare original burst technique.',damage:58,cost:34,cooldown:3}
]
const NPCS={kael:{name:'Kael',role:'injured Rift Scout',personality:'Wary, practical, brave, dry sense of humor. He distrusts the System but cares about civilians.',scene:'The shattered East Gate of Ryuden, beneath a violet rift.',knowledge:'A masked faction called the Pale Choir has been collecting Rift Cores. He saw them take a wounded scout toward the old transit tunnels. He does not know their leader.'},nyra:{name:'Nyra',role:'Ryuden Archivist',personality:'Curious, sharp, slightly impatient, obsessed with impossible records.',scene:'The sealed lower archive beneath Ryuden.',knowledge:'Old records mention a Monarch who rejected the System and a recurring phenomenon called the Thirteenth Echo. She suspects the current rifts are deliberate.'}}
function createRpg({economy,logger,sendButtons}){
 const send=(s,j,m,t)=>s.sendMessage(j,{text:t},{quoted:m}),buttons=(s,j,m,b,f,d)=>sendButtons?sendButtons(s,j,b,f,d,canonicalUserId(m.key)):send(s,j,m,b)
 const who=m=>({id:canonicalUserId(m.key),name:displayName(m),jid:m.key.remoteJid})
 function fmtMs(ms){const min=Math.ceil(ms/60000);return min<=1?'less than a minute':`${min} min`}
 async function panel(s,m){const u=who(m),p=await store.ensurePlayer(u.id,u.name),g=await store.guildForPlayer(u.id);return buttons(s,u.jid,m,['⚔️ *RYUDEN ODYSSEY*','',`> 👤 *${p.username||u.name||'Player'}*`,`🎖️ *${p.rank} • Lv. ${p.level}*   ✨ ${p.xp}/${store.xpNeed(p.level)} XP`,`💥 Power *${p.powerScore}*`,'',`❤️ ${p.hp}   ⚔️ ${p.atk}   🛡️ ${p.def}   💨 ${p.spd}`,`🧙 ${p.currentMaster||'No Master'} • ❤️ Bond ${p.bondPoints}`,`🏰 ${g?.name||'No Guild'} • 🪙 ${economy.fmt(p.gold)} • 💎 ${p.gems}`,`📖 Odyssey • Part ${p.storyChapter+1}/15`].join('\n'),'RYUDEN • ODYSSEY',[['🗺️ Explore','rpg_explore'],['🧙 Master','rpg_master'],['⚔️ Combat','rpg_combat'],['🛒 Shop','rpg_shop'],['🎒 Inventory','rpg_inventory'],['📖 Story','rpg_story'],['🏰 Guild','rpg_guild'],['🎁 Daily','rpg_daily'],['⬅️ Menu','menu_main']])}
 async function masterPanel(s,m){const u=who(m),p=await store.ensurePlayer(u.id,u.name);if(p.currentMaster)return buttons(s,u.jid,m,`🧙 *YOUR MASTER*\n\n> *${p.currentMaster}*\n❤️ Bond: *${p.bondPoints}*\n\nTalk, train and earn enough trust for your Master to teach techniques from their own style.`,'RYUDEN • MASTER',[['💬 Talk','rpg_talk_master'],['🥋 Train','rpg_train'],['📚 Techniques','rpg_techniques'],['❤️ Bond','rpg_bond'],['⚔️ RPG Home','rpg_home']]);return buttons(s,u.jid,m,'🧙 *CHOOSE YOUR MASTER*\n\nFeatured Masters appear first. Your Master changes your abilities, conversations and some story moments.','RYUDEN • DESTINY',[...FEATURED.map(x=>[x.name,`rpg_master_${x.key}`]),['🔎 Explore More Masters','rpg_masters_page_1']])}
 async function archivePanel(s,m,page=1){const u=who(m),p=await store.ensurePlayer(u.id,u.name);if(p.currentMaster)return masterPanel(s,m);const pages=Math.ceil(ARCHIVE.length/PAGE_SIZE),n=Math.max(1,Math.min(pages,+page||1)),list=ARCHIVE.slice((n-1)*PAGE_SIZE,n*PAGE_SIZE),defs=list.map(x=>[x.name,`rpg_master_${x.key}`]);if(n>1)defs.push(['◀️ Previous',`rpg_masters_page_${n-1}`]);if(n<pages)defs.push(['Next ▶️',`rpg_masters_page_${n+1}`]);defs.push(['⭐ Featured','rpg_master']);return buttons(s,u.jid,m,`🔎 *MASTER ARCHIVE • ${n}/${pages}*\n\n${list.map(x=>`• *${x.name}* — ${x.universe}`).join('\n')}`,'RYUDEN • 60 MASTERS',defs)}
 async function chooseMaster(s,m,key){if(!MASTER_KEYS.has(key))return false;const u=who(m),p=await store.ensurePlayer(u.id,u.name);if(p.currentMaster)return masterPanel(s,m);const r=await store.setMaster(u.id,key);await store.addTechnique(u.id,{key:`master_${key}_basic`,name:r.master.skill,source:r.master.name,level:1,damage:30,cost:18,cooldown:1,master:true});return buttons(s,u.jid,m,`🧙 *DESTINY ACCEPTED*\n\n> *${r.master.name}* — ${r.master.universe}\n\n🌀 ${r.master.passive}\n⚔️ ${r.master.skill}\n🌌 ${r.master.ultimate}\n\nYour first Master technique has been registered.`,'RYUDEN • MASTER',[['🥋 Train','rpg_train'],['🗺️ Begin Odyssey','rpg_explore'],['⚔️ RPG Home','rpg_home']])}
 async function train(s,m){const u=who(m),p=await store.ensurePlayer(u.id,u.name);if(!p.currentMaster)return masterPanel(s,m);const cost=75+Math.floor(p.level/5)*25,r=await store.train(u.id,cost);if(!r.ok)return buttons(s,u.jid,m,r.reason==='cooldown'?`⏳ *TRAINING RECOVERY*\n\n${p.currentMaster} won't train again for *${fmtMs(r.remaining)}*.`:`🪙 *NOT ENOUGH RPG GOLD*\n\nTraining costs *${cost} Gold*.`,'RYUDEN • TRAINING',[['⚔️ RPG Home','rpg_home']]);let taught='';const master=store.MASTERS.find(x=>x.name===p.currentMaster),n=r.player;if(master&&n.bondPoints>=60&&!(n.techniques||[]).some(x=>x.key===`master_${master.key}_ultimate`)){await store.addTechnique(u.id,{key:`master_${master.key}_ultimate`,name:master.ultimate,source:master.name,level:1,damage:85,cost:60,cooldown:5,master:true,ultimate:true});taught=`\n\n🌌 *${master.name} finally teaches you ${master.ultimate}!*`}return buttons(s,u.jid,m,`🥋 *TRAINING COMPLETE*\n\n🪙 -${cost} Gold\n❤️ +4 Bond\n⚔️ +1 ATK • 🛡️ +1 DEF • 💨 +1 SPD\n\nBond: *${n.bondPoints}*${taught}`,'RYUDEN • MASTER TRAINING',[['🥋 Train Again','rpg_train'],['📚 Techniques','rpg_techniques'],['⚔️ RPG Home','rpg_home']])}
 async function bondPanel(s,m){const u=who(m),p=await store.ensurePlayer(u.id,u.name);const next=p.bondPoints<15?'15 — stronger mentorship':p.bondPoints<60?'60 — ultimate training':'MAX milestone reached';return buttons(s,u.jid,m,`❤️ *MASTER BOND*\n\n🧙 ${p.currentMaster||'No Master'}\nBond: *${p.bondPoints}*\nNext milestone: *${next}*\n\nMeaningful Master conversations can earn small Bond. Training earns more. Spam does not.`,'RYUDEN • BOND',[['💬 Talk','rpg_talk_master'],['🥋 Train','rpg_train'],['⚔️ RPG Home','rpg_home']])}
 async function techniquesPanel(s,m){const u=who(m),p=await store.ensurePlayer(u.id,u.name),ts=p.techniques||[];return buttons(s,u.jid,m,`📚 *TECHNIQUES*\n\n${ts.length?ts.map((x,i)=>`${i+1}. *${x.name}* Lv.${x.level||1}\n   💥 ${x.damage||0} • ⚡ ${x.cost||0} • ⏳ ${x.cooldown||0} turn`).join('\n\n'):'No techniques learned yet.'}`,'RYUDEN • SKILLS',[...ts.slice(0,8).map(x=>[x.name,`rpg_skill_${x.key}`]),['🛒 Technique Shop','rpg_shop_skills'],['⚔️ RPG Home','rpg_home']])}
 async function skillPanel(s,m,key){const u=who(m),p=await store.ensurePlayer(u.id,u.name),x=(p.techniques||[]).find(v=>v.key===key);if(!x)return techniquesPanel(s,m);const price=(x.level||1)*120;return buttons(s,u.jid,m,`✨ *${x.name}*\n\nSource: *${x.source||'Ryuden System'}*\nLevel: *${x.level||1}*\n💥 Damage: *${x.damage||0}*${x.armor?`\n🛡️ Armor: *${x.armor}*`:''}\n⚡ Energy: *${x.cost||0}*\n⏳ Cooldown: *${x.cooldown||0} turns*\n\nUpgrade: *${price} Gold*`,'RYUDEN • TECHNIQUE',[['⬆️ Upgrade','rpg_skill_upgrade_'+key],['📚 Techniques','rpg_techniques']])}
 async function upgradeSkill(s,m,key){const u=who(m),p=await store.ensurePlayer(u.id,u.name),x=(p.techniques||[]).find(v=>v.key===key);if(!x)return techniquesPanel(s,m);const price=(x.level||1)*120,paid=await store.spendGold(u.id,price);if(!paid)return send(s,u.jid,m,`🪙 You need *${price} RPG Gold* to upgrade ${x.name}.`);await store.updateTechnique(u.id,key,t=>({...t,level:(t.level||1)+1,damage:Math.round((t.damage||0)*1.15),armor:t.armor?Math.round(t.armor*1.12):t.armor}));return skillPanel(s,m,key)}
 async function shopPanel(s,m,skillsOnly=false){const u=who(m),p=await store.ensurePlayer(u.id,u.name),list=SHOP.filter(x=>!skillsOnly||x.type==='technique');return buttons(s,u.jid,m,`🛒 *RYUDEN SHOP*\n\n🪙 ${p.gold} Gold • 💎 ${p.gems} Gems\n\n${list.map(x=>`*${x.name}* — ${x.price} ${x.currency==='gems'?'💎':'🪙'}\n${x.desc}`).join('\n\n')}`,'RYUDEN • SHOP',[...list.map(x=>[x.name,`rpg_buy_${x.key}`]),['⚔️ RPG Home','rpg_home']])}
 async function buy(s,m,key){const u=who(m),x=SHOP.find(v=>v.key===key);if(!x)return shopPanel(s,m);const p=await store.ensurePlayer(u.id,u.name);if(x.type==='technique'&&(p.techniques||[]).some(t=>t.key===x.key))return send(s,u.jid,m,'✨ You already own that technique.');const paid=x.currency==='gems'?await store.spendGems(u.id,x.price):await store.spendGold(u.id,x.price);if(!paid)return send(s,u.jid,m,`❌ Not enough ${x.currency==='gems'?'Gems':'RPG Gold'}.`);if(x.type==='technique')await store.addTechnique(u.id,{...x,source:'Ryuden System',level:1});else await store.addItem(u.id,{...x,rarity:x.currency==='gems'?'Epic':'Common'});return buttons(s,u.jid,m,`✅ *PURCHASED*\n\n*${x.name}*\n${x.desc}`,'RYUDEN • SHOP',[['🛒 Keep Shopping','rpg_shop'],['🎒 Inventory','rpg_inventory'],['⚔️ RPG Home','rpg_home']])}
 async function inventoryPanel(s,m){const u=who(m),p=await store.ensurePlayer(u.id,u.name),inv=p.inventory||[];return buttons(s,u.jid,m,`🎒 *RPG INVENTORY*\n\n${inv.length?inv.map((x,i)=>`${i+1}. *${x.rarity||'Common'} ${x.name}*\n   ${x.desc||x.kind||''}`).join('\n\n'):'Your inventory is empty.'}`,'RYUDEN • INVENTORY',[['🛒 Shop','rpg_shop'],['⚔️ RPG Home','rpg_home']])}
 async function startBattle(s,m,enemy=null){const u=who(m),p=await store.ensurePlayer(u.id,u.name);if(!p.currentMaster)return masterPanel(s,m);const e=enemy||ENEMIES[Math.floor(Math.random()*ENEMIES.length)],battle={enemy:e,enemyHp:e.hp,playerHp:p.hp,energy:100,guard:0,turn:1,cooldowns:{}};await store.setBattle(u.id,battle);return battlePanel(s,m,battle)}
 async function battlePanel(s,m,b){const u=who(m),p=await store.ensurePlayer(u.id,u.name);return buttons(s,u.jid,m,`⚔️ *BATTLE • TURN ${b.turn}*\n\n> 👹 *${b.enemy.name}*\n❤️ ${Math.max(0,b.enemyHp)}/${b.enemy.hp}\n\n> 👤 *${p.username||u.name||'Player'}*\n❤️ ${Math.max(0,b.playerHp)}/${p.hp} • ⚡ ${b.energy}/100\n\nChoose your action.`,'RYUDEN • COMBAT',[['⚔️ Attack','rpg_battle_attack'],['🛡️ Guard','rpg_battle_guard'],['✨ Skill','rpg_battle_skill'],['🎒 Item','rpg_battle_item'],['🌌 Ultimate','rpg_battle_ultimate'],['🏃 Retreat','rpg_battle_retreat']])}
 async function enemyTurn(p,b){let dmg=Math.max(1,b.enemy.atk+Math.floor(Math.random()*7)-Math.floor(p.def*.45));if(b.guard){dmg=Math.max(1,Math.round(dmg*(1-b.guard)));b.guard=0}b.playerHp-=dmg;return dmg}
 async function finishBattle(s,m,b,won){const u=who(m);await store.setBattle(u.id,null);if(won){const n=await store.addProgress(u.id,{xp:b.enemy.xp,gold:b.enemy.gold,gems:b.enemy.gems,win:1});return buttons(s,u.jid,m,`🏆 *VICTORY*\n\n${b.enemy.name} falls.\n✨ +${b.enemy.xp} XP • 🪙 +${b.enemy.gold}${b.enemy.gems?` • 💎 +${b.enemy.gems}`:''}\n🎖️ ${n.rank} Lv.${n.level}`,'RYUDEN • BATTLE',[['🗺️ Continue','rpg_explore'],['⚔️ RPG Home','rpg_home']])}const p=await store.ensurePlayer(u.id,u.name),loss=Math.max(1,Math.floor(p.gold*.1));await store.addProgress(u.id,{gold:-loss,loss:1});return buttons(s,u.jid,m,`💀 *DEFEAT*\n\n${b.enemy.name} overwhelms you.\n🪙 Lost *${loss} Gold*.`,'RYUDEN • BATTLE',[['⚔️ RPG Home','rpg_home']])}
 async function battleAction(s,m,action,key){const u=who(m),p=await store.ensurePlayer(u.id,u.name),b=p.activeBattle;if(!b)return startBattle(s,m);if(action==='retreat'){await store.setBattle(u.id,null);return buttons(s,u.jid,m,'🏃 *RETREATED*\n\nYou escaped before the rift closed.','RYUDEN • COMBAT',[['⚔️ RPG Home','rpg_home']])}if(action==='skill')return buttons(s,u.jid,m,'✨ *CHOOSE TECHNIQUE*','RYUDEN • COMBAT',[...(p.techniques||[]).slice(0,8).map(x=>[x.name,`rpg_battle_cast_${x.key}`]),['↩️ Battle','rpg_combat']]);if(action==='item')return buttons(s,u.jid,m,'🎒 *CHOOSE ITEM*','RYUDEN • COMBAT',[...(p.inventory||[]).filter(x=>x.heal||x.guard).slice(0,8).map(x=>[x.name,`rpg_battle_use_${x.key}`]),['↩️ Battle','rpg_combat']]);let dealt=0;if(action==='attack')dealt=Math.max(1,p.atk+Math.floor(Math.random()*10)-b.enemy.def);if(action==='guard')b.guard=.6;if(action==='cast'){const t=(p.techniques||[]).find(x=>x.key===key);if(!t)return battlePanel(s,m,b);if(b.energy<(t.cost||0))return send(s,u.jid,m,'⚡ Not enough energy.');b.energy-=t.cost||0;dealt=Math.max(1,(t.damage||20)+Math.floor(p.atk*.6)-b.enemy.def);if(t.armor)b.guard=Math.min(.8,(b.guard||0)+t.armor/100)}if(action==='ultimate'){const t=(p.techniques||[]).find(x=>x.ultimate);if(!t)return send(s,u.jid,m,'🌌 Your Master has not taught you an Ultimate yet.');if(b.energy<(t.cost||60))return send(s,u.jid,m,'⚡ Not enough energy.');b.energy-=t.cost||60;dealt=Math.max(1,(t.damage||80)+p.atk-b.enemy.def)}if(action==='use'){const it=await store.consumeItem(u.id,key);if(!it)return battlePanel(s,m,b);if(it.heal)b.playerHp=Math.min(p.hp,b.playerHp+it.heal);if(it.guard)b.guard=Math.max(b.guard||0,it.guard)}b.enemyHp-=dealt;if(b.enemyHp<=0)return finishBattle(s,m,b,true);const hit=await enemyTurn(p,b);if(b.playerHp<=0)return finishBattle(s,m,b,false);b.turn++;b.energy=Math.min(100,b.energy+10);await store.setBattle(u.id,b);await send(s,u.jid,m,`${dealt?`💥 You dealt *${dealt}* damage.\n`:''}👹 ${b.enemy.name} dealt *${hit}* damage.`);return battlePanel(s,m,b)}
 async function storyPanel(s,m){const u=who(m),p=await store.ensurePlayer(u.id,u.name),st=p.storyState||{},flags=st.flags||{};return buttons(s,u.jid,m,`📖 *ODYSSEY I — THE THIRTEENTH ECHO*\n\nPart *${p.storyChapter+1}/15*\n📍 ${st.location||'Ryuden Central'}\n\n${st.summary||'Rifts have begun appearing where the System says none should exist. Someone is collecting what comes through them.'}\n\nChoices remembered: *${Object.keys(flags).length}*`,'RYUDEN • STORY',[['🗺️ Explore','rpg_explore'],['⚔️ RPG Home','rpg_home']])}
 async function npcScene(s,m,npcKey='kael'){const u=who(m),p=await store.ensurePlayer(u.id,u.name),npc=NPCS[npcKey],st={...(p.storyState||{}),npc:npcKey,location:npc.scene,summary:`You encountered ${npc.name}, ${npc.role}.`,quest:{key:'lost_scout',status:'offered'},flags:{...(p.storyState?.flags||{}),metKael:true}};await store.setStoryState(u.id,st);return buttons(s,u.jid,m,`🗺️ *EAST GATE — STORY ENCOUNTER*\n\n> 🧑 *${npc.name} — ${npc.role}*\n\n“Hold it. If you're Master-bound, I could use your help. The Pale Choir dragged one of my scouts into the old transit tunnels.”\n\nYou can talk to *${npc.name}* normally now, or decide.`,'RYUDEN • NPC',[['✅ Accept Request','rpg_quest_accept'],['❌ Decline','rpg_quest_decline'],['⚔️ RPG Home','rpg_home']])}
 async function questChoice(s,m,accept){const u=who(m),p=await store.ensurePlayer(u.id,u.name),st={...(p.storyState||{})},flags={...(st.flags||{})};flags.lostScout=accept?'accepted':'declined';st.flags=flags;st.quest={key:'lost_scout',status:accept?'accepted':'declined'};st.summary=accept?'You agreed to help Kael recover the missing scout from the transit tunnels.':'You refused Kael’s request. The Pale Choir still has the missing scout.';await store.setStoryState(u.id,st);return buttons(s,u.jid,m,accept?'🧑 *Kael:* “Good. Then stay close. Those tunnels stopped obeying maps three days ago.”':'🧑 *Kael:* “Your choice. Just don’t pretend you weren’t warned when the Choir reaches Ryuden.”','RYUDEN • CHOICE RECORDED',[['🗺️ Continue','rpg_explore'],['📖 Story','rpg_story']])}
 async function explore(s,m){const u=who(m),p=await store.ensurePlayer(u.id,u.name);if(!p.currentMaster)return masterPanel(s,m);const lim=await store.consumeExplore(u.id);if(!lim.ok)return buttons(s,u.jid,m,`⏳ *EXPLORATION RECOVERY*\n\nYou've used *10 exploration actions* in this 15-minute window.\nExplore again in *${fmtMs(lim.remaining)}*.`,'RYUDEN • EXPLORATION',[['📖 Story','rpg_story'],['🧙 Master','rpg_master'],['⚔️ RPG Home','rpg_home']]);const st=p.storyState||{};if(!st.flags?.metKael)return npcScene(s,m,'kael');const roll=Math.random();if(roll<.55)return startBattle(s,m);if(roll<.75){const gold=20+Math.floor(Math.random()*61);await store.addProgress(u.id,{xp:18,gold});return buttons(s,u.jid,m,`🗺️ *RIFT CACHE*\n\n✨ +18 XP • 🪙 +${gold} Gold\nExploration uses left this window: *${lim.remainingUses}*`,'RYUDEN • EXPLORE',[['🗺️ Continue','rpg_explore'],['⚔️ RPG Home','rpg_home']])}return buttons(s,u.jid,m,'📖 *THE WORLD MOVES*\n\nA Pale Choir symbol has been carved into the stone—fresh enough that the dust is still falling.\n\nSomebody passed through here moments ago.','RYUDEN • STORY',[['🗺️ Follow Trail','rpg_explore'],['📖 Story','rpg_story']])}
 async function daily(s,m){const u=who(m),r=await store.daily(u.id);if(!r.ok)return send(s,u.jid,m,`⏳ Daily already claimed. Return in about *${Math.ceil(r.remaining/3600000)}h*.`);return buttons(s,u.jid,m,`🎁 *DAILY REWARD*\n\n🪙 +${r.gold} RPG Gold${r.gems?`\n💎 +${r.gems} Gem`:''}`,'RYUDEN • DAILY',[['⚔️ RPG Home','rpg_home']])}
 async function guildPanel(s,m){const u=who(m),g=u.jid.endsWith('@g.us')?await store.guildForGroup(u.jid):await store.guildForPlayer(u.id);return buttons(s,u.jid,m,g?`🏰 *${g.name}*\n\nLevel ${g.level} • XP ${economy.fmt(g.xp)}\nTreasury ${economy.fmt(g.treasury)} • Members ${g.member_count}`:'🏰 *GUILDS*\n\nNo guild found. Group admins can propose one with */guild create [name]*.','RYUDEN • GUILDS',[['⚔️ RPG Home','rpg_home']])}
 async function isAdmin(s,j,id){if(!j.endsWith('@g.us'))return false;const meta=await s.groupMetadata(j),p=meta.participants.find(x=>[x.id,x.phoneNumber,x.lid].filter(Boolean).some(v=>String(v).split(':')[0].split('@')[0]===id));return !!p?.admin}
 async function adminIds(s,j){const meta=await s.groupMetadata(j);return meta.participants.filter(p=>p.admin).map(p=>String(p.id||p.phoneNumber||p.lid||'').split(':')[0].split('@')[0])}
 async function section(s,m,id){if(id==='rpg_home')return panel(s,m);if(id==='rpg_explore')return explore(s,m);if(id==='rpg_master')return masterPanel(s,m);if(id==='rpg_train')return train(s,m);if(id==='rpg_bond')return bondPanel(s,m);if(id==='rpg_techniques')return techniquesPanel(s,m);if(id==='rpg_inventory')return inventoryPanel(s,m);if(id==='rpg_story')return storyPanel(s,m);if(id==='rpg_guild')return guildPanel(s,m);if(id==='rpg_daily')return daily(s,m);if(id==='rpg_shop')return shopPanel(s,m);if(id==='rpg_shop_skills')return shopPanel(s,m,true);if(id==='rpg_combat'){const p=await store.ensurePlayer(who(m).id,displayName(m));return p.activeBattle?battlePanel(s,m,p.activeBattle):startBattle(s,m)}if(id==='rpg_quest_accept')return questChoice(s,m,true);if(id==='rpg_quest_decline')return questChoice(s,m,false);if(id.startsWith('rpg_masters_page_'))return archivePanel(s,m,id.slice(17));if(id.startsWith('rpg_master_'))return chooseMaster(s,m,id.slice(11));if(id.startsWith('rpg_buy_'))return buy(s,m,id.slice(8));if(id.startsWith('rpg_skill_upgrade_'))return upgradeSkill(s,m,id.slice(18));if(id.startsWith('rpg_skill_'))return skillPanel(s,m,id.slice(10));if(id.startsWith('rpg_battle_cast_'))return battleAction(s,m,'cast',id.slice(16));if(id.startsWith('rpg_battle_use_'))return battleAction(s,m,'use',id.slice(15));if(id.startsWith('rpg_battle_'))return battleAction(s,m,id.slice(11));if(id==='rpg_talk_master')return false;return false}
 async function route(s,m,c){const u=who(m),a=c.args||[];if(c.command==='/rpg')return panel(s,m),true;if(c.command==='/masters')return (+a[0]>0?archivePanel(s,m,+a[0]):masterPanel(s,m)),true;if(c.command==='/master')return chooseMaster(s,m,String(a[0]||'').toLowerCase())||true;if(c.command==='/train')return train(s,m),true;if(c.command==='/techniques'||c.command==='/skills')return techniquesPanel(s,m),true;if(c.command==='/shop')return shopPanel(s,m),true;if(c.command==='/combat'||c.command==='/fight')return section(s,m,'rpg_combat'),true;if(c.command==='/daily')return daily(s,m),true;if(c.command==='/explore')return explore(s,m),true;if(c.command==='/inventory')return inventoryPanel(s,m),true;if(c.command==='/story')return storyPanel(s,m),true;if(['/rlb','/rpgleaderboard'].includes(c.command)){const rows=await store.leaderboard(10);await send(s,u.jid,m,`⚔️ *ODYSSEY LEADERBOARD*\n\n${rows.map((p,i)=>`${i===0?'🥇':i===1?'🥈':i===2?'🥉':`${i+1}.`} *${p.username||'Player'}*\n   🎖️ ${p.rank} Lv.${p.level} • 💥 ${p.powerScore}\n   ⚔️ ${p.winCount}W / ${p.lossCount}L`).join('\n\n')||'No adventurers yet.'}`);return true}if(c.command==='/guild'){const sub=String(a[0]||'info').toLowerCase();if(sub==='create'){if(!u.jid.endsWith('@g.us'))return send(s,u.jid,m,'🏰 Guilds can only be created in WhatsApp groups.'),true;if(!(await isAdmin(s,u.jid,u.id)))return send(s,u.jid,m,'🛡️ Only a group admin can propose a guild.'),true;const name=a.slice(1).join(' ').trim();if(name.length<3||name.length>32)return send(s,u.jid,m,'Use */guild create [name]* — 3 to 32 characters.'),true;const r=await store.createProposal(u.jid,name,u.id,await adminIds(s,u.jid));return send(s,u.jid,m,r.created?`🏰 *GUILD CREATED*\n\n${r.guild.name}`:r.ok?`🗳️ *GUILD PROPOSAL*\n\n${name}\nVotes: 1/${r.needed}\nAdmins: */guild accept*`:`❌ ${r.message}`),true}if(sub==='accept'){if(!(await isAdmin(s,u.jid,u.id)))return send(s,u.jid,m,'🛡️ Only group admins can vote.'),true;const r=await store.voteProposal(u.jid,u.id);return send(s,u.jid,m,r.created?`🏰 *GUILD APPROVED* — ${r.guild.name}`:r.ok?`🗳️ Vote accepted. ${r.votes}/${r.needed}`:`❌ ${r.message}`),true}if(sub==='join'){const g=await store.joinGroupGuild(u.jid,u.id);return send(s,u.jid,m,g?`🏰 Joined *${g.name}*.`:'❌ No guild belongs to this group.'),true}return guildPanel(s,m),true}return false}
 async function npcContext(id){const p=await store.getPlayer(id),key=p?.storyState?.npc;if(!key||!NPCS[key])return null;return {...NPCS[key],key}}
 const chatBond=new Map();async function recordMasterChat(id){const now=Date.now(),last=chatBond.get(id)||0;if(now-last<5*60*1000)return null;chatBond.set(id,now);return store.addBond(id,1)}
 return{route,section,panel,getPlayer:store.getPlayer,npcContext,recordMasterChat}
}
module.exports={createRpg}
