'use strict'
const store=require('./rpg-store')
const {canonicalUserId,displayName}=require('./economy-router')
const ENEMIES=[{name:'Wandering Wraith',hp:60,atk:10,def:4,xp:30,gold:15,gems:0},{name:'Corrupted Golem',hp:90,atk:14,def:10,xp:45,gold:25,gems:0},{name:'Void Stalker',hp:75,atk:18,def:6,xp:50,gold:30,gems:1},{name:'Rift Hound',hp:55,atk:12,def:5,xp:25,gold:12,gems:0}]
const BOSSES=[{name:'The Hollow Sovereign',hp:260,atk:26,def:14,xp:220,gold:150,gems:8},{name:'Chronophage, Eater of Time',hp:300,atk:24,def:18,xp:260,gold:180,gems:10}]
const STORY=["You find a torn page of a forgotten Odyssey. It hints at a monarch who once refused the System's judgment.","The sky fractures for a moment, revealing a world that never chose a Master.","You hear whispers in a language your Master refuses to translate."]
const RARITIES=['Common','Common','Common','Uncommon','Uncommon','Rare','Epic','Legendary','Mythic','Ascended']
const MASTER_KEYS=new Set(store.MASTERS.map(x=>x.key)),FEATURED=store.MASTERS.slice(0,10),ARCHIVE=store.MASTERS.slice(10),PAGE_SIZE=10
function item(){const kinds=['weapon','armor','accessory'],names=['Fractured Blade','System Dagger','Void-Touched Spear','Shadow-Woven Cloak','Rift Compass','System Core Fragment'];return{name:names[Math.floor(Math.random()*names.length)],rarity:RARITIES[Math.floor(Math.random()*RARITIES.length)],kind:kinds[Math.floor(Math.random()*kinds.length)]}}
function createRpg({economy,logger,sendButtons}){
 const send=(s,j,m,t)=>s.sendMessage(j,{text:t},{quoted:m})
 const buttons=(s,j,m,body,footer,defs)=>sendButtons?sendButtons(s,j,body,footer,defs,canonicalUserId(m.key)):send(s,j,m,body)
 async function panel(sock,m){const id=canonicalUserId(m.key),name=displayName(m),jid=m.key.remoteJid,p=await store.ensurePlayer(id,name),g=await store.guildForPlayer(id);const body=['⚔️ *RYUDEN ODYSSEY*','',`> 👤 *${p.username||name||'Player'}*`,`🎖️ *${p.rank} • Lv. ${p.level}*   ✨ ${p.xp}/${store.xpNeed(p.level)} XP`,`💥 Power *${p.powerScore}*`,'',`❤️ ${p.hp}   ⚔️ ${p.atk}   🛡️ ${p.def}   💨 ${p.spd}`,`🍀 ${p.luck}   🎯 ${p.crit}%`,'',`🧙 ${p.currentMaster||'No Master'}   🏰 ${g?.name||'No Guild'}`,`🪙 ${economy.fmt(p.gold)} Gold   💎 ${p.gems} Gems`,`📖 Odyssey • Part ${p.storyChapter+1}/15`].join('\n');return buttons(sock,jid,m,body,'RYUDEN • ODYSSEY',[['🗺️ Explore','rpg_explore'],['🧙 Master','rpg_master'],['🎒 Inventory','rpg_inventory'],['🏰 Guild','rpg_guild'],['📖 Odyssey','rpg_story'],['🎁 Daily','rpg_daily'],['⬅️ Menu','menu_main']])}
 async function masterPanel(sock,m){const id=canonicalUserId(m.key),jid=m.key.remoteJid,p=await store.ensurePlayer(id,displayName(m));if(p.currentMaster)return buttons(sock,jid,m,`🧙 *YOUR MASTER*\n\n> *${p.currentMaster}*\nBond: *${p.bondPoints}*\n\nYour Master can react to your real Odyssey context through the AI link.`,'RYUDEN • MASTER',[['💬 Talk to Master','rpg_talk_master'],['⚔️ RPG Home','rpg_home']]);const defs=[...FEATURED.map(x=>[x.name,`rpg_master_${x.key}`]),['🔎 Explore More Masters','rpg_masters_page_1']];return buttons(sock,jid,m,'🧙 *CHOOSE YOUR MASTER*\n\nTen featured Masters are shown first. Want someone else? Open the Master Archive for 50 more choices.\n\nYour Master shapes your Odyssey universe, abilities and story.','RYUDEN • DESTINY',defs)}
 async function archivePanel(sock,m,page=1){const p=await store.ensurePlayer(canonicalUserId(m.key),displayName(m));if(p.currentMaster)return masterPanel(sock,m);const pages=Math.ceil(ARCHIVE.length/PAGE_SIZE),n=Math.max(1,Math.min(pages,Number(page)||1)),list=ARCHIVE.slice((n-1)*PAGE_SIZE,n*PAGE_SIZE),defs=list.map(x=>[x.name,`rpg_master_${x.key}`]);if(n>1)defs.push(['◀️ Previous',`rpg_masters_page_${n-1}`]);if(n<pages)defs.push(['Next ▶️',`rpg_masters_page_${n+1}`]);defs.push(['⭐ Featured','rpg_master']);return buttons(sock,m.key.remoteJid,m,`🔎 *MASTER ARCHIVE • ${n}/${pages}*\n\n${list.map(x=>`• *${x.name}* — ${x.universe}`).join('\n')}\n\nChoose the Master that fits your Odyssey.`,'RYUDEN • 60 MASTERS',defs)}
 async function inventoryPanel(sock,m){const p=await store.ensurePlayer(canonicalUserId(m.key),displayName(m)),x=p.inventory.length?p.inventory.map((v,i)=>`${i+1}. *${v.rarity}* ${v.name}\n   └ ${v.kind}`).join('\n'):'> Your inventory is empty.';return buttons(sock,m.key.remoteJid,m,`🎒 *RPG INVENTORY*\n\n${x}`,'RYUDEN • INVENTORY',[['🗺️ Explore','rpg_explore'],['⚔️ RPG Home','rpg_home']])}
 async function storyPanel(sock,m){const p=await store.ensurePlayer(canonicalUserId(m.key),displayName(m));return buttons(sock,m.key.remoteJid,m,`📖 *YOUR ODYSSEY*\n\n🧙 Master: *${p.currentMaster||'Not chosen'}*\n📍 Current Part: *${p.storyChapter+1}/15*\n🎖️ Rank: *${p.rank}*\n\nYour choices, battles and encounters form your personal Odyssey log.`,'RYUDEN • STORY',[['🗺️ Explore','rpg_explore'],['⚔️ RPG Home','rpg_home']])}
 async function guildPanel(sock,m){const id=canonicalUserId(m.key),jid=m.key.remoteJid,g=jid.endsWith('@g.us')?await store.guildForGroup(jid):await store.guildForPlayer(id);return buttons(sock,jid,m,g?`🏰 *${g.name}*\n\nLevel: *${g.level}*\nXP: *${economy.fmt(g.xp)}*\nTreasury: *${economy.fmt(g.treasury)}*\nMembers: *${g.member_count}*`:'🏰 *GUILDS*\n\nNo guild found.\n\nOnly WhatsApp group admins can propose a guild with */guild create [name]*. Other group admins vote with */guild accept*.','RYUDEN • GUILDS',[['⚔️ RPG Home','rpg_home']])}
 async function isAdmin(sock,jid,userId){if(!jid.endsWith('@g.us'))return false;const meta=await sock.groupMetadata(jid),p=meta.participants.find(x=>[x.id,x.phoneNumber,x.lid].filter(Boolean).some(v=>String(v).split(':')[0].split('@')[0]===userId));return !!p?.admin}
 async function adminIds(sock,jid){const meta=await sock.groupMetadata(jid);return meta.participants.filter(p=>p.admin).map(p=>String(p.id||p.phoneNumber||p.lid||'').split(':')[0].split('@')[0])}
 async function explore(sock,m){const id=canonicalUserId(m.key),name=displayName(m),jid=m.key.remoteJid,p=await store.ensurePlayer(id,name);if(!p.currentMaster){await masterPanel(sock,m);return true}const roll=Math.random();if(roll<.22){const gold=20+Math.floor(Math.random()*61),it=Math.random()<.35?item():null,n=await store.addProgress(id,{xp:20,gold,item:it});await buttons(sock,jid,m,`🗺️ *SYSTEM CACHE*\n\nA sealed cache pulses beneath the ruins.\n\n✨ +20 XP\n🪙 +${gold} Gold${it?`\n🎒 *${it.rarity} ${it.name}*`:''}\n\n🎖️ ${n.rank} • Lv.${n.level}`,'RYUDEN • EXPLORE',[['🗺️ Explore Again','rpg_explore'],['🎒 Inventory','rpg_inventory'],['⚔️ RPG Home','rpg_home']]);return true}if(roll<.42){await buttons(sock,jid,m,`📖 *ODYSSEY ECHO*\n\n${STORY[Math.floor(Math.random()*STORY.length)]}`,'RYUDEN • UNKNOWN RECORD',[['➡️ Continue','rpg_explore'],['📖 Odyssey','rpg_story'],['⚔️ RPG Home','rpg_home']]);return true}const boss=roll>.92,e=(boss?BOSSES:ENEMIES)[Math.floor(Math.random()*(boss?BOSSES:ENEMIES).length)],playerHit=Math.max(1,p.atk+Math.floor(Math.random()*12)-e.def),enemyHit=Math.max(1,e.atk+Math.floor(Math.random()*8)-p.def),turns=Math.ceil(e.hp/playerHit),damage=enemyHit*Math.max(0,turns-1),won=damage<p.hp;if(won){const drop=Math.random()<(boss?.7:.18)?item():null,n=await store.addProgress(id,{xp:e.xp,gold:e.gold,gems:e.gems,item:drop,win:1});await buttons(sock,jid,m,`${boss?'👑 *BOSS DEFEATED*':'⚔️ *VICTORY*'}\n\n> *${e.name}*\n\n❤️ Damage taken: ${damage}\n✨ +${e.xp} XP\n🪙 +${e.gold} Gold${e.gems?`\n💎 +${e.gems} Gems`:''}${drop?`\n🎒 *${drop.rarity} ${drop.name}*`:''}\n\n🎖️ ${n.rank} • Lv.${n.level}`,'RYUDEN • BATTLE',[['🗺️ Continue','rpg_explore'],['🎒 Inventory','rpg_inventory'],['⚔️ RPG Home','rpg_home']])}else{const loss=Math.max(1,Math.floor(p.gold*.1));await store.addProgress(id,{gold:-loss,loss:1});await buttons(sock,jid,m,`💀 *DEFEAT*\n\n> *${e.name}*\n\nThe System drags you back to Ryuden.\n🪙 Lost *${loss}* RPG Gold.`,'RYUDEN • DEFEAT',[['🗺️ Try Again','rpg_explore'],['⚔️ RPG Home','rpg_home']])}return true}
 async function daily(sock,m){const r=await store.daily(canonicalUserId(m.key));if(!r.ok){await buttons(sock,m.key.remoteJid,m,`⏳ *DAILY ALREADY CLAIMED*\n\nReturn in about *${Math.ceil(r.remaining/3600000)}h*.`,'RYUDEN • DAILY',[['⚔️ RPG Home','rpg_home']]);return true}await buttons(sock,m.key.remoteJid,m,`🎁 *DAILY REWARD*\n\n🪙 +${r.gold} RPG Gold${r.gems?`\n💎 +${r.gems} Gem`:''}`,'RYUDEN • DAILY',[['🗺️ Explore','rpg_explore'],['⚔️ RPG Home','rpg_home']]);return true}
 async function chooseMaster(sock,m,key){if(!MASTER_KEYS.has(key))return false;const p=await store.ensurePlayer(canonicalUserId(m.key),displayName(m));if(p.currentMaster){await masterPanel(sock,m);return true}const r=await store.setMaster(canonicalUserId(m.key),key);await buttons(sock,m.key.remoteJid,m,`🧙 *DESTINY ACCEPTED*\n\n> *${r.master.name}* — ${r.master.universe}\n\n🌀 ${r.master.passive}\n⚔️ ${r.master.skill}\n🌌 ${r.master.ultimate}\n\nYour Odyssey has begun.`,'RYUDEN • MASTER',[['🗺️ Begin Odyssey','rpg_explore'],['⚔️ RPG Home','rpg_home']]);return true}
 async function section(sock,m,id){if(id==='rpg_home')return panel(sock,m);if(id==='rpg_explore')return explore(sock,m);if(id==='rpg_master')return masterPanel(sock,m);if(id==='rpg_inventory')return inventoryPanel(sock,m);if(id==='rpg_guild')return guildPanel(sock,m);if(id==='rpg_story')return storyPanel(sock,m);if(id==='rpg_daily')return daily(sock,m);if(id==='rpg_talk_master')return false;if(id.startsWith('rpg_masters_page_'))return archivePanel(sock,m,id.slice(17));if(id.startsWith('rpg_master_'))return chooseMaster(sock,m,id.slice(11));return false}
 async function route(sock,m,c){const id=canonicalUserId(m.key),name=displayName(m),jid=m.key.remoteJid,args=c.args||[];if(c.command==='/rpg'){await panel(sock,m);return true}if(c.command==='/masters'){const pg=Number(args[0]||0);if(pg>0)await archivePanel(sock,m,pg);else await masterPanel(sock,m);return true}if(c.command==='/master'){const p=await store.ensurePlayer(id,name);if(p.currentMaster){await masterPanel(sock,m);return true}const key=String(args[0]||'').toLowerCase();if(!MASTER_KEYS.has(key)){await masterPanel(sock,m);return true}return chooseMaster(sock,m,key)}if(c.command==='/daily')return daily(sock,m);if(c.command==='/explore')return explore(sock,m);if(c.command==='/inventory'){await inventoryPanel(sock,m);return true}if(['/rlb','/rpgleaderboard'].includes(c.command)){const rows=await store.leaderboard(10);await send(sock,jid,m,`🏆 *ODYSSEY POWER RANKING*\n\n${rows.map((p,i)=>`${i+1}. *${p.username||'Player'}* — ${p.rank} Lv.${p.level}\n   💥 ${p.powerScore}`).join('\n\n')||'No adventurers yet.'}`);return true}if(c.command==='/guild'){const sub=String(args[0]||'info').toLowerCase();if(sub==='create'){if(!jid.endsWith('@g.us')){await send(sock,jid,m,'🏰 Guilds can only be created from WhatsApp groups.');return true}if(!(await isAdmin(sock,jid,id))){await send(sock,jid,m,'🛡️ Only a *group admin* can propose a guild.');return true}const gname=args.slice(1).join(' ').trim();if(gname.length<3||gname.length>32){await send(sock,jid,m,'Use */guild create [name]* — 3 to 32 characters.');return true}await store.ensurePlayer(id,name);const ids=await adminIds(sock,jid),r=await store.createProposal(jid,gname,id,ids);if(!r.ok){await send(sock,jid,m,`❌ ${r.message}`);return true}await send(sock,jid,m,r.created?`🏰 *GUILD CREATED*\n\n*${r.guild.name}* now represents this group.`:`🗳️ *GUILD PROPOSAL*\n\n> 🏰 *${gname}*\nProposed by: *${name||'Group Admin'}*\n\nVotes: *1/${r.needed}* required\nAdmins: */guild accept*\n⏳ Expires in 24 hours.`);return true}if(sub==='accept'){if(!jid.endsWith('@g.us')||!(await isAdmin(sock,jid,id))){await send(sock,jid,m,'🛡️ Only group admins can vote.');return true}const r=await store.voteProposal(jid,id);await send(sock,jid,m,!r.ok?`❌ ${r.message}`:r.created?`🏰 *GUILD APPROVED!*\n\n*${r.guild.name}* has been founded.\nVote: *${r.votes}/${r.needed}*.`:`🗳️ Vote accepted for *${r.name}*.\nVotes: *${r.votes}/${r.needed}*.`);return true}if(sub==='join'){if(!jid.endsWith('@g.us')){await send(sock,jid,m,'Use */guild join* inside the guild’s WhatsApp group.');return true}const g=await store.joinGroupGuild(jid,id);await send(sock,jid,m,g?`🏰 You joined *${g.name}*.`:'❌ This group has no guild yet.');return true}await guildPanel(sock,m);return true}return false}
 return{route,section,panel,getPlayer:id=>store.getPlayer(id)}
}
module.exports={createRpg}
