'use strict'
const http=require('http'),fs=require('fs/promises'),path=require('path'),pino=require('pino')
const {createAuthState,clearAuthState,listAuthSessions,closeAuthStore,pingDatabase,database}=require('./auth-store')
const {createDashboard}=require('./dashboard')
const {createInstanceLease}=require('./instance-lease')
const {buildEnterMessage,relayOptions,createTracker}=require('./button-test')
const {createEconomyStore}=require('./economy-store'),{createEconomyRouter}=require('./economy-router'),{createCasino}=require('./casino'),{createUi}=require('./ui')
const {createCursedSticker}=require('./cursed-sticker')
const {resolveButtonId,isKnownButtonInteraction,shouldHandleUpsert,ReplyRateLimiter}=require('./message-guard')
const {resolveMessageUserId}=require('./identity')
const {ORIGINAL_OWNER}=require('./access')
const accountConfig=require('./account-config'),ai=require('./ai-v2')
const logger=pino({level:process.env.LOG_LEVEL||'info'}),port=Number(process.env.PORT||3000),TEST_IMAGE_PATH=path.join(__dirname,'..','assets','speed-test.jpg'),MENU_IMAGE_PATH=path.join(__dirname,'..','assets','ryuden-menu.jpg'),API_IMAGE_URL=process.env.TEST_IMAGE_URL||'https://picsum.photos/900/1200.jpg'
const economy=createEconomyStore({database,logger}),routeEconomy=createEconomyRouter({economy,logger}),casino=createCasino({economy})

function actorId(m){const k=m?.key||{};return String(k.participantAlt||k.participant||k.remoteJidAlt||k.remoteJid||'').split(':')[0].split('@')[0]}
function actorIdFromJid(value){return String(value||'').split(':')[0].split('@')[0]}
function escapeRegex(value){return String(value||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function ownedButton(raw){const x=String(raw||''),m=x.match(/^(.*)~u:([0-9]+)$/);return m?{id:m[1],owner:m[2]}:{id:x,owner:null}}
class GlobalOutputGuard{
 constructor(logger){this.logger=logger;this.recent=[];this.queue=[];this.cooling=false;this.draining=false;this.timer=null;this.rawSend=null;this.windowMs=1500;this.maxBurst=3;this.minCooldown=5000;this.maxCooldown=10000;this.spacing=650;this.noticeJid=null}
 setRawSend(fn){this.rawSend=fn}
 setNoticeText(value){this.noticeText=String(value||'').trim()}
 async run(jid,fn){const now=Date.now();this.recent=this.recent.filter(t=>now-t<=this.windowMs);if(this.cooling||this.draining){return new Promise((resolve,reject)=>this.queue.push({jid,fn,resolve,reject}))}if(this.recent.length>=this.maxBurst){this.cooling=true;this.noticeJid=jid;const wait=this.minCooldown+Math.floor(Math.random()*(this.maxCooldown-this.minCooldown+1));this.logger.warn({waitMs:wait,queued:this.queue.length+1},'Global WhatsApp output cooldown started');const promise=new Promise((resolve,reject)=>this.queue.push({jid,fn,resolve,reject}));this.timer=setTimeout(()=>void this.resume(),wait);return promise}this.recent.push(now);return fn()}
 async resume(){this.cooling=false;this.recent=[];if(this.rawSend&&this.noticeJid&&this.noticeText){await this.rawSend(this.noticeJid,{text:this.noticeText}).catch(()=>{})}this.noticeJid=null;this.draining=true;if(this.queue.length)await new Promise(r=>setTimeout(r,this.spacing));while(this.queue.length){const q=this.queue.shift();try{q.resolve(await q.fn())}catch(e){q.reject(e)}if(this.queue.length)await new Promise(r=>setTimeout(r,this.spacing))}this.draining=false;this.recent=[]}
}
class WhatsAppConnection{
 constructor(sessionId,primary=false){this.sessionId=sessionId;this.primary=primary;this.log=logger.child({waSession:sessionId});this.sock=null;this.baileys=null;this.cursedSticker=null;this.ui=null;this.config=null;this.state='starting';this.registered=false;this.storage='unknown';this.connectedAt=null;this.generation=0;this.reconnectAttempt=0;this.pairingReady=false;this.pairingInFlight=false;this.stopping=false;this.paused=false;this.lastMessageAt=null;this.messagesHandled=0;this.incidents=[];this.seen=new Map();this.minesGames=new Map();this.lastAutoReply=new Map();this.outputGuard=new GlobalOutputGuard(this.log);this.replyLimiter=new ReplyRateLimiter()}
 status(){return{sessionId:this.sessionId,label:this.config?.label||'',mode:this.config?.mode||(this.primary?'lily':'autoreply'),personaName:this.config?.personaName||null,enabled:this.config?.enabled!==false,replyCooldownSec:this.config?.replyCooldownSec||30,groupMode:this.config?.groupMode||'mentions',mutedChats:this.config?.mutedChats?.length||0,state:this.state,registered:this.registered,storage:this.storage,phone:this.sock?.user?.id||null,paused:this.paused,lastMessageAt:this.lastMessageAt,messagesHandled:this.messagesHandled,uptimeSec:this.connectedAt?Math.floor((Date.now()-this.connectedAt)/1000):0}}
 setPaused(value){this.paused=!!value}
 incidentHistory(){return this.incidents.slice()}
 async start(){this.config=await accountConfig.get(this.sessionId,this.primary);if(!this.baileys)this.baileys=await import('@whiskeysockets/baileys');this.outputGuard.setNoticeText(this.config.mode==='lily'?'⚠️ *RYUDEN COOLDOWN ENDED*\n\nToo many requests reached Rimuru at once. Please avoid spamming commands or buttons so the WhatsApp account stays safe.':'');await this.connect()}
 async updateConfig(patch){this.config=await accountConfig.save(this.sessionId,patch,this.primary);return this.config}
 async connect(){if(this.stopping)return;const b=this.baileys,{state,saveCreds,storage}=await createAuthState(b,this.sessionId);this.registered=!!state.creds.registered;this.storage=storage;this.state=this.registered?'connecting':'waiting-for-pair';this.pairingReady=false;const g=++this.generation,{version}=await b.fetchLatestBaileysVersion(),sock=b.default({version,auth:{creds:state.creds,keys:b.makeCacheableSignalKeyStore(state.keys,this.log)},browser:b.Browsers.ubuntu('Chrome'),printQRInTerminal:false,markOnlineOnConnect:false,syncFullHistory:false,generateHighQualityLinkPreview:false,defaultQueryTimeoutMs:60000,logger:this.log.child({module:'baileys'})});this.sock=sock;const rawSend=sock.sendMessage.bind(sock);this.outputGuard.setRawSend(rawSend);sock.sendMessage=(jid,content,opts)=>this.outputGuard.run(jid,()=>rawSend(jid,content,opts));this.buttonTracker?.dispose();this.buttonTracker=createTracker(sock,this.log);sock.ev.on('creds.update',async()=>{await saveCreds();this.registered=!!state.creds.registered});sock.ev.on('messages.upsert',({messages,type})=>{if(!['notify','append'].includes(type))return;for(const m of messages)void this.handleMessage(sock,m,type).catch(async e=>{this.log.error({err:e,jid:m?.key?.remoteJid},'WhatsApp command failed');if(m?.key?.remoteJid)await sock.sendMessage(m.key.remoteJid,{text:`Command failed: ${e.message}`},{quoted:m}).catch(()=>{})})});sock.ev.on('connection.update',({connection,lastDisconnect,qr})=>{if(this.generation!==g||this.sock!==sock)return;if(qr)this.pairingReady=true;if(connection==='open'){this.state='connected';this.connectedAt=Date.now();this.reconnectAttempt=0;this.pairingReady=true;this.log.info('WhatsApp connected')}if(connection==='close')void this.onClose(sock,g,lastDisconnect)});this.log.info({storage,registered:this.registered},'WhatsApp socket started')}
 async onClose(sock,g,d){if(this.generation!==g||this.sock!==sock)return;this.buttonTracker?.dispose();const code=d?.error?.output?.statusCode,message=String(d?.error?.message||''),conflict=code===440||/conflict|replaced/i.test(message);this.sock=null;this.state=code===401?'logged-out':conflict?'standby-conflict':'disconnected';if(this.stopping||code===401||code===429)return;if(conflict){logger.error({code},'WhatsApp session replaced; waiting 60 seconds before one safe recovery attempt');setTimeout(()=>{if(!this.stopping&&!this.sock&&this.generation===g)void this.connect()},60000);return}this.reconnectAttempt++;setTimeout(()=>{if(!this.stopping&&!this.sock&&this.generation===g)void this.connect()},Math.min(30000,2000*(2**Math.min(this.reconnectAttempt,4))))}
 async waitForPairingReady(g,t=20000){const st=Date.now();while(Date.now()-st<t){if(g!==this.generation)throw Error('WhatsApp socket restarted; run /pair again');if(this.sock&&this.pairingReady)return;await new Promise(r=>setTimeout(r,150))}throw Error('WhatsApp did not become pairing-ready')}
 async requestPairingCode(raw){if(this.pairingInFlight)throw Error('A pairing request is already running');const phone=String(raw).replace(/\D/g,'').replace(/^0+/,'');if(!/^\d{8,15}$/.test(phone))throw Error('Use international format');this.pairingInFlight=true;try{await this.resetSocket(true);await this.waitForPairingReady(this.generation);this.state='pairing';return await this.sock.requestPairingCode(phone)}finally{this.pairingInFlight=false}}
 async resetSocket(clear){this.buttonTracker?.dispose();this.generation++;const old=this.sock;this.sock=null;try{old?.end(undefined)}catch{}if(clear)await clearAuthState(this.sessionId);this.reconnectAttempt=0;await this.connect()}
 async reconnect(){await this.resetSocket(false)}
 async handleMessage(sock,m,type='notify'){const jid=m?.key?.remoteJid,id=m?.key?.id;if(!jid||!id||jid==='status@broadcast'||this.seen.has(id))return;const content=this.baileys.normalizeMessageContent(m.message)||{};if(this.config?.mode==='autoreply')return this.handleAutoReply(sock,m,content,type);const button=resolveButtonId(content),known=isKnownButtonInteraction(content);if(!shouldHandleUpsert(content,{fromMe:!!m.key.fromMe,type}))return;this.lastMessageAt=new Date().toISOString();this.messagesHandled++;if(this.paused)return;this.seen.set(id,Date.now());if(this.seen.size>2000)this.seen.clear();if(known)logger.info({jid,id,type,fromMe:!!m.key.fromMe,button,types:Object.keys(content)},'Rimuru button tap accepted');const ob=ownedButton(button),actor=await resolveMessageUserId(sock,m)||actorId(m);if(ob.owner&&ob.owner!==actor){await sock.sendMessage(jid,{text:'🔒 *NOT YOUR WINDOW*\n\nThis player interface belongs to someone else.\nUse */rpg* to open your own.'},{quoted:m});return}const actionButton=ob.id;
  if(!this.ui)this.ui=createUi({economy,casino,logger:this.log,accountId:this.sessionId,sendButtons:(s,j,b,f,d,o)=>this.sendNativeButtons(s,j,b,f,d,o),sendUrlButton:(s,j,b,f,l,u,q)=>this.sendUrlButton(s,j,b,f,l,u,q),aiIncidentReporter:event=>this.reportAiIncident(sock,event)})
  if(!this.cursedSticker)this.cursedSticker=createCursedSticker({baileys:this.baileys,logger})
  const rawText=String(content.conversation||content.extendedTextMessage?.text||'').trim(),isStart=/^\/start(?:\s|$)/i.test(rawText)
  if((actionButton||rawText.startsWith('/')||rawText.toLowerCase().startsWith('!claim'))&&!isStart){const account=await economy.findUser(actor);if(!account?.registeredAt){await sock.sendMessage(jid,{text:'🌸 *YOU HAVEN’T MET LILY YET*\n\nUse */start* to register before using any Lily command or button.'},{quoted:m});return}}
  if(actionButton||rawText.startsWith('/')||rawText.toLowerCase().startsWith('!claim')){const limit=this.replyLimiter.check(m);if(!limit.allowed){if(limit.warn)await sock.sendMessage(jid,{text:`🤫 *EASY THERE*\n\nThree requests came in too quickly. Lily is ignoring commands for ${Math.ceil(limit.durationMs/1000)} seconds.`},{quoted:m});return}}
  if(await this.cursedSticker.handle(sock,m,content))return
  if(actionButton){if(['menu_','casino_','start_','rpg_','owner_','duel_'].some(p=>actionButton.startsWith(p))){await this.ui.section(sock,m,actionButton);return}if(actionButton==='ryuden_enter'){await this.ui.menu(sock,m);return}if(actionButton.startsWith('mines_')){await this.handleMinesButton(sock,m,`${jid}:${m.key.participant||jid}`,actionButton);return}}
  if(await this.ui.route(sock,m,content))return;if(await routeEconomy(sock,m,content))return;if(await this.ui.maybeAi?.(sock,m,content))return
  const text=String(content.conversation||content.extendedTextMessage?.text||'').trim().toLowerCase(),gameKey=`${jid}:${m.key.participant||jid}`
  if(text==='/ping'||text==='/test'){await sock.sendMessage(jid,{text:'Pong 🏓'},{quoted:m});return}
  if(text==='/dbping'){await sock.sendMessage(jid,{text:`Database test ✅\nSupabase query: ${await pingDatabase()} ms`},{quoted:m});return}
  if(text==='/image'){const image=await fs.readFile(TEST_IMAGE_PATH);await sock.sendMessage(jid,{image,caption:'Bundled image test'},{quoted:m});return}
  if(text==='/api'){const r=await fetch(API_IMAGE_URL,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(`Image API HTTP ${r.status}`);await sock.sendMessage(jid,{image:Buffer.from(await r.arrayBuffer()),caption:'External API image test'},{quoted:m});return}
  if(text==='/mines'){this.minesGames.set(gameKey,{mine:Math.random()<.5?'mines_a1':'mines_b2',opened:new Set()});await this.sendMinesButtons(sock,jid)}
 }
 async handleAutoReply(sock,m,content,type){const jid=m.key.remoteJid,id=m.key.id,text=String(content.conversation||content.extendedTextMessage?.text||content.imageMessage?.caption||content.videoMessage?.caption||'').trim();if(!text)return;this.seen.set(id,Date.now());if(this.seen.size>2000)this.seen.clear();const fromMe=!!m.key.fromMe,command=text.match(/^\/ai\s+(on|off)$/i);if(fromMe){if(!command)return;const ownIds=new Set([sock.user?.id,sock.user?.lid,sock.user?.phoneNumber].filter(Boolean).map(actorIdFromJid)),isOwn=!jid.endsWith('@g.us')&&ownIds.has(actorIdFromJid(jid)),turnOn=command[1].toLowerCase()==='on';if(isOwn){await this.updateConfig({enabled:turnOn});await sock.sendMessage(jid,{text:`Boy Alone is ${turnOn?'on':'off'} globally.`});return}const muted=new Set(this.config.mutedChats||[]);if(turnOn)muted.delete(jid);else muted.add(jid);await this.updateConfig({mutedChats:[...muted]});await sock.sendMessage(jid,{text:`Boy Alone is ${turnOn?'on':'off'} in this chat.`});return}if(!['notify','append'].includes(type)||this.paused||!this.config.enabled||(this.config.mutedChats||[]).includes(jid))return;const group=jid.endsWith('@g.us');if(group){if(this.config.groupMode==='off')return;if(this.config.groupMode==='mentions'){const ctx=content.extendedTextMessage?.contextInfo||content.imageMessage?.contextInfo||content.videoMessage?.contextInfo||{},botIds=new Set([sock.user?.id,sock.user?.lid,sock.user?.phoneNumber].filter(Boolean).map(actorIdFromJid)),mentioned=(ctx.mentionedJid||[]).some(x=>botIds.has(actorIdFromJid(x))),quoted=[ctx.participant,ctx.participantAlt].filter(Boolean).some(x=>botIds.has(actorIdFromJid(x))),named=new RegExp(`\\b${escapeRegex(this.config.personaName)}\\b`,'i').test(text);if(!mentioned&&!quoted&&!named)return}}const now=Date.now(),cooldown=this.config.replyCooldownSec*1000;if(now-(this.lastAutoReply.get(jid)||0)<cooldown)return;this.lastAutoReply.set(jid,now);this.lastMessageAt=new Date().toISOString();this.messagesHandled++;const user=await resolveMessageUserId(sock,m)||actorId(m),name=m.pushName||'friend';try{const reply=await ai.chat({jid:`${this.sessionId}:${jid}`,userId:`${this.sessionId}:${user}`,name,text,mode:'autoreply',personaName:this.config.personaName,personaPrompt:this.config.personaPrompt});if(reply)await sock.sendMessage(jid,{text:reply},{quoted:m})}catch(e){if(!['LILY_SILENT','LILY_BUSY'].includes(e.code))this.log.warn({err:e,jid},'Boy Alone reply failed')}}
 async sendNativeButtons(sock,jid,body,footer,defs,ownerId=null){const {proto,generateWAMessageFromContent}=this.baileys,buttons=defs.map(([label,id])=>{const scoped=ownerId&&['rpg_','duel_'].some(p=>String(id).startsWith(p))?`${id}~u:${ownerId}`:id;return{name:'quick_reply',buttonParamsJson:JSON.stringify({display_text:label,id:scoped})}}),g=generateWAMessageFromContent(jid,{viewOnceMessage:{message:{messageContextInfo:{deviceListMetadata:{},deviceListMetadataVersion:2},interactiveMessage:proto.Message.InteractiveMessage.create({body:proto.Message.InteractiveMessage.Body.create({text:body}),footer:proto.Message.InteractiveMessage.Footer.create({text:footer}),nativeFlowMessage:proto.Message.InteractiveMessage.NativeFlowMessage.create({buttons})})}}},{});await this.outputGuard.run(jid,()=>sock.relayMessage(jid,g.message,relayOptions(g.key.id)))}
 async sendUrlButton(sock,jid,body,footer,label,url,quoted=null){const {proto,generateWAMessageFromContent}=this.baileys,buttons=[{name:'cta_url',buttonParamsJson:JSON.stringify({display_text:label,url,merchant_url:url})}],g=generateWAMessageFromContent(jid,{viewOnceMessage:{message:{messageContextInfo:{deviceListMetadata:{},deviceListMetadataVersion:2},interactiveMessage:proto.Message.InteractiveMessage.create({body:proto.Message.InteractiveMessage.Body.create({text:body}),footer:proto.Message.InteractiveMessage.Footer.create({text:footer}),nativeFlowMessage:proto.Message.InteractiveMessage.NativeFlowMessage.create({buttons})})}}},quoted?{quoted}:{});await this.outputGuard.run(jid,()=>sock.relayMessage(jid,g.message,relayOptions(g.key.id)))}
 async sendMinesButtons(sock,jid){await this.sendNativeButtons(sock,jid,'💣 *MINES BUTTON TEST*','JTF × RYUDEN',[['💎 Open A1','mines_a1'],['💎 Open B2','mines_b2'],['💰 Cash Out','mines_cashout']])}
 async reportAiIncident(sock,event){this.incidents.unshift({type:event.type||'unknown',at:event.recoveredAt||event.startedAt||new Date().toISOString(),status:event.status||event.code||null,message:String(event.message||'').slice(0,500),model:event.model||null,retryAt:event.retryAt||null,durationSeconds:event.durationSeconds||null,attempts:(event.attempts||[]).slice(0,8).map(x=>({model:x.model,status:x.status||x.code||null,message:String(x.message||'').slice(0,220)}))});this.incidents=this.incidents.slice(0,50);logger.warn({aiIncident:event},event.type==='recovery'?'Lily AI provider recovered':'Lily AI provider failure');const owner=`${ORIGINAL_OWNER}@s.whatsapp.net`;if(event.type==='recovery'){await sock.sendMessage(owner,{text:`✅ *LILY RECOVERED*\n\nShe is responding normally again.\nModel: ${event.model||'unknown'}\nDowntime: ${event.durationSeconds||'?'}s`}).catch(e=>logger.warn({err:e},'Owner recovery alert failed'));return}const attempts=(event.attempts||[]).map(x=>`• ${x.model}: ${x.status||x.code||'network'} — ${x.message}`).join('\n'),text=`⚠️ *LILY BACKEND FAILURE*\n\nStatus: ${event.status||event.code||'network error'}\nReason: ${event.message||'Unknown provider failure'}\nRetry after: ${event.retryAt||'automatic'}${attempts?`\n\nAttempts:\n${attempts}`:''}`;await sock.sendMessage(owner,{text:text.slice(0,3500)}).catch(e=>logger.warn({err:e},'Owner failure alert failed'))}
 async handleMinesButton(sock,m,k,id){const g=this.minesGames.get(k),jid=m.key.remoteJid;if(!g){await sock.sendMessage(jid,{text:'Session expired. Send /mines again.'},{quoted:m});return}if(id==='mines_cashout'){this.minesGames.delete(k);await sock.sendMessage(jid,{text:'💰 Cashed out!'},{quoted:m});return}if(id===g.mine){this.minesGames.delete(k);await sock.sendMessage(jid,{text:'💥 BOOM!'},{quoted:m});return}g.opened.add(id);await sock.sendMessage(jid,{text:'💎 SAFE TILE!'},{quoted:m})}
 async stop(){this.buttonTracker?.dispose();this.stopping=true;this.generation++;try{this.sock?.end(undefined)}catch{}this.sock=null}
}
class WhatsAppSessionManager{
 constructor(){this.connections=new Map();this.primaryId=process.env.WA_SESSION_ID||'rimuru-wa-test';this.maxSessions=Math.max(1,Math.min(20,Number(process.env.WA_MAX_SESSIONS)||5))}
 async start(){await accountConfig.ensure();const saved=await listAuthSessions(),ids=[...new Set([this.primaryId,...saved])];for(const id of ids){const c=new WhatsAppConnection(id,id===this.primaryId);this.connections.set(id,c);await c.start().catch(e=>logger.error({err:e,waSession:id},'WhatsApp session failed to start'))}}
 list(){return[...this.connections.values()].map(c=>c.status())}
 status(){const all=this.list(),primary=all.find(x=>x.sessionId===this.primaryId)||all[0]||null;return{primary,accounts:all,connected:all.filter(x=>x.state==='connected').length,total:all.length}}
 get(id){return this.connections.get(String(id||this.primaryId))}
 async pair(phone,label=''){if(this.connections.size>=this.maxSessions)throw Object.assign(Error(`Maximum ${this.maxSessions} WhatsApp accounts reached`),{status:409});const clean=String(label||'').toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-|-$/g,'').slice(0,30),id=`wa-${clean||Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`,c=new WhatsAppConnection(id,false);this.connections.set(id,c);try{await accountConfig.save(id,{label:String(label||'Boy Alone'),mode:'autoreply'},false);await c.start();const code=await c.requestPairingCode(phone);return{id,code}}catch(e){this.connections.delete(id);await c.stop().catch(()=>{});await clearAuthState(id).catch(()=>{});await accountConfig.remove(id).catch(()=>{});throw e}}
 async reconnect(id){const c=this.get(id);if(!c)throw Object.assign(Error('WhatsApp account not found'),{status:404});await c.reconnect()}
 setPaused(id,value){const c=this.get(id);if(!c)throw Object.assign(Error('WhatsApp account not found'),{status:404});c.setPaused(value);return c.status()}
 async remove(id){id=String(id||'');const c=this.connections.get(id);if(!c)throw Object.assign(Error('WhatsApp account not found'),{status:404});if(id===this.primaryId)throw Object.assign(Error('The primary Lily account cannot be removed here'),{status:409});await c.stop();await clearAuthState(id);await accountConfig.remove(id);this.connections.delete(id);return true}
 boy(){return[...this.connections.values()].find(c=>c.config?.mode==='autoreply')||null}
 async updateBoy(patch){const c=this.boy();if(!c)throw Object.assign(Error('Pair the Boy Alone WhatsApp account first'),{status:404});return c.updateConfig(patch)}
 incidents(){return[...this.connections.values()].flatMap(c=>c.incidentHistory().map(x=>({...x,sessionId:c.sessionId}))).sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,50)}
 async stop(){await Promise.allSettled([...this.connections.values()].map(c=>c.stop()))}
}
const sessions=new WhatsAppSessionManager(),lease=createInstanceLease({database,logger}),dashboard=createDashboard({sessions,database,lease,logger}),healthServer=http.createServer((q,r)=>{void (async()=>{if(await dashboard.handle(q,r))return;if(q.url==='/'||q.url==='/health'){r.writeHead(200,{'content-type':'application/json'});r.end(JSON.stringify({ok:true,instance:lease.status(),whatsapp:sessions.status()}));return}r.writeHead(404).end()})().catch(e=>{logger.error({err:e},'HTTP request failed');if(!r.headersSent)r.writeHead(500,{'content-type':'application/json'});r.end(JSON.stringify({ok:false,error:'Internal server error'}))})})
async function main(){healthServer.listen(port,'0.0.0.0',()=>logger.info({port},'health server listening'));await economy.ensureSchema();logger.info('Economy schema ready');const acquired=await lease.acquire(async()=>{await sessions.stop()});if(!acquired)return;await sessions.start();logger.info({accounts:sessions.list().length},'Website control and WhatsApp sessions started')}
async function shutdown(signal){logger.info({signal},'shutting down');await sessions.stop();await lease.release();healthServer.close();await closeAuthStore();process.exit(0)}
process.on('SIGTERM',()=>void shutdown('SIGTERM'));process.on('SIGINT',()=>void shutdown('SIGINT'));process.on('unhandledRejection',e=>logger.error({err:e},'unhandled rejection'));main().catch(e=>{logger.fatal({err:e},'startup failed');process.exit(1)})
