'use strict'
const http=require('http'),fs=require('fs/promises'),path=require('path'),pino=require('pino')
const {createAuthState,clearAuthState,closeAuthStore,pingDatabase,database}=require('./auth-store')
const {createTelegramControl}=require('./telegram-control')
const {buildEnterMessage,relayOptions,createTracker}=require('./button-test')
const {createEconomyStore}=require('./economy-store'),{createEconomyRouter}=require('./economy-router'),{createCasino}=require('./casino'),{createUi}=require('./ui')
const {resolveButtonId,isKnownButtonInteraction,isReplyTrigger,shouldHandleUpsert,ReplyRateLimiter}=require('./message-guard')
const logger=pino({level:process.env.LOG_LEVEL||'info'}),port=Number(process.env.PORT||3000),TEST_IMAGE_PATH=path.join(__dirname,'..','assets','speed-test.jpg'),MENU_IMAGE_PATH=path.join(__dirname,'..','assets','ryuden-menu.jpg'),API_IMAGE_URL=process.env.TEST_IMAGE_URL||'https://picsum.photos/900/1200.jpg'
const economy=createEconomyStore({database,logger}),routeEconomy=createEconomyRouter({economy,logger}),casino=createCasino({economy});let ui=null
class WhatsAppConnection{
 constructor(){this.sock=null;this.baileys=null;this.state='starting';this.registered=false;this.storage='unknown';this.connectedAt=null;this.generation=0;this.reconnectAttempt=0;this.pairingReady=false;this.pairingInFlight=false;this.stopping=false;this.seen=new Map();this.minesGames=new Map();this.replyLimiter=new ReplyRateLimiter()}
 status(){return{state:this.state,registered:this.registered,storage:this.storage,uptimeSec:this.connectedAt?Math.floor((Date.now()-this.connectedAt)/1000):0}}
 async start(){if(!this.baileys)this.baileys=await import('@whiskeysockets/baileys');await this.connect()}
 async connect(){if(this.stopping)return;const b=this.baileys,{state,saveCreds,storage}=await createAuthState(b);this.registered=!!state.creds.registered;this.storage=storage;this.state=this.registered?'connecting':'waiting-for-pair';this.pairingReady=false;const g=++this.generation,{version}=await b.fetchLatestBaileysVersion(),sock=b.default({version,auth:{creds:state.creds,keys:b.makeCacheableSignalKeyStore(state.keys,logger)},browser:b.Browsers.ubuntu('Chrome'),printQRInTerminal:false,markOnlineOnConnect:false,syncFullHistory:false,generateHighQualityLinkPreview:false,defaultQueryTimeoutMs:60000,logger:logger.child({module:'baileys'})});this.sock=sock;this.buttonTracker?.dispose();this.buttonTracker=createTracker(sock,logger);sock.ev.on('creds.update',async()=>{await saveCreds();this.registered=!!state.creds.registered});sock.ev.on('messages.upsert',({messages,type})=>{if(!['notify','append'].includes(type))return;for(const m of messages)void this.handleMessage(sock,m,type).catch(async e=>{logger.error({err:e,jid:m?.key?.remoteJid},'WhatsApp command failed');if(m?.key?.remoteJid)await sock.sendMessage(m.key.remoteJid,{text:`Command failed: ${e.message}`},{quoted:m}).catch(()=>{})})});sock.ev.on('connection.update',({connection,lastDisconnect,qr})=>{if(this.generation!==g||this.sock!==sock)return;if(qr)this.pairingReady=true;if(connection==='open'){this.state='connected';this.connectedAt=Date.now();this.reconnectAttempt=0;this.pairingReady=true;logger.info('WhatsApp connected')}if(connection==='close')void this.onClose(sock,g,lastDisconnect)});logger.info({storage,registered:this.registered},'WhatsApp socket started')}
 async onClose(sock,g,d){if(this.generation!==g||this.sock!==sock)return;this.buttonTracker?.dispose();const code=d?.error?.output?.statusCode;this.sock=null;this.state=code===401?'logged-out':'disconnected';if(this.stopping||code===401||code===429)return;this.reconnectAttempt++;setTimeout(()=>{if(!this.stopping&&!this.sock&&this.generation===g)void this.connect()},Math.min(30000,2000*(2**Math.min(this.reconnectAttempt,4))))}
 async waitForPairingReady(g,t=20000){const st=Date.now();while(Date.now()-st<t){if(g!==this.generation)throw Error('WhatsApp socket restarted; run /pair again');if(this.sock&&this.pairingReady)return;await new Promise(r=>setTimeout(r,150))}throw Error('WhatsApp did not become pairing-ready')}
 async requestPairingCode(raw){if(this.pairingInFlight)throw Error('A pairing request is already running');const phone=String(raw).replace(/\D/g,'').replace(/^0+/,'');if(!/^\d{8,15}$/.test(phone))throw Error('Use international format');this.pairingInFlight=true;try{await this.resetSocket(true);await this.waitForPairingReady(this.generation);this.state='pairing';return await this.sock.requestPairingCode(phone)}finally{this.pairingInFlight=false}}
 async resetSocket(clear){this.buttonTracker?.dispose();this.generation++;const old=this.sock;this.sock=null;try{old?.end(undefined)}catch{}if(clear)await clearAuthState();this.reconnectAttempt=0;await this.connect()}
 async reconnect(){await this.resetSocket(false)}
 async handleMessage(sock,m,type='notify'){const jid=m?.key?.remoteJid,id=m?.key?.id;if(!jid||!id||jid==='status@broadcast'||this.seen.has(id))return;const content=this.baileys.normalizeMessageContent(m.message)||{},button=resolveButtonId(content),known=isKnownButtonInteraction(content);if(!shouldHandleUpsert(content,{fromMe:!!m.key.fromMe,type}))return;this.seen.set(id,Date.now());if(this.seen.size>2000)this.seen.clear();if(known)logger.info({jid,id,type,fromMe:!!m.key.fromMe,button,types:Object.keys(content)},'Rimuru button tap accepted');if(isReplyTrigger(content)){const x=this.replyLimiter.check(m);if(!x.allowed){if(x.warn)await sock.sendMessage(jid,{text:`⚠️ *Slow down.*\n\nRimuru will stay silent for about *${Math.ceil(x.durationMs/1000)} seconds*.`},{quoted:m});return}}
  if(!ui)ui=createUi({economy,casino,logger,sendButtons:(s,j,b,f,d)=>this.sendNativeButtons(s,j,b,f,d)})
  if(button){if(['menu_','casino_','start_','rpg_'].some(p=>button.startsWith(p))){await ui.section(sock,m,button);return}if(button==='ryuden_enter'){await ui.menu(sock,m);return}if(button.startsWith('mines_')){await this.handleMinesButton(sock,m,`${jid}:${m.key.participant||jid}`,button);return}}
  if(await ui.route(sock,m,content))return;if(await routeEconomy(sock,m,content))return;if(await ui.maybeAi?.(sock,m,content))return
  const text=String(content.conversation||content.extendedTextMessage?.text||'').trim().toLowerCase(),gameKey=`${jid}:${m.key.participant||jid}`
  if(text==='/ping'||text==='/test'){await sock.sendMessage(jid,{text:'Pong 🏓'},{quoted:m});return}
  if(text==='/dbping'){await sock.sendMessage(jid,{text:`Database test ✅\nSupabase query: ${await pingDatabase()} ms`},{quoted:m});return}
  if(text==='/image'){const image=await fs.readFile(TEST_IMAGE_PATH);await sock.sendMessage(jid,{image,caption:'Bundled image test'},{quoted:m});return}
  if(text==='/api'){const r=await fetch(API_IMAGE_URL,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(`Image API HTTP ${r.status}`);await sock.sendMessage(jid,{image:Buffer.from(await r.arrayBuffer()),caption:'External API image test'},{quoted:m});return}
  if(text==='/mines'){this.minesGames.set(gameKey,{mine:Math.random()<.5?'mines_a1':'mines_b2',opened:new Set()});await this.sendMinesButtons(sock,jid)}
 }
 async sendNativeButtons(sock,jid,body,footer,defs){const {proto,generateWAMessageFromContent}=this.baileys,buttons=defs.map(([label,id])=>({name:'quick_reply',buttonParamsJson:JSON.stringify({display_text:label,id})})),g=generateWAMessageFromContent(jid,{viewOnceMessage:{message:{messageContextInfo:{deviceListMetadata:{},deviceListMetadataVersion:2},interactiveMessage:proto.Message.InteractiveMessage.create({body:proto.Message.InteractiveMessage.Body.create({text:body}),footer:proto.Message.InteractiveMessage.Footer.create({text:footer}),nativeFlowMessage:proto.Message.InteractiveMessage.NativeFlowMessage.create({buttons})})}}},{});await sock.relayMessage(jid,g.message,relayOptions(g.key.id))}
 async sendMinesButtons(sock,jid){await this.sendNativeButtons(sock,jid,'💣 *MINES BUTTON TEST*','JTF × RYUDEN',[['💎 Open A1','mines_a1'],['💎 Open B2','mines_b2'],['💰 Cash Out','mines_cashout']])}
 async handleMinesButton(sock,m,k,id){const g=this.minesGames.get(k),jid=m.key.remoteJid;if(!g){await sock.sendMessage(jid,{text:'Session expired. Send /mines again.'},{quoted:m});return}if(id==='mines_cashout'){this.minesGames.delete(k);await sock.sendMessage(jid,{text:'💰 Cashed out!'},{quoted:m});return}if(id===g.mine){this.minesGames.delete(k);await sock.sendMessage(jid,{text:'💥 BOOM!'},{quoted:m});return}g.opened.add(id);await sock.sendMessage(jid,{text:'💎 SAFE TILE!'},{quoted:m})}
 async stop(){this.buttonTracker?.dispose();this.stopping=true;this.generation++;try{this.sock?.end(undefined)}catch{}this.sock=null}
}
const connection=new WhatsAppConnection(),telegram=createTelegramControl({connection,logger}),healthServer=http.createServer((q,r)=>{if(q.url==='/'||q.url==='/health'){r.writeHead(200,{'content-type':'application/json'});r.end(JSON.stringify({ok:true,whatsapp:connection.status()}));return}r.writeHead(404).end()})
async function main(){healthServer.listen(port,'0.0.0.0',()=>logger.info({port},'health server listening'));await economy.ensureSchema();logger.info('Economy schema ready');await connection.start();await telegram.start();logger.info('Telegram controller started')}
async function shutdown(signal){logger.info({signal},'shutting down');telegram.stop();await connection.stop();healthServer.close();await closeAuthStore();process.exit(0)}
process.on('SIGTERM',()=>void shutdown('SIGTERM'));process.on('SIGINT',()=>void shutdown('SIGINT'));process.on('unhandledRejection',e=>logger.error({err:e},'unhandled rejection'));main().catch(e=>{logger.fatal({err:e},'startup failed');process.exit(1)})
