'use strict'
const fs=require('fs/promises'),path=require('path'),casinoPolish=require('./casino-polish'),balanceUp=require('./rpg-balance-upgrade'),zones=require('./zone-router'),baseUi=require('./ui'),{createRpg}=require('./rpg'),{createRpgUpgrade}=require('./rpg-upgrade'),{createCards}=require('./cards'),{createMusic}=require('./music'),{createDuels}=require('./duels'),{database}=require('./auth-store'),{isOwner}=require('./access'),{canonicalUserId,displayName,commandParts}=require('./economy-router'),ai=require('./ai-v2')
const LILY_IMAGE=path.join(__dirname,'..','assets','lily-menu.jpg')
balanceUp.install()
function createUi(opts){casinoPolish.install(opts.casino);const base=baseUi.createUi(opts),rpg=createRpg({economy:opts.economy,logger:opts.logger,sendButtons:opts.sendButtons}),up=createRpgUpgrade({base:rpg,economy:opts.economy,sendButtons:opts.sendButtons}),cards=createCards({logger:opts.logger}),music=createMusic({logger:opts.logger}),duels=createDuels({sendButtons:opts.sendButtons}),masters=new Set(),aiDisabled=new Set(),send=(s,j,m,t)=>s.sendMessage(j,{text:t},{quoted:m}),P=m=>({id:canonicalUserId(m.key),name:displayName(m),jid:m.key.remoteJid});let globalAi=true
 async function battleOrigin(id){const d=database();if(!d)return null;try{const r=await d.query('SELECT active_battle FROM rimuru_rpg_players WHERE user_id=$1',[id]),b=r.rows[0]?.active_battle;return b?.origin||(b?.storyBoss?'story':b?'standalone_combat':null)}catch{return null}}
 async function menu(s,m){return opts.sendButtons(s,m.key.remoteJid,'🌸 *LILY • RYUDEN*\n\nChoose a section below. Only systems currently online are shown.','JTF × RYUDEN',[['🎰 Casino','menu_casino'],['💰 Balance','menu_balance'],['🏆 Leaderboards','menu_leaderboard'],['🎮 Games','menu_games'],['🛠️ Utilities','menu_utilities'],['❓ Help','menu_help']])}
 async function city(s,m){return opts.sendButtons(s,m.key.remoteJid,'🏰 *ODYSSEY CITY — RYUDEN*\n\nViolet lanterns glow over the tavern while adventurers crowd the Quest Board. The guild quarter, training grounds and East Gate are open.\n\nWhere are you heading?','LILY • ODYSSEY CITY',[['📜 Quest Board','rpg_missions'],['🗺️ East Gate','rpg_explore'],['🥋 Training Grounds','rpg_train'],['🧙 Master Hall','rpg_master'],['🏰 Guild Quarter','rpg_guild'],['⚔️ RPG Profile','rpg_home']])}
 async function casino(s,m){return opts.sendButtons(s,m.key.remoteJid,'🎰 *LILY CASINO*\n\n🎰 /slots [amount]\n🪙 /cf [heads|tails] [amount]\n🎲 /dice [1-6] [amount]\n🎡 /roulette [bet] [amount]','LILY • JTF × RYUDEN',[['🎰 Slots','casino_slots_help'],['🪙 Coin Flip','casino_cf_help'],['🎲 Dice','casino_dice_help'],['🎡 Roulette','casino_roulette_help'],['⬅️ Menu','menu_main']])}
 async function balance(s,m){const p=P(m),u=await opts.economy.getBalance(p.id,p.name);return send(s,p.jid,m,`💰 *LILY • BALANCE*\n\n> 👤 *${u.displayName||p.name||'Player'}*\n\n👛 Wallet: *${opts.economy.fmt(u.wallet)}*\n🏦 Bank: *${opts.economy.fmt(u.bank)}*\n💎 Net Worth: *${opts.economy.fmt(u.wallet+u.bank)}*`)}
 async function route(s,m,content){const c=commandParts(content),p=P(m)
  if(c?.command==='/start'){const r=await opts.economy.register(p.id,p.name),n=p.name||r.user.displayName||'mortal',image=await fs.readFile(LILY_IMAGE);await s.sendMessage(p.jid,{image,caption:r.isNew?`🌸 *WELCOME TO RYUDEN, ${n.toUpperCase()}!*\n\nI'm *Lily* — Rimuru's distant sister and Ryuden's resident troublemaker. Your account is ready.\n💰 Starting coins: *${opts.economy.fmt(r.user.wallet)}*`:`🌸 *WELCOME BACK, ${n.toUpperCase()}!*\n\nLily remembered you. Your account and progress are ready.`},{quoted:m});await opts.sendButtons(s,p.jid,'✨ *WHERE TO NEXT?*','LILY • JTF × RYUDEN',[['⚔️ Enter Odyssey','start_rpg'],['🎰 Enter Casino','start_casino'],['📜 Main Menu','menu_main']]);return true}
  if(c?.command==='/menu')return menu(s,m),true
  if(c?.command==='/casino'){if(await zones.guard(s,m,'/casino'))return true;return casino(s,m),true}
  if(['/balance','/bal'].includes(c?.command))return balance(s,m),true
  if(c?.command==='/ai'){const x=String(c.args[0]||'').toLowerCase();if(x==='global'){if(!isOwner(p.id)){await send(s,p.jid,m,'⛔ Original Owner only.');return true}globalAi=String(c.args[1]||'on').toLowerCase()!=='off';await send(s,p.jid,m,`👑 Global Lily AI: *${globalAi?'ON':'OFF'}*`);return true}if(x==='off')aiDisabled.add(p.jid);else if(x==='on')aiDisabled.delete(p.jid);await send(s,p.jid,m,`🌸 *LILY AI: ${aiDisabled.has(p.jid)?'OFF':'ON'}*\n\nIn groups, say *Lily* or @mention me. Replying to one of my messages alone does not summon me.`);return true}
  if(c?.command==='/rpg'&&(await zones.zoneFor(p.jid))?.zone==='rpg')return city(s,m),true
  if(c?.command==='/help'){const page=Math.max(1,Math.min(5,Number(c.args[0]||1))),pages={1:'❓ *HELP 1/5 — CORE*\n\n/start • /menu • /p • /balance • /bank • /lb\n\nNext: /help 2',2:'❓ *HELP 2/5 — ECONOMY*\n\n/deposit • /withdraw • /donate • /transfer\n\nNext: /help 3',3:'❓ *HELP 3/5 — CASINO*\n\n/casino • /slots • /cf • /dice • /roulette\n_Casino zone only._\n\nNext: /help 4',4:'❓ *HELP 4/5 — ODYSSEY*\n\n/rpg • /masters • /explore • /train • /inventory • /guild\n/story • /missions • /npc • /shop • /combat\n\nNext: /help 5',5:'❓ *HELP 5/5 — DUELS, CARDS & MUSIC*\n\n/duel @player • /duels\n/cards • /collection • /cardinfo\n/play <song> • /zones'};await send(s,p.jid,m,pages[page]);return true}
  if(c&&['/slots','/cf','/coinflip','/dice','/roulette'].includes(c.command)){if(await zones.guard(s,m,c.command))return true;let r=null;if(c.command==='/slots')r=await opts.casino.slots(p.id,p.name,c.args[0]);if(['/cf','/coinflip'].includes(c.command))r=await opts.casino.coinflip(p.id,p.name,c.args[0],c.args[1]);if(c.command==='/dice')r=await opts.casino.dice(p.id,p.name,c.args[0],c.args[1]);if(c.command==='/roulette')r=await opts.casino.roulette(p.id,p.name,c.args);if(!r?.ok){await send(s,p.jid,m,r?.message||'Casino command failed.');return true}const payout=Number(r.payout||0),bet=Number(r.bet||0),net=payout-bet,outcome=net>0?'🎉 *WIN*':net<0?'❌ *LOSS*':'➖ *PUSH*',face=r.reels?r.reels.join(' | '):r.flip||r.rolled||r.number||'';await send(s,p.jid,m,`🎰 *CASINO RESULT*\n\n${face}\n\n${outcome}\n${net>=0?'💚 Gained':'🔻 Lost'}: *${opts.economy.fmt(Math.abs(net))}*\n💵 Bet: ${opts.economy.fmt(bet)}\n${payout?`💰 Payout: ${opts.economy.fmt(payout)}\n`:''}👛 Wallet: *${opts.economy.fmt(r.user.wallet)}*`);return true}
  if(c&&await zones.handle(s,m,c,p.id))return true
  if(c&&await balanceUp.admin(s,m,c))return true
  if(c&&await zones.guard(s,m,c.command))return true
  if(c&&await duels.route(s,m,c,content))return true
  const raw=String(content.conversation||content.extendedTextMessage?.text||'').trim().toLowerCase()
  if((raw.startsWith('!claim')||c&&['/cards','/collection','/card','/cardinfo','/spawncard'].includes(c.command))&&await zones.guardZone(s,m,'normal'))return true
  if(await cards.handle(s,m,content))return true
  if(await music.handle(s,m,content))return true
  if(c?.command==='/npc'){const npc=await rpg.npcContext(p.id),text=c.args.join(' ').trim();if(!npc){await send(s,p.jid,m,'🗺️ There is no active NPC in your current Story scene.');return true}if(!text){await send(s,p.jid,m,`Talk to ${npc.name} with */npc <message>*.`);return true}const a=await ai.chat({jid:p.jid,userId:p.id,name:p.name,text,mode:'npc',npc});await send(s,p.jid,m,`*${npc.name}:* ${a}`);return true}
  if(c){if(await up.route(s,m,c))return true;if(c.command==='/talk'){const r=await base.route(s,m,content);masters.add(p.id);return r}if(c.command==='/endtalk'){masters.delete(p.id);return base.route(s,m,content)}}return base.route(s,m,content)
 }
 async function section(s,m,x){const p=P(m),origin=(x==='rpg_combat'||x.startsWith('rpg_battle_'))?await battleOrigin(p.id):null;if(await zones.guardSection(s,m,x,origin))return true;if(await duels.section(s,m,x))return true;if(x==='menu_main')return menu(s,m);if(['start_casino','menu_casino'].includes(x))return casino(s,m);if(x==='menu_balance')return balance(s,m);if(x==='menu_games')return send(s,p.jid,m,'🎮 *GAMES*\n\n🎰 /casino — Casino zone\n⚔️ /combat — Combat zone\n🥊 /duel @player — Duels zone\n📖 /story — Normal zone\n🏰 /rpg — Odyssey profile and city');if(x==='menu_help')return send(s,p.jid,m,'❓ Use */help 1* for the command pages.');if(await up.section(s,m,x))return true;const r=await base.section(s,m,x);if(x==='rpg_talk_master')masters.add(p.id);return r}
 async function maybeAi(s,m,content){const p=P(m),text=String(content.conversation||content.extendedTextMessage?.text||'').trim();if(!globalAi||aiDisabled.has(p.jid)||!text||text.startsWith('/')||text.startsWith('!claim')||m.key.fromMe)return false;const master=masters.has(p.id),group=p.jid.endsWith('@g.us'),ctx=content.extendedTextMessage?.contextInfo||{},botIds=new Set([s.user?.id,s.user?.lid,s.user?.phoneNumber].filter(Boolean).map(x=>String(x).split(':')[0].split('@')[0])),mentioned=(ctx.mentionedJid||[]).some(x=>botIds.has(String(x).split(':')[0].split('@')[0])),saysLily=/\blily\b/i.test(text)
  if(!master&&group&&!saysLily&&!mentioned)return false
  const player=master?await rpg.getPlayer(p.id):null,mode=master?'master':'lily',a=await ai.chat({jid:p.jid,userId:p.id,name:p.name,text,mode,player});if(master)await rpg.recordMasterChat(p.id);await send(s,p.jid,m,master?`*${player.currentMaster}:* ${a}`:`🌸 *Lily:* ${a}`);return true
 }
 return{...base,route,section,maybeAi,menu}}
module.exports={createUi}
