'use strict'
const fs=require('fs/promises'),path=require('path'),{canonicalUserId,displayName,commandParts}=require('./economy-router'),{createRpg}=require('./rpg'),{isOwner}=require('./access'),ai=require('./ai')
const START_IMAGE_PATH=path.join(__dirname,'..','assets','ryuden-menu.jpg')
const BUTTONS={main:[['🎰 Casino','menu_casino'],['💰 Balance','menu_balance'],['🏆 Leaderboards','menu_leaderboard'],['🎮 Games','menu_games'],['🛠️ Utilities','menu_utilities'],['❓ Help','menu_help']],casino:[['🎰 Slots','casino_slots_help'],['🪙 Coin Flip','casino_cf_help'],['🎲 Dice','casino_dice_help'],['🎡 Roulette','casino_roulette_help'],['⬅️ Menu','menu_main']]}
function createUi({economy,casino,sendButtons,logger}){const send=(s,j,m,t)=>s.sendMessage(j,{text:t},{quoted:m}),P=m=>({id:canonicalUserId(m.key),name:displayName(m),jid:m.key.remoteJid}),rpg=createRpg({economy,logger,sendButtons}),aiChats=new Map(),masterChats=new Set();let globalAi=true
 async function gate(s,m,c){if(c.command==='/start')return false;const p=P(m),u=await economy.findUser(p.id);if(u?.registeredAt)return false;await send(s,p.jid,m,'🌊 *YOU HAVEN’T ENTERED RYUDEN YET*\n\nUse */start* to register before using Rimuru.');return true}
 async function aiCommand(s,m,c){const p=P(m),x=String(c.args[0]||'').toLowerCase();if(x==='global'){if(!isOwner(p.id))return send(s,p.jid,m,'⛔ Original Owner only.'),true;const v=String(c.args[1]||'').toLowerCase();globalAi=v!=='off';await send(s,p.jid,m,`👑 Global AI: *${globalAi?'ON':'OFF'}*`);return true}if(x==='on'){aiChats.set(p.jid,true);await send(s,p.jid,m,'🤖 *RIMURU AI: ON*\n\nDM normally. In groups, mention Rimuru or reply to him.');return true}if(x==='off'){aiChats.delete(p.jid);masterChats.delete(p.id);await send(s,p.jid,m,'🌙 *RIMURU AI: OFF*');return true}await send(s,p.jid,m,`🤖 Personal AI: *${aiChats.get(p.jid)?'ON':'OFF'}*\n🌐 Global AI: *${globalAi?'ON':'OFF'}*\nModel: *${ai.model}*`);return true}
 async function startMasterTalk(s,m){const p=P(m),player=await rpg.getPlayer(p.id);if(!player?.currentMaster)return send(s,p.jid,m,'🧙 Choose a Master first.'),true;masterChats.add(p.id);aiChats.set(p.jid,true);await send(s,p.jid,m,`💬 *MASTER LINK OPEN*\n\n> 🧙 *${player.currentMaster}*\n❤️ Bond: *${player.bondPoints}*\n\nChat normally. Meaningful conversation can slowly raise Bond. */endtalk* returns to Rimuru.`);return true}
 async function maybeAi(s,m,content){const p=P(m),text=String(content.conversation||content.extendedTextMessage?.text||'').trim();if(!globalAi||!text||text.startsWith('/')||m.key.fromMe)return false;const npc=await rpg.npcContext(p.id),master=masterChats.has(p.id);if(!aiChats.get(p.jid)&&!npc&&!master)return false;const group=p.jid.endsWith('@g.us'),ctx=content.extendedTextMessage?.contextInfo||{};if(group&&!ctx.quotedMessage&&!/\brimuru\b/i.test(text)&&!master&&!npc)return false;const player=master?await rpg.getPlayer(p.id):null,mode=master?'master':npc?'npc':'rimuru';try{const a=await ai.chat({jid:p.jid,userId:p.id,name:p.name,text,mode,player,npc});if(master)await rpg.recordMasterChat(p.id);await send(s,p.jid,m,mode==='npc'?`*${npc.name}:* ${a}`:mode==='master'?`*${player.currentMaster}:* ${a}`:a);return true}catch(e){logger.warn({err:e},'Groq AI failed');return false}}
 async function balance(s,m){const p=P(m),u=await economy.getBalance(p.id,p.name);return send(s,p.jid,m,`💰 *RIMURU • BALANCE*\n\n> 👤 *${u.displayName||p.name||'Player'}*\n\n👛 Wallet: *${economy.fmt(u.wallet)}*\n🏦 Bank: *${economy.fmt(u.bank)}*\n💎 Net Worth: *${economy.fmt(u.wallet+u.bank)}*`)}
 async function wealthLeaderboard(s,m){const rows=await economy.leaderboard(10),med=['🥇','🥈','🥉'];return send(s,m.key.remoteJid,m,`💎 *RYUDEN WEALTH LEADERBOARD*\n\n${rows.map((u,i)=>`${med[i]||`${i+1}.`} *${u.displayName||'Player'}*\n   💰 Net Worth: *${economy.fmt(u.netWorth)}*`).join('\n\n')||'No registered players yet.'}`)}
 async function leaderboards(s,m){return sendButtons(s,m.key.remoteJid,'🏆 *RYUDEN LEADERBOARDS*\n\nChoose what you want to rank.','JTF × RYUDEN',[['💎 Wealth','menu_lb_wealth'],['⚔️ Odyssey Rank','menu_lb_rpg'],['⬅️ Menu','menu_main']])}
 async function profile(s,m){const p=P(m),u=await economy.getBalance(p.id,p.name),wr=u.gamesPlayed?((u.gamesWon/u.gamesPlayed)*100).toFixed(1):'0.0';return send(s,p.jid,m,`👤 *RIMURU PROFILE*\n\n> *${u.displayName||p.name||'Player'}*\n💰 ${economy.fmt(u.wallet+u.bank)} net worth\n🎮 ${u.gamesPlayed} games • 🏆 ${u.gamesWon} wins • 📈 ${wr}%\n\n⚔️ */rpg* for Odyssey profile.`)}
 async function menu(s,m){return sendButtons(s,m.key.remoteJid,'🐉 *RIMURU • RYUDEN*\n\nChoose a section below.','JTF × RYUDEN',BUTTONS.main)}
 async function casinoPanel(s,m){return sendButtons(s,m.key.remoteJid,'🎰 *RIMURU CASINO*\n\n🎰 /slots [amount]\n🪙 /cf [heads|tails] [amount]\n🎲 /dice [1-6] [amount]\n🎡 /roulette [bet] [amount]','JTF × RYUDEN • CASINO',BUTTONS.casino)}
 async function ownerPanel(s,m){const p=P(m);if(!isOwner(p.id))return send(s,p.jid,m,'⛔ Original Owner only.');return sendButtons(s,p.jid,'👑 *RIMURU • ORIGINAL OWNER*\n\nFull authority recognized.\n\nEconomy mutation commands remain owner-locked. Global AI can only be changed here/by owner command.','JTF × RYUDEN • OWNER',[['🤖 Global AI ON','owner_ai_on'],['🌙 Global AI OFF','owner_ai_off'],['💰 Economy Help','owner_economy'],['⚔️ RPG Admin Help','owner_rpg'],['📜 Main Menu','menu_main']])}
 async function section(s,m,id){const fake={command:id==='menu_main'?'/menu':id==='menu_balance'?'/balance':id==='menu_leaderboard'?'/leaderboard':id==='menu_casino'?'/casino':id==='start_rpg'?'/rpg':id.startsWith('rpg_')?'/rpg':null};if(fake.command&&await gate(s,m,fake))return true;if(id==='start_rpg')return rpg.panel(s,m);if(id==='start_casino')return casinoPanel(s,m);if(id==='rpg_talk_master')return startMasterTalk(s,m);if(id.startsWith('rpg_')){const h=await rpg.section(s,m,id);if(h)return true}if(id==='menu_main')return menu(s,m);if(id==='menu_balance')return balance(s,m);if(id==='menu_leaderboard')return leaderboards(s,m);if(id==='menu_lb_wealth')return wealthLeaderboard(s,m);if(id==='menu_lb_rpg')return rpg.route(s,m,{command:'/rlb',args:[]});if(id==='menu_casino')return casinoPanel(s,m);if(id==='menu_games')return send(s,m.key.remoteJid,m,'🎮 *GAMES*\n\n🎰 /casino\n⚔️ /rpg\n🗺️ /explore\n⚔️ /combat\n🛒 /shop');if(id==='menu_utilities')return send(s,m.key.remoteJid,m,'🛠️ *UTILITIES*\n\n/p • /menu • /help 1 • /lb');if(id==='menu_help')return send(s,m.key.remoteJid,m,'❓ Use */help 1*.');if(id.startsWith('owner_')){const p=P(m);if(!isOwner(p.id))return send(s,p.jid,m,'⛔ Original Owner only.');if(id==='owner_ai_on'){globalAi=true;return send(s,p.jid,m,'🤖 Global AI enabled.')}if(id==='owner_ai_off'){globalAi=false;return send(s,p.jid,m,'🌙 Global AI disabled.')}if(id==='owner_economy')return send(s,p.jid,m,'💰 *OWNER ECONOMY*\n\nReply to a user:\n/addcoin [amount]\n/setbal [amount]');if(id==='owner_rpg')return send(s,p.jid,m,'⚔️ *RPG ADMIN*\n\nRPG mutation commands are reserved for the Original Owner as they are added. Regular users cannot access economy mutation commands.')}const x={casino_slots_help:'🎰 /slots 5000 — 2 matches 2×, 3 matches 4×',casino_cf_help:'🪙 /cf heads 5000 — correct call 2×',casino_dice_help:'🎲 /dice 5 2000 — exact number 6×',casino_roulette_help:'🎡 /roulette red 5000'};if(x[id])return send(s,m.key.remoteJid,m,x[id]);return false}
 async function route(s,m,content){const c=commandParts(content);if(!c)return false;const p=P(m);if(c.command==='/start'){const r=await economy.register(p.id,p.name),n=p.name||r.user.displayName||'mortal',image=await fs.readFile(START_IMAGE_PATH);await s.sendMessage(p.jid,{image,caption:r.isNew?`🌊 *WELCOME TO RYUDEN, ${n.toUpperCase()}!*\n\n> 👤 *${n}*\n\nYour account is registered.\n💰 Starting coins: *${economy.fmt(r.user.wallet)}*`:`🌊 *WELCOME BACK TO RYUDEN!*\n\n> 👤 *${n}*\n\nYour account and progress are ready.`},{quoted:m});await sendButtons(s,p.jid,'🐉 *CHOOSE YOUR PATH*','JTF × RYUDEN',[['⚔️ Enter Odyssey','start_rpg'],['🎰 Enter Casino','start_casino'],['📜 Main Menu','menu_main']]);return true}if(await gate(s,m,c))return true;if(c.command==='/ai')return aiCommand(s,m,c);if(c.command==='/talk')return startMasterTalk(s,m);if(c.command==='/endtalk'){masterChats.delete(p.id);await send(s,p.jid,m,'🌊 Master link closed. You’re talking to Rimuru again.');return true}if(c.command==='/owner'||c.command==='/ownerpanel'){await ownerPanel(s,m);return true}if(await rpg.route(s,m,c))return true;if(c.command==='/menu')return menu(s,m),true;if(['/lb','/leaderboard'].includes(c.command))return leaderboards(s,m),true;if(['/wealthlb','/wlb'].includes(c.command))return wealthLeaderboard(s,m),true;if(['/p','/profile'].includes(c.command))return profile(s,m),true;if(c.command==='/casino')return casinoPanel(s,m),true;if(c.command==='/games')return section(s,m,'menu_games'),true;if(c.command==='/utilities')return section(s,m,'menu_utilities'),true;if(c.command==='/help'){const pg=Number(c.args[0]||1),pages={1:'❓ *HELP 1/4 — CORE*\n\n/start • /menu • /p • /bal • /bank • /lb\n/wealthlb • /rlb\n\nNext: /help 2',2:'❓ *HELP 2/4 — ECONOMY*\n\n/dep • /wd • /donate • /transfer\n\nNext: /help 3',3:'❓ *HELP 3/4 — CASINO*\n\n/slots • /cf • /dice • /roulette\n\nNext: /help 4',4:'❓ *HELP 4/4 — ODYSSEY*\n\n/rpg • /masters • /explore • /combat\n/train • /skills • /shop • /story • /inventory\n/guild • /rlb'};await send(s,p.jid,m,pages[pg]||pages[1]);return true}let r=null;if(c.command==='/slots')r=await casino.slots(p.id,p.name,c.args[0]);if(['/cf','/coinflip'].includes(c.command))r=await casino.coinflip(p.id,p.name,c.args[0],c.args[1]);if(c.command==='/dice')r=await casino.dice(p.id,p.name,c.args[0],c.args[1]);if(c.command==='/roulette')r=await casino.roulette(p.id,p.name,c.args);if(!r)return false;if(!r.ok)return send(s,p.jid,m,r.message),true;await send(s,p.jid,m,`🎰 *CASINO RESULT*\n\n${r.reels?r.reels.join(' | '):r.flip||r.rolled||r.number}\n\n💵 Bet: ${economy.fmt(r.bet)}\n${r.payout?`💰 Payout: ${economy.fmt(r.payout)}\n`:''}👛 Wallet: *${economy.fmt(r.user.wallet)}*`);return true}
 return{route,section,menu,balance,leaderboard:leaderboards,profile,maybeAi}}
module.exports={createUi}
