'use strict'
const fs=require('fs/promises')
const path=require('path')
const {canonicalUserId,displayName,commandParts}=require('./economy-router')
const START_IMAGE_PATH=path.join(__dirname,'..','assets','ryuden-menu.jpg')
const BUTTONS={main:[['🎰 Casino','menu_casino'],['💰 Balance','menu_balance'],['🏆 Leaderboard','menu_leaderboard'],['🎮 Games','menu_games'],['🛠️ Utilities','menu_utilities'],['❓ Help','menu_help']],casino:[['🎰 Slots','casino_slots_help'],['🪙 Coin Flip','casino_cf_help'],['🎲 Dice','casino_dice_help'],['🎡 Roulette','casino_roulette_help'],['⬅️ Menu','menu_main']]}
function createUi({economy,casino,sendButtons,logger}){
 const send=(s,j,m,t)=>s.sendMessage(j,{text:t},{quoted:m}),P=m=>({id:canonicalUserId(m.key),name:displayName(m),jid:m.key.remoteJid})
 async function balance(s,m){const p=P(m),u=await economy.getBalance(p.id,p.name);return send(s,p.jid,m,`💰 *RIMURU • BALANCE*\n\n> 👤 *${u.displayName||p.name||'Player'}*\n\n👛 Wallet: *${economy.fmt(u.wallet)}*\n🏦 Bank: *${economy.fmt(u.bank)}*\n💎 Net Worth: *${economy.fmt(u.wallet+u.bank)}*\n\n🎮 Games: *${u.gamesPlayed}*\n🏆 Wins: *${u.gamesWon}* • 💀 Losses: *${u.gamesLost}*`)}
 async function profile(s,m){const p=P(m),u=await economy.getBalance(p.id,p.name),wr=u.gamesPlayed?((u.gamesWon/u.gamesPlayed)*100).toFixed(1):'0.0',reg=u.registeredAt?new Date(u.registeredAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}):'Legacy account';return send(s,p.jid,m,`╭━━〔 👤 *RIMURU PROFILE* 〕━━╮\n\n> 👤 *${u.displayName||p.name||'Player'}*\n\n💰 *ECONOMY*\n├─ 👛 Wallet: *${economy.fmt(u.wallet)}*\n├─ 🏦 Bank: *${economy.fmt(u.bank)}*\n└─ 💎 Net Worth: *${economy.fmt(u.wallet+u.bank)}*\n\n🎰 *CASINO RECORD*\n├─ 🎮 Played: *${u.gamesPlayed}*\n├─ 🏆 Won: *${u.gamesWon}*\n├─ 💀 Lost: *${u.gamesLost}*\n├─ 📈 Win Rate: *${wr}%*\n├─ 🎟️ Wagered: *${economy.fmt(u.wagered)}*\n└─ 💹 Casino Profit: *${u.casinoProfit>=0?'+':''}${economy.fmt(u.casinoProfit)}*\n\n📅 Registered: *${reg}*\n\n╰━━━━〔 *JTF • RYUDEN* 〕━━━━╯`)}
 async function leaderboard(s,m){const rows=await economy.leaderboard(10),med=['🥇','🥈','🥉'],body=rows.length?rows.map((u,i)=>`${med[i]||`🔹 ${i+1}.`} *${i<3?`${i+1}${i===0?'ST':i===1?'ND':'RD'} PLACE`:`#${i+1}`}*\n> 👤 *${u.displayName||'Player'}*\n└─ 💎 Net Worth: *${economy.fmt(u.netWorth)}*`).join('\n\n'):'> ⚠️ No registered players yet.';return send(s,m.key.remoteJid,m,`🏆 *RIMURU • LEADERBOARD* 🏆\n╭──────〔 *TOP 10* 〕──────╮\nTop elite magnates across Ryuden.\n╰────────────────────╯\n\n${body}\n\n💎 Rankings use *Wallet + Bank*.\n╰━━━━〔 *JTF • RYUDEN* 〕━━━━╯`)}
 async function menu(s,m){return sendButtons(s,m.key.remoteJid,'🐉 *RIMURU • RYUDEN*\n\nChoose a section below. Only systems currently online are shown.','JTF × RYUDEN',BUTTONS.main)}
 async function casinoPanel(s,m){return sendButtons(s,m.key.remoteJid,'🎰 *RIMURU CASINO*\n\n🎰 */slots [amount]*\n🪙 */cf [heads|tails] [amount]*\n🎲 */dice [1-6] [amount]*\n🎡 */roulette [bet] [amount]*\n\n> 🎩 Bets come from your wallet.\n\nTap a game for usage.','JTF × RYUDEN • CASINO',BUTTONS.casino)}
 async function games(s,m){return send(s,m.key.remoteJid,m,'🎮 *RIMURU • GAMES*\n\n🎰 */slots* — slot machine\n🪙 */cf* — coin flip\n🎲 */dice* — exact-number dice\n🎡 */roulette* — European roulette\n\n> More original Rimuru games will appear here as they are ported.')}
 async function utilities(s,m){return send(s,m.key.remoteJid,m,'🛠️ *RIMURU • UTILITIES*\n\n🏓 */ping* — connection speed\n🗄️ */dbping* — database speed\n👤 */p* — your profile\n📜 */menu* — main menu\n🌊 */start* — registration/status\n❓ */help 1* — help pages')}
 async function section(s,m,id){if(id==='menu_main')return menu(s,m);if(id==='menu_balance')return balance(s,m);if(id==='menu_leaderboard')return leaderboard(s,m);if(id==='menu_casino')return casinoPanel(s,m);if(id==='menu_games')return games(s,m);if(id==='menu_utilities')return utilities(s,m);if(id==='menu_help')return send(s,m.key.remoteJid,m,'❓ *RIMURU HELP*\n\nHelp is split into readable pages.\n\n> 📖 Use */help 1* to see Help Page 1.');const u={casino_slots_help:'🎰 *SLOTS*\n\n> Command: */slots 5000*\n\n2 matches = 2× • 3 matches = 4×',casino_cf_help:'🪙 *COIN FLIP*\n\n> Command: */cf heads 5000*\n\nCorrect call pays 2×.',casino_dice_help:'🎲 *DICE*\n\n> Command: */dice 5 2000*\n\nExact number pays 6×.',casino_roulette_help:'🎡 *ROULETTE*\n\n*/roulette red 5000*\n*/roulette even 5000*\n*/roulette high 5000*\n*/roulette straight 7 5000*'};if(u[id])return send(s,m.key.remoteJid,m,u[id]);return false}
 async function route(s,m,content){const c=commandParts(content);if(!c)return false;const p=P(m)
  if(c.command==='/start'){const r=await economy.register(p.id,p.name),n=p.name||r.user.displayName||'mortal',cap=r.isNew?`🌊 *WELCOME TO RYUDEN, ${n.toUpperCase()}!*\n\n> 👤 *${n}*\n\nI'm *Rimuru Tempest* — guardian of the JTF Casino and your guide through Ryuden.\n\nYour account has been registered with *${economy.fmt(r.user.wallet)}* starting coins. Your wallet, bank and game progress are stored persistently.\n\nUse */menu* anytime to explore.`:`🌊 *WELCOME BACK TO RYUDEN!*\n\n> 👤 *${n}*\n\nYou're already registered. I'm *Rimuru Tempest*, guardian of the JTF Casino and your companion throughout Ryuden.\n\nYour account, wallet, bank and game progress are ready.\n\nUse */menu* to continue.`;const image=await fs.readFile(START_IMAGE_PATH);await s.sendMessage(p.jid,{image,caption:cap},{quoted:m});return true}
  if(c.command==='/menu'){await menu(s,m);return true}if(['/lb','/leaderboard'].includes(c.command)){await leaderboard(s,m);return true}if(['/p','/profile'].includes(c.command)){await profile(s,m);return true}if(c.command==='/casino'){await casinoPanel(s,m);return true}if(c.command==='/games'){await games(s,m);return true}if(c.command==='/utilities'){await utilities(s,m);return true}
  if(c.command==='/help'){const pg=Number(c.args[0]||0),pages={1:'❓ *HELP • PAGE 1/3*\n\n🌊 /start — registration / welcome back\n📜 /menu — interactive menu\n👤 /p — player profile\n💰 /bal — balance\n🏦 /bank — bank status\n🏆 /lb — wealth leaderboard\n\n> Next: */help 2*',2:'❓ *HELP • PAGE 2/3 — ECONOMY*\n\n🏦 /dep [amount|all]\n💸 /wd [amount|all]\n💝 /donate [amount] — reply to a user\n🔁 /transfer [amount] — reply to a user\n\n> Next: */help 3*',3:'❓ *HELP • PAGE 3/3 — CASINO*\n\n🎰 /slots [amount]\n🪙 /cf [heads|tails] [amount]\n🎲 /dice [1-6] [amount]\n🎡 /roulette red|black|even|odd|low|high [amount]\n🎯 /roulette straight [0-36] [amount]\n\n> Use */casino* for the casino panel.'};await send(s,p.jid,m,pages[pg]||'❓ Help uses pages.\n\n> 📖 Start with */help 1*.');return true}
  let r=null;if(c.command==='/slots')r=await casino.slots(p.id,p.name,c.args[0]);if(['/cf','/coinflip'].includes(c.command))r=await casino.coinflip(p.id,p.name,c.args[0],c.args[1]);if(c.command==='/dice')r=await casino.dice(p.id,p.name,c.args[0],c.args[1]);if(c.command==='/roulette')r=await casino.roulette(p.id,p.name,c.args);if(!r)return false;if(!r.ok){await send(s,p.jid,m,r.message);return true}
  let t=c.command==='/slots'?`🎰 ${r.reels.join(' | ')}\n\n${r.payout?'✅ *YOU WIN!*':'❌ No luck.'}`:['/cf','/coinflip'].includes(c.command)?`🪙 The coin lands *${r.flip.toUpperCase()}*.\n\n${r.payout?'✅ *DOUBLE!*':'❌ You lost.'}`:c.command==='/dice'?`🎲 You picked *${r.pick}* — rolled *${r.rolled}*.\n\n${r.payout?'✅ *JACKPOT! 6×*':'❌ Missed.'}`:`🎡 The ball lands on *${r.number} ${r.color}*.\n\n${r.payout?'✅ *WIN!*':'❌ Lost.'}`;t+=`\n\n> 👤 *${p.name||'Player'}*\n💵 Bet: ${economy.fmt(r.bet)}\n${r.payout?`💰 Payout: ${economy.fmt(r.payout)}\n`:''}👛 Wallet: *${economy.fmt(r.user.wallet)}*`;await send(s,p.jid,m,t);logger.info({game:r.game,userId:p.id,bet:r.bet,payout:r.payout},'casino game completed');return true}
 return{route,section,menu,balance,leaderboard,profile}}
module.exports={createUi}
