'use strict'
const {database}=require('./auth-store'),{isOwner}=require('./access'),{isModerator}=require('./economy-router')
const VALID=new Set(['normal','casino','combat','duels','rpg'])
const LABEL={normal:'🌊 Ryuden',casino:'⌬ AXYN VAULT 🪙 {casino}',combat:'⚔️ Combat',duels:'🥊 Duels',rpg:'🏰 Odyssey City'}
const inviteCache=new Map(),INVITE_TTL_MS=5*60*1000
const COMMAND_ZONE=new Map([
 ['/casino','casino'],['/slots','casino'],['/cf','casino'],['/coinflip','casino'],['/dice','casino'],['/roulette','casino'],
 ['/combat','combat'],['/fight','combat'],['/duel','duels'],['/duels','duels'],['/challenge','duels'],['/cardbattle','duels'],['/hybridbattle','duels'],
 ['/story','normal'],['/shop','normal'],['/cards','normal'],['/collection','normal'],['/card','normal'],['/cardinfo','normal'],['/cardstats','normal'],['/deck','normal'],['/spawncard','normal'],['/missions','normal'],['/mission','normal'],
 ['/explore','rpg'],['/masters','rpg'],['/master','rpg'],['/train','rpg'],['/guild','rpg'],['/daily','rpg'],['/inventory','rpg'],['/npc','rpg']
])
function db(){const d=database();if(!d)throw Error('DATABASE_URL is required for zones');return d}
let ready=false
async function ensureSchema(){if(ready)return;await db().query(`CREATE TABLE IF NOT EXISTS rimuru_wa_zones(group_jid TEXT PRIMARY KEY,zone TEXT NOT NULL,display_name TEXT NOT NULL DEFAULT '',set_by TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); ALTER TABLE rimuru_wa_zones DROP CONSTRAINT IF EXISTS rimuru_wa_zones_zone_check; ALTER TABLE rimuru_wa_zones ADD CONSTRAINT rimuru_wa_zones_zone_check CHECK(zone IN ('normal','casino','combat','duels','rpg')); CREATE UNIQUE INDEX IF NOT EXISTS rimuru_wa_one_group_per_zone ON rimuru_wa_zones(zone);`);ready=true}
async function zoneFor(jid){if(!String(jid).endsWith('@g.us'))return null;await ensureSchema();return(await db().query('SELECT * FROM rimuru_wa_zones WHERE group_jid=$1',[jid])).rows[0]||null}
async function groupFor(zone){await ensureSchema();return(await db().query('SELECT * FROM rimuru_wa_zones WHERE zone=$1',[zone])).rows[0]||null}
async function allZones(){await ensureSchema();return(await db().query('SELECT * FROM rimuru_wa_zones ORDER BY zone')).rows}
function required(command){return COMMAND_ZONE.get(String(command||'').toLowerCase())||null}
function sectionRequirement(id,battleOrigin){const x=String(id||'');if(['start_casino','menu_casino'].includes(x)||x.startsWith('casino_'))return'casino';if(x==='rpg_combat'||x.startsWith('rpg_battle_'))return battleOrigin==='story'?'normal':battleOrigin==='rpg'?'rpg':'combat';if(x.startsWith('duel_'))return'duels';if(['rpg_story','rpg_story_continue','rpg_shop','rpg_shop_skills','rpg_missions'].includes(x)||x.startsWith('rpg_buy_'))return'normal';if(['rpg_explore','rpg_master','rpg_train','rpg_guild','rpg_daily','rpg_inventory'].includes(x)||x.startsWith('rpg_masters_page_')||x.startsWith('rpg_master_'))return'rpg';return null}
async function inviteLink(sock,target){const configured=String(process.env.RYUDEN_COMMUNITY_URL||'').trim();if(!target?.group_jid)return configured||null;const cached=inviteCache.get(target.group_jid);if(cached&&cached.expiresAt>Date.now())return cached.url;try{const code=await sock.groupInviteCode(target.group_jid);if(code){const url=`https://chat.whatsapp.com/${code}`;inviteCache.set(target.group_jid,{url,expiresAt:Date.now()+INVITE_TTL_MS});return url}}catch{}return configured||null}
async function wrongZone(sock,m,need,sendUrlButton,detail=''){const jid=m.key.remoteJid,target=await groupFor(need).catch(()=>null),destination=target?.display_name||LABEL[need]||'the correct Ryuden group',body=`📍 *WRONG ZONE*\n\nThis belongs in *${destination}*.\n${detail||'Tap below to open the correct Ryuden Community group.'}`,url=await inviteLink(sock,target);if(url&&sendUrlButton){await sendUrlButton(sock,jid,body,'LILY • JTF × RYUDEN','🌊 Go to Ryuden Community',url,m);return true}await sock.sendMessage(jid,{text:`${body}\n\n> I couldn't fetch the Community link right now. Ask a Ryuden admin for an invite.`},{quoted:m});return true}
async function guardZone(sock,m,need,sendUrlButton){if(!need)return false;const jid=m.key.remoteJid,here=await zoneFor(jid);if(here?.zone===need)return false;return wrongZone(sock,m,need,sendUrlButton)}
async function guard(sock,m,command,sendUrlButton){return guardZone(sock,m,required(command),sendUrlButton)}
async function guardSection(sock,m,id,battleOrigin,sendUrlButton){return guardZone(sock,m,sectionRequirement(id,battleOrigin),sendUrlButton)}
async function handle(sock,m,c,userId){if(!['/setzone','/zone','/zones'].includes(c.command))return false;const jid=m.key.remoteJid;if(c.command==='/zone'){const z=await zoneFor(jid);await sock.sendMessage(jid,{text:z?`📍 This group is registered as *${LABEL[z.zone]}*.`:'📍 This group has no Lily zone assigned.'},{quoted:m});return true}if(c.command==='/zones'){await ensureSchema();const rows=(await db().query('SELECT * FROM rimuru_wa_zones ORDER BY zone')).rows;await sock.sendMessage(jid,{text:`🗺️ *LILY COMMUNITY ZONES*\n\n${rows.length?rows.map(x=>`${LABEL[x.zone]} — *${x.display_name||'Registered group'}*`).join('\n'):'No zones registered yet.'}`},{quoted:m});return true}if(!(isOwner(userId)||await isModerator(userId))){await sock.sendMessage(jid,{text:'🛡️ Only the Original Owner or a Lily moderator can configure zones.'},{quoted:m});return true}if(!String(jid).endsWith('@g.us')){await sock.sendMessage(jid,{text:'📍 Run */setzone* inside the group you want to register.'},{quoted:m});return true}const z=String(c.args[0]||'').toLowerCase();if(!VALID.has(z)){await sock.sendMessage(jid,{text:'Use */setzone normal*, */setzone casino*, */setzone combat*, */setzone duels*, or */setzone rpg*.'},{quoted:m});return true}let name='';try{name=(await sock.groupMetadata(jid))?.subject||''}catch{}await ensureSchema();await db().query(`INSERT INTO rimuru_wa_zones(group_jid,zone,display_name,set_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_jid) DO UPDATE SET zone=EXCLUDED.zone,display_name=EXCLUDED.display_name,set_by=EXCLUDED.set_by,updated_at=NOW()`,[jid,z,name,userId]);await sock.sendMessage(jid,{text:`✅ *ZONE REGISTERED*\n\n${name?`*${name}*\n`:''}${LABEL[z]}\n\nLily will now enforce features assigned to this zone.`},{quoted:m});return true}
module.exports={ensureSchema,zoneFor,groupFor,allZones,guard,guardZone,guardSection,handle,required,sectionRequirement,wrongZone,inviteLink,LABEL,_test:{inviteCache}}
